import type { ScreenId } from '@/app/state/demoTypes'
import type { ScreenMeta } from '../contracts'
import { ALL_COUNTRIES } from '../countries'

export const SERVICES_SCREENS = {
  'pi.messages.overview': {
    id: 'pi.messages.overview',
    label: 'PI Messages inbox',
    runtimeScreen: 'messages',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'mock-driven',
    layoutFamily: 'messages',
    componentPath: 'src/app/screens/messages/MessagesScreen.tsx',
    features: [],
    screenshots: ['screenshots/52.png'],
    similarTo: ['pi.more.overview', 'pi.analytics.overview'],
  },
  'pi.my-banker.recommendations': {
    id: 'pi.my-banker.recommendations',
    label: 'PI My Banker recommendations',
    runtimeScreen: 'my-banker',
    products: ['PI'],
    countries: ['RS'],
    designSystems: ['current'],
    status: 'mock-driven',
    layoutFamily: 'products',
    componentPath: 'src/app/screens/my-banker/MyBankerScreen.tsx',
    features: ['fx_rsMyBanker'],
    screenshots: [],
    similarTo: ['pi.products.overview', 'pi.products.detail'],
  },
  'pi.prime.overview': {
    id: 'pi.prime.overview',
    label: 'PI Prime overview',
    runtimeScreen: 'prime',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'prime',
    componentPath: 'src/app/screens/prime/PrimeScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: [],
  },
  'pi.prime.appointments': {
    id: 'pi.prime.appointments',
    label: 'PI Prime appointments',
    runtimeScreen: 'appointments',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'prime',
    componentPath: 'src/app/screens/appointments/AppointmentScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.prime.overview'],
  },
  'pi.prime.call-request': {
    id: 'pi.prime.call-request',
    label: 'PI Prime call request',
    runtimeScreen: 'request-call',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'prime',
    componentPath: 'src/app/screens/appointments/RequestCallScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.prime.overview', 'pi.prime.appointments'],
  },
  'pi.more.overview': {
    id: 'pi.more.overview',
    label: 'PI More overview',
    runtimeScreen: 'more',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'service-menu',
    componentPath: 'src/app/screens/more/MoreScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.documents.overview', 'pi.settings.overview', 'pi.contacts.overview'],
  },
  'pi.documents.overview': {
    id: 'pi.documents.overview',
    label: 'PI Documents overview',
    runtimeScreen: 'documents',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'messages',
    componentPath: 'src/app/screens/documents/DocumentsScreen.tsx',
    features: [],
    screenshots: ['screenshots/Documents.png'],
    similarTo: ['pi.messages.overview', 'pi.more.overview'],
  },
  'pi.settings.overview': {
    id: 'pi.settings.overview',
    label: 'PI Settings overview',
    runtimeScreen: 'settings',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'service-menu',
    componentPath: 'src/app/screens/settings/SettingsScreen.tsx',
    features: [],
    screenshots: ['screenshots/Settings.png'],
    similarTo: ['pi.more.overview', 'pi.contacts.overview'],
  },
  'pi.contacts.overview': {
    id: 'pi.contacts.overview',
    label: 'PI Contacts overview',
    runtimeScreen: 'contacts',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'contacts',
    componentPath: 'src/app/screens/contacts/ContactsScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.more.overview'],
  },
} satisfies Partial<Record<ScreenId, ScreenMeta>>
