import { defineTemplate, screenshotUrl } from '../templateDefaults'
import type { TemplateRegistryItem } from '../contracts'
export const SERVICES_TEMPLATES: readonly TemplateRegistryItem[] = [
  defineTemplate({
    id: 'template-52',
    name: '52',
    sourcePath: 'screenshots/52.png',
    imageSrc: screenshotUrl('52.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'messages',
    runtimeScreenId: 'pi.messages.overview',
    relatedScreens: ['pi.messages.overview', 'platform.design-system'],
    flowIds: ['pi.header-to-messages'],
    relatedComponents: [
      'messages.inbox-list',
      'messages.mailbox-tabs',
      'accounts.transaction-search',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'messages-inbox',
    implementationPath: 'src/app/screens/messages/MessagesScreen.tsx',
    implementationStatus: 'reconstructed-code',
    reuseContract: {
      role: 'runtime-screen',
      dataSources: ['src/app/config/messagesConfig.ts'],
      assemblyRules: [
        'Use the runtime Messages screen and messages config for prompt-built mailbox flows.',
        'Inbox/Outbox state changes should reuse MessagesMailboxTabs rather than separate tab implementations.',
      ],
    },
    reuseNotes: [
      'The runtime Messages screen is reconstructed from this template and uses the same country-addressable message config as the Design System preview.',
      'Reuses the account search bar, AppIcon header actions, two-tab bar, date/message row, new badge, and dot-menu patterns.',
      'The screenshot remains source evidence; the Design System preview renders reconstructed JSX while the header Messages icon opens the runtime screen.',
    ],
  }),
  defineTemplate({
    id: 'template-contact',
    name: 'Contact',
    sourcePath: 'screenshots/Contact.png',
    imageSrc: screenshotUrl('Contact.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'contacts',
    relatedScreens: ['pi.contacts.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-more-to-contacts'],
    relatedComponents: ['contacts.navigation-card', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'contact-info-sheet',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the contact information bottom sheet with a dark backdrop, close action, and reusable contact action cards.',
      'Uses existing contact iconography so support/contact sheet flows can be composed without screenshot assets.',
    ],
  }),
  defineTemplate({
    id: 'template-documents',
    name: 'Documents',
    sourcePath: 'screenshots/Documents.png',
    imageSrc: screenshotUrl('Documents.png'),
    width: 377,
    height: 863,
    format: 'png',
    screenFamily: 'messages',
    runtimeScreenId: 'pi.documents.overview',
    relatedScreens: ['pi.documents.overview', 'pi.messages.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-more-to-documents'],
    relatedComponents: [
      'shell.page-header',
      'accounts.transaction-search',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'documents',
    implementationPath: 'src/app/screens/documents/DocumentsScreen.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Documents list as the same family as Messages, reusing the shared header and search treatment but removing the mailbox tabs and per-row dot menu.',
      'The More > Documents runtime screen and the Design System Template preview both read the same `documentsConfig.ts` grouped-list data.',
    ],
  }),
  defineTemplate({
    id: 'template-message',
    name: 'Message',
    sourcePath: 'screenshots/Message.png',
    imageSrc: screenshotUrl('Message.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'messages',
    relatedScreens: ['pi.messages.overview', 'platform.design-system'],
    flowIds: ['pi.header-to-messages'],
    relatedComponents: ['messages.inbox-list', 'ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'message-detail',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the message detail layout with back chrome, title/date, media placeholder, body copy, primary CTA, and link action.',
      'Complements template 52 by covering the detail-side message pattern without introducing a runtime detail screen yet.',
    ],
  }),
  defineTemplate({
    id: 'template-settings',
    name: 'Settings',
    sourcePath: 'screenshots/Settings.png',
    imageSrc: screenshotUrl('Settings.png'),
    width: 754,
    height: 1628,
    format: 'png',
    screenFamily: 'service-menu',
    runtimeScreenId: 'pi.settings.overview',
    relatedScreens: ['pi.settings.overview', 'pi.more.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-more-to-settings'],
    relatedComponents: [
      'shell.page-header',
      'ui.section-heading-divider',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'settings',
    implementationPath: 'src/app/screens/settings/SettingsScreen.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Settings screen as a shared PageHeader plus section-heading/divider and chevron-list rows driven by a common settings config.',
      'The More > Settings runtime screen and the Design System Template preview both read the same `settingsConfig.ts` section data so copy and structure stay aligned.',
    ],
  }),
  defineTemplate({
    id: 'template-more-menu-code',
    name: 'More menu',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::more-menu',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'service-menu',
    runtimeScreenId: 'pi.more.overview',
    relatedScreens: ['pi.more.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-more-to-contacts', 'pi.home-to-more-to-documents', 'pi.home-to-more-to-settings'],
    relatedComponents: ['more.card-grid', 'shell.bottom-navigation', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'more-menu',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template derived from the country-aware More card matrix.',
      'Reuses the top-level header, More card row composition, icon registry, and five-tab bottom navigation.',
    ],
  }),
  defineTemplate({
    id: 'template-contacts-directory-code',
    name: 'Contacts directory',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::contacts-directory',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'contacts',
    runtimeScreenId: 'pi.contacts.overview',
    relatedScreens: ['pi.contacts.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-more-to-contacts'],
    relatedComponents: [
      'contacts.navigation-card',
      'accounts.transaction-search',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'contacts-directory',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for a full Contacts directory surface, complementing the existing contact bottom-sheet screenshot template.',
      'Reuses the search strip, section divider, contact action cards, and centralized contact icons.',
    ],
  }),
  defineTemplate({
    id: 'template-messages-outbox-code',
    name: 'Messages outbox',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::messages-outbox',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'messages',
    runtimeScreenId: 'pi.messages.overview',
    relatedScreens: ['pi.messages.overview', 'platform.design-system'],
    flowIds: ['pi.header-to-messages'],
    relatedComponents: [
      'messages.inbox-list',
      'messages.mailbox-tabs',
      'accounts.transaction-search',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'messages-outbox',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only mailbox variant that reuses the template 52 Messages family but selects Outbox data from messagesConfig.',
      'Gives future prompt-driven flows both inbox and sent-message list patterns without needing an extra PNG.',
    ],
  }),
  defineTemplate({
    id: 'template-prime-benefits-code',
    name: 'Prime benefits',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::prime-benefits',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'prime',
    runtimeScreenId: 'pi.prime.overview',
    relatedScreens: ['pi.prime.overview', 'platform.design-system'],
    flowIds: [],
    relatedComponents: ['prime.benefits-tab', 'ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'prime-benefits',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for Prime benefits and premium-service storytelling.',
      'Reuses the status/card + checklist composition so Prime prompts can be built from known screen parts instead of invented cards.',
    ],
  }),
  defineTemplate({
    id: 'template-logout-confirmation-code',
    name: 'Logout confirmation',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::logout-confirmation',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'service-menu',
    relatedScreens: ['pi.more.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-more-to-contacts', 'pi.home-to-more-to-documents', 'pi.home-to-more-to-settings'],
    relatedComponents: [
      'dialogs.logout-confirmation',
      'more.card-grid',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'logout-confirmation',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the iOS-style logout confirmation overlay over the More surface.',
      'Reuses the actual LogoutConfirmDialog component so destructive/confirmation prompts stay visually consistent.',
    ],
  }),
]
