import { IDENTITY_CUSTOM_ICONS } from './domains/identity/custom'
import { composeRegistry } from '@/app/registry/domains/composeRegistry'
import { SHARED_CUSTOM_ICONS } from './domains/shared/custom'
import { ANALYTICS_CUSTOM_ICONS } from './domains/analytics/custom'
import { INVESTMENTS_CUSTOM_ICONS } from './domains/investments/custom'
import { KIDS_CUSTOM_ICONS } from './domains/kids/custom'
import { PLATFORM_CUSTOM_ICONS } from './domains/platform/custom'
import { PAYMENTS_CUSTOM_ICONS } from './domains/payments/custom'
import { SERVICES_CUSTOM_ICONS } from './domains/services/custom'
import { ACCOUNTS_CUSTOM_ICONS } from './domains/accounts/custom'
import { CARDS_CUSTOM_ICONS } from './domains/cards/custom'
import { PRODUCTS_CUSTOM_ICONS } from './domains/products/custom'
export const CUSTOM_ICON_DOMAINS = [
  SHARED_CUSTOM_ICONS,
  ANALYTICS_CUSTOM_ICONS,
  INVESTMENTS_CUSTOM_ICONS,
  KIDS_CUSTOM_ICONS,
  PLATFORM_CUSTOM_ICONS,
  PAYMENTS_CUSTOM_ICONS,
  SERVICES_CUSTOM_ICONS,
  ACCOUNTS_CUSTOM_ICONS,
  CARDS_CUSTOM_ICONS,
  PRODUCTS_CUSTOM_ICONS,
  IDENTITY_CUSTOM_ICONS,
] as const
const CUSTOM_ICON_ORDER = [
  'edit-pencil',
  'trash-2',
  'analytics-donut-toggle',
  'analytics-bars-toggle',
  'header-profile',
  'header-messages',
  'help-circle',
  'play',
  'logout',
  'nav-home',
  'nav-analytics',
  'nav-payments',
  'nav-products',
  'nav-more',
  'robo-nav-portfolio',
  'robo-nav-invest',
  'robo-nav-explore',
  'hu-kids-request-money',
  'hu-kids-account-details',
  'hu-kids-learn',
  'hu-kids-more-options',
  'hu-kids-saving',
  'amount-hide',
  'amount-show',
  'search',
  'filters',
  'radio-unselected',
  'radio-selected',
  'demo-chevron-down',
  'demo-settings',
  'demo-reset',
  'clear-results',
  'payment-create-qr',
  'payment-scan-qr',
  'payment-photo-camera',
  'payment-use-account',
  'payment-new',
  'payment-templates',
  'payment-recurrent',
  'payment-card-repayment',
  'payment-exchange-rates',
  'new-payment-domestic',
  'new-payment-foreign',
  'currency-exchange',
  'exchange-rates',
  'investment-trend-up',
  'investment-trend-down',
  'chevron-link',
  'chevron-left',
  'chevron-right',
  'chevron-down',
  'chevron-down-wide',
  'chevron-up',
  'trade-buy',
  'trade-sell',
  'back-heavy',
  'back-line',
  'info-circle',
  'warning-small',
  'close-x',
  'close-flow',
  'insurance-calendar',
  'robo-withdraw',
  'robo-goal-settings',
  'panel-smart-banking',
  'panel-share-screen',
  'prime-check',
  'prime-direction',
  'prime-email',
  'prime-book-appointment',
  'prime-request-call',
  'accounts-coins',
  'account-details',
  'account-info',
  'account-options',
  'account-option-share-info',
  'account-option-push-notifications',
  'account-option-statement',
  'investment-history',
  'investment-to-approve',
  'investment-download-report',
  'account-option-create-paycode',
  'account-option-change-name',
  'add-money',
  'invest-action',
  'add-circle',
  'plus',
  'more-horizontal',
  'user-event-badge',
  'user-event-refresh',
  'recurring-contribution',
  'refresh',
  'keypad-backspace',
  'mcash',
  'copy-documents',
  'share-filled',
  'transaction-transfer',
  'contact-prime',
  'contact-location',
  'contact-time',
  'contact-phone',
  'contact-block',
  'contact-email',
  'shopsmart-store',
  'contact-website',
  'contact-youtube',
  'contact-x',
  'grid-2x2',
  'block-card',
  'show-card-details',
  'view-pin',
  'standing-order',
  'redo-payment',
  'request-chargeback',
  'send-payment',
  'investment-more-details',
  'investment-ex-ante',
  'investment-documents',
  'investment-important-info',
  'investment-disclaimer',
  'card-options-apple-pay',
  'card-options-mastercard',
  'card-options-registrations',
  'card-options-limits',
  'card-options-change-name',
  'card-options-delivery-address',
  'card-options-reissue',
  'file-pdf',
  'file-word',
  'robo-goal-wealth',
  'robo-goal-inflation',
  'robo-goal-unforeseen',
  'robo-goal-purchase',
  'robo-goal-retirement',
  'investment-goals-product',
] as const
export const CUSTOM_ICONS = composeRegistry('CUSTOM_ICONS', CUSTOM_ICON_DOMAINS, CUSTOM_ICON_ORDER)
