/**
 * Lucide icons that are centralised here rather than imported ad hoc, so the
 * Design System inventory and the icon audits can see every one of them.
 *
 * Extracted verbatim from AppIcon.tsx.
 */
import {
  AlertTriangle,
  ArrowRight,
  Bike,
  BookOpen,
  CalendarDays,
  Camera,
  CircleDollarSign,
  ClipboardCheck,
  CreditCard,
  Download,
  Eye,
  EyeOff,
  Gift,
  Landmark,
  Lock,
  Palette,
  PiggyBank,
  ReceiptText,
  Repeat2,
  Send,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Trophy,
  UserRound,
  Users,
  WalletCards,
} from "lucide-react";
import type { LucideIconDefinition } from "./iconTypes";

export const LUCIDE_ICONS = {
  "wallet-cards": {
    source: "lucide",
    label: "Wallet cards",
    category: "External Lucide",
    width: 32,
    height: 32,
    component: WalletCards,
    usage: ["Payments wallet illustration", "AccountOptionsScreen", "KidsMarketHomeApp"],
  },
  "shopping-bag": {
    source: "lucide",
    label: "Shopping bag",
    category: "External Lucide",
    width: 32,
    height: 32,
    component: ShoppingBag,
    usage: ["ProductMenuCard", "KidsMarketHomeApp"],
  },
  "arrow-right": {
    source: "lucide",
    label: "Arrow right",
    category: "External Lucide",
    width: 32,
    height: 32,
    component: ArrowRight,
    usage: ["ProductMenuCard", "QuickActions"],
  },
  camera: {
    source: "lucide",
    label: "Camera",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Camera,
    usage: ["DomesticPaymentFlowScreens"],
  },
  landmark: {
    source: "lucide",
    label: "Landmark",
    category: "External Lucide",
    width: 25,
    height: 25,
    component: Landmark,
    usage: ["TransactionDetailScreen"],
  },
  repeat: {
    source: "lucide",
    label: "Repeat",
    category: "External Lucide",
    width: 26,
    height: 26,
    component: Repeat2,
    usage: ["TransactionDetailScreen"],
  },
  lock: {
    source: "lucide",
    label: "Lock",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Lock,
    usage: ["InactiveState"],
  },
  "alert-triangle": {
    source: "lucide",
    label: "Alert triangle",
    category: "External Lucide",
    width: 20,
    height: 20,
    component: AlertTriangle,
    usage: ["UnplannedBanner"],
  },
  "credit-card": {
    source: "lucide",
    label: "Credit card",
    category: "External Lucide",
    width: 20,
    height: 20,
    component: CreditCard,
    usage: ["QuickActions"],
  },
  download: {
    source: "lucide",
    label: "Download",
    category: "Actions",
    width: 20,
    height: 20,
    component: Download,
    usage: ["DesignSystemPage Icons inventory"],
  },
  send: {
    source: "lucide",
    label: "Send",
    category: "External Lucide",
    width: 20,
    height: 20,
    component: Send,
    usage: ["QuickActions", "KidsMarketHomeApp"],
  },
  bike: {
    source: "lucide",
    label: "Bike",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Bike,
    usage: ["KidsMarketHomeApp"],
  },
  "book-open": {
    source: "lucide",
    label: "Book open",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: BookOpen,
    usage: ["KidsMarketHomeApp"],
  },
  "calendar-days": {
    source: "lucide",
    label: "Calendar days",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: CalendarDays,
    usage: ["KidsMarketHomeApp"],
  },
  "circle-dollar-sign": {
    source: "lucide",
    label: "Circle dollar sign",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: CircleDollarSign,
    usage: ["KidsMarketHomeApp"],
  },
  "clipboard-check": {
    source: "lucide",
    label: "Clipboard check",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: ClipboardCheck,
    usage: ["KidsMarketHomeApp"],
  },
  eye: {
    source: "lucide",
    label: "Eye",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Eye,
    usage: ["KidsMarketHomeApp"],
  },
  "eye-off": {
    source: "lucide",
    label: "Eye off",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: EyeOff,
    usage: ["KidsMarketHomeApp"],
  },
  gift: {
    source: "lucide",
    label: "Gift",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Gift,
    usage: ["KidsMarketHomeApp"],
  },
  palette: {
    source: "lucide",
    label: "Palette",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Palette,
    usage: ["KidsMarketHomeApp"],
  },
  "piggy-bank": {
    source: "lucide",
    label: "Piggy bank",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: PiggyBank,
    usage: ["KidsMarketHomeApp"],
  },
  "receipt-text": {
    source: "lucide",
    label: "Receipt text",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: ReceiptText,
    usage: ["KidsMarketHomeApp"],
  },
  "shield-check": {
    source: "lucide",
    label: "Shield check",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: ShieldCheck,
    usage: ["KidsMarketHomeApp"],
  },
  "sliders-horizontal": {
    source: "lucide",
    label: "Sliders horizontal",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: SlidersHorizontal,
    usage: ["KidsMarketHomeApp"],
  },
  trophy: {
    source: "lucide",
    label: "Trophy",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Trophy,
    usage: ["KidsMarketHomeApp"],
  },
  "user-round": {
    source: "lucide",
    label: "User round",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: UserRound,
    usage: ["KidsMarketHomeApp"],
  },
  users: {
    source: "lucide",
    label: "Users",
    category: "External Lucide",
    width: 24,
    height: 24,
    component: Users,
    usage: ["KidsMarketHomeApp"],
  },
} satisfies Record<string, LucideIconDefinition>;
