import type { ScreenId } from '@/app/state/demoTypes'
import type { ScreenMeta } from '../contracts'
import { ALL_COUNTRIES } from '../countries'

export const ACCOUNTS_SCREENS = {
  'pi.transactions.overview': {
    id: 'pi.transactions.overview',
    label: 'PI Transactions',
    runtimeScreen: 'transactions',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'mock-driven',
    layoutFamily: 'account-detail',
    componentPath: 'src/app/screens/accounts/TransactionsScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.account.detail'],
  },
  'pi.account.detail': {
    id: 'pi.account.detail',
    label: 'PI Account detail',
    runtimeScreen: 'account-detail',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'account-detail',
    componentPath: 'src/app/screens/accounts/AccountDetailScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.account.details-info', 'pi.account.options'],
  },
  'pi.account.details-info': {
    id: 'pi.account.details-info',
    label: 'PI Account details info',
    runtimeScreen: 'account-details-info',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'account-detail',
    componentPath: 'src/app/screens/accounts/AccountDetailsInfoScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.account.detail', 'pi.account.options'],
  },
  'pi.account.options': {
    id: 'pi.account.options',
    label: 'PI Account options',
    runtimeScreen: 'account-options',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'account-options',
    componentPath: 'src/app/screens/accounts/AccountOptionsScreen.tsx',
    features: [],
    screenshots: ['screenshots/account-options.png'],
    similarTo: ['pi.account.detail', 'pi.account.details-info'],
  },
  'pi.transaction.detail': {
    id: 'pi.transaction.detail',
    label: 'PI Transaction detail',
    runtimeScreen: 'transaction-detail',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'implemented',
    layoutFamily: 'account-detail',
    componentPath: 'src/app/screens/payments/DomesticPaymentFlowScreens.tsx',
    features: ['fx_newPaymentsHub'],
    screenshots: ['screenshots/Transaction detail.png'],
    similarTo: ['pi.account.detail', 'pi.payment.domestic-create'],
  },
} satisfies Partial<Record<ScreenId, ScreenMeta>>
