import { defineTemplate, screenshotUrl } from '../templateDefaults'
import type { TemplateRegistryItem } from '../contracts'
export const ACCOUNTS_TEMPLATES: readonly TemplateRegistryItem[] = [
  defineTemplate({
    id: 'template-account-options',
    name: 'Account options',
    sourcePath: 'screenshots/account-options.png',
    imageSrc: screenshotUrl('account-options.png'),
    width: 375,
    height: 1038,
    format: 'png',
    screenFamily: 'account-options',
    runtimeScreenId: 'pi.account.options',
    relatedScreens: ['pi.account.options', 'pi.account.detail', 'platform.design-system'],
    flowIds: ['pi.home-to-account-detail'],
    relatedComponents: [
      'accounts.action-bar',
      'products.product-card',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'account-options',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the account options list and product recommendation cards as JSX using the same account-details data already used by the runtime AccountOptionsScreen.',
      'Introduces reusable account-option icon mapping and product promo card composition for follow-up account option flows.',
    ],
  }),
  defineTemplate({
    id: 'template-homepage',
    name: 'Homepage',
    sourcePath: 'screenshots/homepage.png',
    imageSrc: screenshotUrl('homepage.png'),
    width: 750,
    height: 1624,
    format: 'png',
    screenFamily: 'account-detail',
    relatedScreens: ['pi.account.detail', 'pi.home.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-account-detail'],
    relatedComponents: [
      'home.account-balance-card',
      'accounts.transaction-search',
      'accounts.transaction-row',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'account-detail-homepage',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'The source filename is `homepage`, but the screenshot content is an account-detail home screen; the registry maps it to the reconstructed account-detail homepage preview.',
      'Reuses account balance card, shortcut, search, transaction-list, and five-item bottom navigation patterns for future account flows.',
    ],
  }),
  defineTemplate({
    id: 'template-panel',
    name: 'Panel',
    sourcePath: 'screenshots/Panel.png',
    imageSrc: screenshotUrl('Panel.png'),
    width: 375,
    height: 809,
    format: 'png',
    screenFamily: 'account-detail',
    relatedScreens: ['pi.account.detail', 'platform.design-system'],
    flowIds: ['pi.home-to-account-detail'],
    relatedComponents: [
      'shell.bottom-sheet',
      'ui.radio-button',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'account-selection-panel',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the account-selection bottom sheet with dark backdrop, sheet header/close action, radio account rows, and Select CTA.',
      'Shares the same radio option row primitive with Generate Token and Product selection.',
    ],
  }),
  defineTemplate({
    id: 'template-transaction-detail',
    name: 'Transaction detail',
    sourcePath: 'screenshots/Transaction detail.png',
    imageSrc: screenshotUrl('Transaction detail.png'),
    width: 375,
    height: 1855,
    format: 'png',
    screenFamily: 'account-detail',
    runtimeScreenId: 'pi.transaction.detail',
    relatedScreens: ['pi.transaction.detail', 'pi.account.detail', 'platform.design-system'],
    flowIds: ['pi.transaction-redo-payment'],
    relatedComponents: [
      'transactions.detail',
      'payments.domestic-flow',
      'shell.page-header',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'transaction-detail',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the transaction detail screen with merchant summary, action shortcuts, spending insight chart, copyable details, and Show less action.',
      'Reuses read-only detail rows and shortcut primitives already introduced for payment/account templates.',
    ],
  }),
  defineTemplate({
    id: 'template-account-transactions-list-code',
    name: 'Account transactions list',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::account-transactions-list',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'account-detail',
    runtimeScreenId: 'pi.account.detail',
    relatedScreens: ['pi.account.detail', 'platform.design-system'],
    flowIds: ['pi.home-to-account-detail'],
    relatedComponents: [
      'home.account-balance-card',
      'accounts.transaction-search',
      'accounts.transaction-row',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'account-transactions-list',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only account transaction list template with account card, search strip, month divider, and transaction rows.',
      'Complements the account-detail homepage screenshot template with a denser list-first state for prompt-built account flows.',
    ],
  }),
]
