import {
  Send,
  Bike,
  BookOpen,
  CalendarDays,
  CircleDollarSign,
  ClipboardCheck,
  Eye,
  EyeOff,
  Gift,
  Palette,
  PiggyBank,
  ReceiptText,
  ShieldCheck,
  SlidersHorizontal,
  Trophy,
  UserRound,
  Users,
} from 'lucide-react'
import type { LucideIconDefinition } from '../../iconTypes'

export const KIDS_LUCIDE_ICONS = {
  send: {
    source: 'lucide',
    label: 'Send',
    category: 'External Lucide',
    width: 20,
    height: 20,
    component: Send,
    usage: ['QuickActions', 'KidsMarketHomeApp'],
  },
  bike: {
    source: 'lucide',
    label: 'Bike',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: Bike,
    usage: ['KidsMarketHomeApp'],
  },
  'book-open': {
    source: 'lucide',
    label: 'Book open',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: BookOpen,
    usage: ['KidsMarketHomeApp'],
  },
  'calendar-days': {
    source: 'lucide',
    label: 'Calendar days',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: CalendarDays,
    usage: ['KidsMarketHomeApp'],
  },
  'circle-dollar-sign': {
    source: 'lucide',
    label: 'Circle dollar sign',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: CircleDollarSign,
    usage: ['KidsMarketHomeApp'],
  },
  'clipboard-check': {
    source: 'lucide',
    label: 'Clipboard check',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: ClipboardCheck,
    usage: ['KidsMarketHomeApp'],
  },
  eye: {
    source: 'lucide',
    label: 'Eye',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: Eye,
    usage: ['KidsMarketHomeApp'],
  },
  'eye-off': {
    source: 'lucide',
    label: 'Eye off',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: EyeOff,
    usage: ['KidsMarketHomeApp'],
  },
  gift: {
    source: 'lucide',
    label: 'Gift',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: Gift,
    usage: ['KidsMarketHomeApp'],
  },
  palette: {
    source: 'lucide',
    label: 'Palette',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: Palette,
    usage: ['KidsMarketHomeApp'],
  },
  'piggy-bank': {
    source: 'lucide',
    label: 'Piggy bank',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: PiggyBank,
    usage: ['KidsMarketHomeApp'],
  },
  'receipt-text': {
    source: 'lucide',
    label: 'Receipt text',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: ReceiptText,
    usage: ['KidsMarketHomeApp'],
  },
  'shield-check': {
    source: 'lucide',
    label: 'Shield check',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: ShieldCheck,
    usage: ['KidsMarketHomeApp'],
  },
  'sliders-horizontal': {
    source: 'lucide',
    label: 'Sliders horizontal',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: SlidersHorizontal,
    usage: ['KidsMarketHomeApp'],
  },
  trophy: {
    source: 'lucide',
    label: 'Trophy',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: Trophy,
    usage: ['KidsMarketHomeApp'],
  },
  'user-round': {
    source: 'lucide',
    label: 'User round',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: UserRound,
    usage: ['KidsMarketHomeApp'],
  },
  users: {
    source: 'lucide',
    label: 'Users',
    category: 'External Lucide',
    width: 24,
    height: 24,
    component: Users,
    usage: ['KidsMarketHomeApp'],
  },
} satisfies Record<string, LucideIconDefinition>
