export type ColorPaletteId =
  | "neutral"
  | "action-teal"
  | "brand-red"
  | "product"
  | "semantic-green"
  | "warning-orange"
  | "peach"
  | "utility";

export type AppColorAuditStatus = "mapped" | "asset-exception" | "pending-review";

export interface DesignSystemPalette {
  id: ColorPaletteId;
  label: string;
  description: string;
}

export interface DesignSystemColor {
  id: string;
  name: string;
  paletteId: ColorPaletteId;
  lightHex: string;
  darkHex: string;
  sourceTokens: string[];
  usage: string;
  cssVariable: string;
  darkNote?: string;
}

export interface AppColorAuditItem {
  sourceColor: string;
  targetToken: string;
  targetHex: string;
  status: AppColorAuditStatus;
  usage: string;
  note?: string;
}

export const COLOR_SOURCE_AUDIT = {
  sourcePath: "screenshots/Colors.svg",
  extractedColorGroups: 66,
  solidColorGroups: 59,
  uniqueSolidColors: 48,
  normalizedColorsInRegistry: 50,
  gradientGroups: 1,
};

export const COLOR_PALETTES: DesignSystemPalette[] = [
  {
    id: "neutral",
    label: "Neutral / Primary",
    description: "Core backgrounds, surfaces, text, dividers, and icons.",
  },
  {
    id: "action-teal",
    label: "Action Teal",
    description: "Primary actions, selected states, active navigation, and informational surfaces.",
  },
  {
    id: "brand-red",
    label: "UniCredit Red",
    description: "Brand marks, destructive emphasis, and high-priority visual accents.",
  },
  {
    id: "product",
    label: "Product Tiles",
    description: "Product card surfaces and editorial offer backgrounds.",
  },
  {
    id: "semantic-green",
    label: "Semantic Green",
    description: "Success, positive, environmental, and specialty green accents.",
  },
  {
    id: "warning-orange",
    label: "Warning / Orange",
    description: "Warning, card-network adjacent, gold, and orange attention colors.",
  },
  {
    id: "peach",
    label: "Peach",
    description: "Soft supporting surfaces used in light illustrations and warm accents.",
  },
  {
    id: "utility",
    label: "Utility",
    description: "Special status and audit-only colors from the source SVG.",
  },
];

export const DESIGN_SYSTEM_COLORS: DesignSystemColor[] = [
  {
    id: "neutral-white",
    name: "White",
    paletteId: "neutral",
    lightHex: "#FFFFFF",
    darkHex: "#262626",
    sourceTokens: ["Primary / 100", "Primary / 600 Copy 2-5"],
    usage: "Light surfaces, cards, nav bars, and inverse text.",
    cssVariable: "--uc-neutral-white",
    darkNote: "Dark surfaces move to Primary 900 to keep contrast calm.",
  },
  {
    id: "neutral-100",
    name: "Neutral 100",
    paletteId: "neutral",
    lightHex: "#F5F5F5",
    darkHex: "#262626",
    sourceTokens: ["Primary / 200"],
    usage: "App background and subtle section background.",
    cssVariable: "--uc-neutral-100",
  },
  {
    id: "neutral-200",
    name: "Neutral 200",
    paletteId: "neutral",
    lightHex: "#E5E5E5",
    darkHex: "#454545",
    sourceTokens: ["Primary / 300"],
    usage: "Secondary separators and muted cards.",
    cssVariable: "--uc-neutral-200",
  },
  {
    id: "neutral-300",
    name: "Neutral 300",
    paletteId: "neutral",
    lightHex: "#D8D8D8",
    darkHex: "#535453",
    sourceTokens: ["Primary / 902"],
    usage: "Primary borders and divider lines.",
    cssVariable: "--uc-neutral-300",
  },
  {
    id: "neutral-400",
    name: "Neutral 400",
    paletteId: "neutral",
    lightHex: "#CCCCCC",
    darkHex: "#666666",
    sourceTokens: ["Primary / 600"],
    usage: "Disabled borders and low-emphasis controls.",
    cssVariable: "--uc-neutral-400",
  },
  {
    id: "neutral-500",
    name: "Neutral 500",
    paletteId: "neutral",
    lightHex: "#B9B9B9",
    darkHex: "#909090",
    sourceTokens: ["Primary / Main 22"],
    usage: "Secondary UI chrome and inactive indicators.",
    cssVariable: "--uc-neutral-500",
  },
  {
    id: "neutral-600",
    name: "Neutral 600",
    paletteId: "neutral",
    lightHex: "#999999",
    darkHex: "#B9B9B9",
    sourceTokens: ["Primary / 600 Copy"],
    usage: "Muted labels and secondary text.",
    cssVariable: "--uc-neutral-600",
  },
  {
    id: "neutral-650",
    name: "Neutral 650",
    paletteId: "neutral",
    lightHex: "#909090",
    darkHex: "#CCCCCC",
    sourceTokens: ["Primary / Main 26"],
    usage: "Status and chart helper labels.",
    cssVariable: "--uc-neutral-650",
  },
  {
    id: "neutral-700",
    name: "Neutral 700",
    paletteId: "neutral",
    lightHex: "#666666",
    darkHex: "#D8D8D8",
    sourceTokens: ["Primary / 901"],
    usage: "Secondary labels and inactive navigation text.",
    cssVariable: "--uc-neutral-700",
  },
  {
    id: "neutral-750",
    name: "Neutral 750",
    paletteId: "neutral",
    lightHex: "#535453",
    darkHex: "#E5E5E5",
    sourceTokens: ["Primary / Main Copy 3"],
    usage: "Deep muted product surfaces.",
    cssVariable: "--uc-neutral-750",
  },
  {
    id: "neutral-800",
    name: "Neutral 800",
    paletteId: "neutral",
    lightHex: "#454545",
    darkHex: "#F5F5F5",
    sourceTokens: ["Primary / Main 20"],
    usage: "Dense dark UI surfaces.",
    cssVariable: "--uc-neutral-800",
  },
  {
    id: "neutral-900",
    name: "Primary K1",
    paletteId: "neutral",
    lightHex: "#262626",
    darkHex: "#FFFFFF",
    sourceTokens: ["Primary / 900", "Primary / Main 21"],
    usage: "Primary text, icons, and strong dividers.",
    cssVariable: "--uc-primary-k1",
  },
  {
    id: "neutral-black",
    name: "Black",
    paletteId: "neutral",
    lightHex: "#000000",
    darkHex: "#FFFFFF",
    sourceTokens: ["Primary / Main"],
    usage: "Device chrome and true black shapes.",
    cssVariable: "--uc-primary-main",
  },
  {
    id: "teal-900",
    name: "Teal Deep",
    paletteId: "action-teal",
    lightHex: "#006375",
    darkHex: "#99D9D5",
    sourceTokens: ["Primary / Main 2", "Primary / 900 Copy 3", "Primary / Main 18"],
    usage: "Pressed action, deep selected state, and offer backgrounds.",
    cssVariable: "--uc-teal-900",
  },
  {
    id: "teal-700",
    name: "Teal Main",
    paletteId: "action-teal",
    lightHex: "#007A91",
    darkHex: "#00A197",
    sourceTokens: ["Primary / Main 3", "Primary / 900 2", "Primary / 900 16", "Primary / Main 27"],
    usage: "Primary action, active navigation, banners, and chart inflow.",
    cssVariable: "--uc-teal-main",
  },
  {
    id: "teal-650",
    name: "Teal Blue",
    paletteId: "action-teal",
    lightHex: "#05829A",
    darkHex: "#99D9D5",
    sourceTokens: ["Primary / Main 19"],
    usage: "Alternate selected teal for charts and status surfaces.",
    cssVariable: "--uc-teal-blue",
  },
  {
    id: "teal-600",
    name: "Teal Bright",
    paletteId: "action-teal",
    lightHex: "#00A197",
    darkHex: "#99D9D5",
    sourceTokens: ["Primary / Main 4"],
    usage: "Bright action accent and dark-mode active state.",
    cssVariable: "--uc-teal-bright",
  },
  {
    id: "teal-300",
    name: "Teal Soft",
    paletteId: "action-teal",
    lightHex: "#99D9D5",
    darkHex: "#007A91",
    sourceTokens: ["Primary / 900 3"],
    usage: "Soft active surface and light selected background.",
    cssVariable: "--uc-teal-soft",
  },
  {
    id: "teal-100",
    name: "Teal Pale",
    paletteId: "action-teal",
    lightHex: "#CCECEA",
    darkHex: "#006375",
    sourceTokens: ["Primary / 800"],
    usage: "Low-emphasis success/info background.",
    cssVariable: "--uc-teal-pale",
  },
  {
    id: "red-main",
    name: "UniCredit Red",
    paletteId: "brand-red",
    lightHex: "#E2001A",
    darkHex: "#E01E25",
    sourceTokens: ["Primary / Main 5", "Primary / 900 14"],
    usage: "Brand mark and primary brand accent.",
    cssVariable: "--uc-red-main",
  },
  {
    id: "red-bright",
    name: "Red Bright",
    paletteId: "brand-red",
    lightHex: "#E01E25",
    darkHex: "#E2001A",
    sourceTokens: ["Primary / 600 Copy 6"],
    usage: "Dark-mode brand accent and alert emphasis.",
    cssVariable: "--uc-red-bright",
  },
  {
    id: "red-card",
    name: "Red Card",
    paletteId: "brand-red",
    lightHex: "#B91823",
    darkHex: "#E01E25",
    sourceTokens: ["Primary / 600 Copy 2", "Primary / 900 13"],
    usage: "Card product tile and strong warning.",
    cssVariable: "--uc-red-card",
  },
  {
    id: "red-deep",
    name: "Red Deep",
    paletteId: "brand-red",
    lightHex: "#9A000B",
    darkHex: "#B91823",
    sourceTokens: ["Primary / 900 Copy", "Primary / Main 15"],
    usage: "Deep red surfaces and dark red accents.",
    cssVariable: "--uc-red-deep",
  },
  {
    id: "red-brown",
    name: "Red Brown",
    paletteId: "brand-red",
    lightHex: "#961414",
    darkHex: "#CF3524",
    sourceTokens: ["Primary / 900 4"],
    usage: "Legacy deep warning and decorative emphasis.",
    cssVariable: "--uc-red-brown",
  },
  {
    id: "product-blue-deep",
    name: "Product Blue Deep",
    paletteId: "product",
    lightHex: "#244858",
    darkHex: "#3F6A8B",
    sourceTokens: ["Primary / Main 6"],
    usage: "Account product tile.",
    cssVariable: "--uc-product-blue-deep",
  },
  {
    id: "product-slate",
    name: "Product Slate",
    paletteId: "product",
    lightHex: "#5E6F73",
    darkHex: "#B9B9B9",
    sourceTokens: ["Primary / 900 5"],
    usage: "Investments and neutral product tile.",
    cssVariable: "--uc-product-slate",
  },
  {
    id: "product-blue",
    name: "Product Blue",
    paletteId: "product",
    lightHex: "#3F6A8B",
    darkHex: "#99D9D5",
    sourceTokens: ["Primary / Main 7"],
    usage: "Insurance product tile.",
    cssVariable: "--uc-product-blue",
  },
  {
    id: "product-mauve",
    name: "Product Mauve",
    paletteId: "product",
    lightHex: "#A26077",
    darkHex: "#A26077",
    sourceTokens: ["Primary / Main 8"],
    usage: "Mortgage and loans product tile.",
    cssVariable: "--uc-product-mauve",
  },
  {
    id: "product-pink",
    name: "Product Pink",
    paletteId: "product",
    lightHex: "#DD1860",
    darkHex: "#DD1860",
    sourceTokens: ["Primary / 900 6"],
    usage: "Pink accent in product/editorial visuals.",
    cssVariable: "--uc-product-pink",
  },
  {
    id: "product-brown",
    name: "Product Brown",
    paletteId: "product",
    lightHex: "#5E3D32",
    darkHex: "#FFCBB1",
    sourceTokens: ["Primary / Main 9"],
    usage: "Warm product surface and illustration accent.",
    cssVariable: "--uc-product-brown",
  },
  {
    id: "green-deep",
    name: "Green Deep",
    paletteId: "semantic-green",
    lightHex: "#004C3D",
    darkHex: "#CCECEA",
    sourceTokens: ["Primary / Main Copy 2", "Primary / Main 16"],
    usage: "Deep green editorial and success surface.",
    cssVariable: "--uc-green-deep",
  },
  {
    id: "green-main",
    name: "Green Main",
    paletteId: "semantic-green",
    lightHex: "#007A6B",
    darkHex: "#99D9D5",
    sourceTokens: ["Primary / 900 15"],
    usage: "Positive/action green accent.",
    cssVariable: "--uc-green-main",
  },
  {
    id: "green-bright",
    name: "Green Bright",
    paletteId: "semantic-green",
    lightHex: "#008574",
    darkHex: "#00A197",
    sourceTokens: ["Primary / Main 17"],
    usage: "Bright green selected/semantic accent.",
    cssVariable: "--uc-green-bright",
  },
  {
    id: "green-success",
    name: "Green Success",
    paletteId: "semantic-green",
    lightHex: "#2FA358",
    darkHex: "#359F42",
    sourceTokens: ["Primary / Main 10"],
    usage: "Success and positive status.",
    cssVariable: "--uc-green-success",
  },
  {
    id: "green-status",
    name: "Green Status",
    paletteId: "semantic-green",
    lightHex: "#359F42",
    darkHex: "#3D7D43",
    sourceTokens: ["Primary / Main Copy 4"],
    usage: "Status green in audit and message states.",
    cssVariable: "--uc-green-status",
  },
  {
    id: "green-olive",
    name: "Green Olive",
    paletteId: "semantic-green",
    lightHex: "#3D7D43",
    darkHex: "#2FA358",
    sourceTokens: ["Primary / Main 23"],
    usage: "Olive product/status accent.",
    cssVariable: "--uc-green-olive",
  },
  {
    id: "orange-main",
    name: "Orange Main",
    paletteId: "warning-orange",
    lightHex: "#E67300",
    darkHex: "#F0871D",
    sourceTokens: ["Primary / Main Copy"],
    usage: "Warning and orange emphasis.",
    cssVariable: "--uc-orange-main",
  },
  {
    id: "orange-card",
    name: "Orange Card",
    paletteId: "warning-orange",
    lightHex: "#E67301",
    darkHex: "#F0871D",
    sourceTokens: ["Primary / Main 13"],
    usage: "Card/network adjacent orange.",
    cssVariable: "--uc-orange-card",
  },
  {
    id: "orange-bright",
    name: "Orange Bright",
    paletteId: "warning-orange",
    lightHex: "#F0871D",
    darkHex: "#FBB800",
    sourceTokens: ["Primary / 900 10"],
    usage: "Bright warning highlight.",
    cssVariable: "--uc-orange-bright",
  },
  {
    id: "orange-status",
    name: "Orange Status",
    paletteId: "warning-orange",
    lightHex: "#F26B08",
    darkHex: "#F0871D",
    sourceTokens: ["Primary / Main 24"],
    usage: "Status warning accent.",
    cssVariable: "--uc-orange-status",
  },
  {
    id: "yellow-gold",
    name: "Gold",
    paletteId: "warning-orange",
    lightHex: "#FBB800",
    darkHex: "#EDBA00",
    sourceTokens: ["Primary / 900 7"],
    usage: "Gold and attention highlights.",
    cssVariable: "--uc-yellow-gold",
  },
  {
    id: "yellow-muted",
    name: "Muted Gold",
    paletteId: "warning-orange",
    lightHex: "#DFA805",
    darkHex: "#FBB800",
    sourceTokens: ["Primary / 900 8"],
    usage: "Muted gold highlight.",
    cssVariable: "--uc-yellow-muted",
  },
  {
    id: "yellow-brown",
    name: "Brown Gold",
    paletteId: "warning-orange",
    lightHex: "#D1960A",
    darkHex: "#DFA805",
    sourceTokens: ["Primary / Main 11"],
    usage: "Deep gold/brown surface.",
    cssVariable: "--uc-yellow-brown",
  },
  {
    id: "yellow-main",
    name: "Yellow Main",
    paletteId: "warning-orange",
    lightHex: "#EDBA00",
    darkHex: "#FBB800",
    sourceTokens: ["Primary / 900 9"],
    usage: "Yellow highlight.",
    cssVariable: "--uc-yellow-main",
  },
  {
    id: "orange-deep",
    name: "Orange Deep",
    paletteId: "warning-orange",
    lightHex: "#E3690E",
    darkHex: "#F0871D",
    sourceTokens: ["Primary / Main 12"],
    usage: "Deep orange accent.",
    cssVariable: "--uc-orange-deep",
  },
  {
    id: "peach-100",
    name: "Peach 100",
    paletteId: "peach",
    lightHex: "#FFDAC0",
    darkHex: "#5E3D32",
    sourceTokens: ["Primary / 900 12"],
    usage: "Warm pale surface.",
    cssVariable: "--uc-peach-100",
  },
  {
    id: "peach-200",
    name: "Peach 200",
    paletteId: "peach",
    lightHex: "#FFCBB1",
    darkHex: "#5E3D32",
    sourceTokens: ["Primary / 900 11"],
    usage: "Warm supporting surface.",
    cssVariable: "--uc-peach-200",
  },
  {
    id: "peach-300",
    name: "Peach 300",
    paletteId: "peach",
    lightHex: "#FFBDA5",
    darkHex: "#5E3D32",
    sourceTokens: ["Primary / Main 14"],
    usage: "Warm supporting accent.",
    cssVariable: "--uc-peach-300",
  },
  {
    id: "red-status",
    name: "Status Red",
    paletteId: "utility",
    lightHex: "#CF3524",
    darkHex: "#E01E25",
    sourceTokens: ["Primary / Main 25"],
    usage: "Status red in audit and warning surfaces.",
    cssVariable: "--uc-status-red",
  },
  {
    id: "gold-brown",
    name: "Gold Brown",
    paletteId: "utility",
    lightHex: "#7E5B01",
    darkHex: "#DFA805",
    sourceTokens: ["Primary / Main Copy 4 2"],
    usage: "Utility brown/gold accent from source SVG.",
    cssVariable: "--uc-gold-brown",
  },
];

export const APP_COLOR_AUDIT: AppColorAuditItem[] = [
  {
    sourceColor: "#F5F5F5",
    targetToken: "--uc-app-bg",
    targetHex: "#F5F5F5",
    status: "mapped",
    usage: "Main app background.",
  },
  {
    sourceColor: "#FFFFFF",
    targetToken: "--uc-surface",
    targetHex: "#FFFFFF",
    status: "mapped",
    usage: "Cards, sheets, nav bars, and page surfaces.",
  },
  {
    sourceColor: "#262626",
    targetToken: "--uc-text",
    targetHex: "#262626",
    status: "mapped",
    usage: "Primary text and icons.",
  },
  {
    sourceColor: "#666666",
    targetToken: "--uc-text-muted",
    targetHex: "#666666",
    status: "mapped",
    usage: "Secondary labels and inactive navigation.",
  },
  {
    sourceColor: "#D8D8D8",
    targetToken: "--uc-border",
    targetHex: "#D8D8D8",
    status: "mapped",
    usage: "Dividers and borders.",
  },
  {
    sourceColor: "#007A91",
    targetToken: "--uc-action",
    targetHex: "#007A91",
    status: "mapped",
    usage: "Primary action, active navigation, teal banners.",
  },
  {
    sourceColor: "#E2001A",
    targetToken: "--uc-brand",
    targetHex: "#E2001A",
    status: "mapped",
    usage: "UniCredit brand and selected shell controls.",
  },
  {
    sourceColor: "#245466",
    targetToken: "--uc-product-blue-deep",
    targetHex: "#244858",
    status: "mapped",
    usage: "Legacy product-card blue mapped to DS Product Blue Deep.",
  },
  {
    sourceColor: "#A70F14",
    targetToken: "--uc-red-card",
    targetHex: "#B91823",
    status: "mapped",
    usage: "Legacy card tile red mapped to DS Red Card.",
  },
  {
    sourceColor: "#A86683",
    targetToken: "--uc-product-mauve",
    targetHex: "#A26077",
    status: "mapped",
    usage: "Legacy mortgages tile mauve mapped to DS Product Mauve.",
  },
  {
    sourceColor: "#467392",
    targetToken: "--uc-product-blue",
    targetHex: "#3F6A8B",
    status: "mapped",
    usage: "Legacy insurance tile blue mapped to DS Product Blue.",
  },
  {
    sourceColor: "#667A7B",
    targetToken: "--uc-product-slate",
    targetHex: "#5E6F73",
    status: "mapped",
    usage: "Legacy investments tile slate mapped to DS Product Slate.",
  },
  {
    sourceColor: "#77816A",
    targetToken: "--uc-neutral-750",
    targetHex: "#535453",
    status: "mapped",
    usage: "Legacy additional-services tile mapped to DS neutral utility.",
  },
  {
    sourceColor: "#EB001B / #FF5F00 / #F79E1B",
    targetToken: "asset exception",
    targetHex: "#E2001A",
    status: "asset-exception",
    usage: "Card-network decorative mark colors inside mock card artwork.",
    note: "Kept only where the color is part of an embedded brand-like illustration.",
  },
];

export const COLOR_BY_HEX = DESIGN_SYSTEM_COLORS.reduce<Record<string, DesignSystemColor[]>>((acc, color) => {
  const key = color.lightHex.toUpperCase();
  acc[key] = [...(acc[key] ?? []), color];
  return acc;
}, {});

export function normalizeHexColor(value: string) {
  const trimmed = value.trim().toUpperCase();
  if (/^#[0-9A-F]{6}$/.test(trimmed)) return trimmed;
  if (/^#[0-9A-F]{3}$/.test(trimmed)) {
    return `#${trimmed[1]}${trimmed[1]}${trimmed[2]}${trimmed[2]}${trimmed[3]}${trimmed[3]}`;
  }
  return trimmed;
}

export function findDesignSystemColorsByHex(value: string) {
  return COLOR_BY_HEX[normalizeHexColor(value)] ?? [];
}
