export type ColorPaletteId =
  | "neutral"
  | "action-teal"
  | "brand-red"
  | "product"
  | "semantic-green"
  | "warning-orange"
  | "peach"
  | "pfm"
  | "utility";

export type AppColorAuditStatus = "mapped" | "asset-exception" | "pending-review";

export interface DesignSystemPalette {
  id: ColorPaletteId;
  label: string;
  description: string;
}

export interface DesignSystemColor {
  id: string;
  name: string;
  paletteId: ColorPaletteId;
  lightHex: string;
  darkHex: string;
  sourceTokens: string[];
  usage: string;
  cssVariable: string;
  darkNote?: string;
}

export interface AppColorAuditItem {
  sourceColor: string;
  targetToken: string;
  targetHex: string;
  status: AppColorAuditStatus;
  usage: string;
  note?: string;
}

export const COLOR_SOURCE_AUDIT = {
  sourcePath: "screenshots/Colors.svg",
  extractedColorGroups: 66,
  solidColorGroups: 59,
  uniqueSolidColors: 48,
  normalizedColorsInRegistry: 60,
  gradientGroups: 1,
};

export const COLOR_PALETTES = [
  {
    id: "neutral",
    label: "Neutral / Primary",
    description: "Core backgrounds, surfaces, text, dividers, and icons.",
  },
  {
    id: "action-teal",
    label: "Action Teal",
    description: "Primary actions, selected states, active navigation, and informational surfaces.",
  },
  {
    id: "brand-red",
    label: "UniCredit Red",
    description: "Brand marks, destructive emphasis, and high-priority visual accents.",
  },
  {
    id: "product",
    label: "Product Tiles",
    description: "Product card surfaces and editorial offer backgrounds.",
  },
  {
    id: "semantic-green",
    label: "Semantic Green",
    description: "Success, positive, environmental, and specialty green accents.",
  },
  {
    id: "warning-orange",
    label: "Warning / Orange",
    description: "Warning, card-network adjacent, gold, and orange attention colors.",
  },
  {
    id: "peach",
    label: "Peach",
    description: "Soft supporting surfaces used in light illustrations and warm accents.",
  },
  {
    id: "pfm",
    label: "PFM Categories",
    description:
      "Semantic Personal Finance Management category colors used in analytics and account transactions; dark variants preserve light hue/chroma with a perceptual lightness lift for dark surfaces.",
  },
  {
    id: "utility",
    label: "Utility",
    description: "Special status and audit-only colors from the source SVG.",
  },
] as const satisfies readonly [DesignSystemPalette, ...DesignSystemPalette[]];

export const DESIGN_SYSTEM_COLORS: DesignSystemColor[] = [
  {
    id: "neutral-white",
    name: "White",
    paletteId: "neutral",
    lightHex: "#FFFFFF",
    darkHex: "#262626",
    sourceTokens: ["Primary / 100", "Primary / 600 Copy 2-5"],
    usage: "Light surfaces, cards, nav bars, and inverse text.",
    cssVariable: "--uc-neutral-white",
    darkNote: "Dark surfaces move to Primary 900 to keep contrast calm.",
  },
  {
    id: "neutral-100",
    name: "Neutral 100",
    paletteId: "neutral",
    lightHex: "#F5F5F5",
    darkHex: "#121212",
    sourceTokens: ["Primary / 200"],
    usage: "App background and subtle section background.",
    cssVariable: "--uc-neutral-100",
  },
  {
    id: "neutral-200",
    name: "Neutral 200",
    paletteId: "neutral",
    lightHex: "#E5E5E5",
    darkHex: "#333333",
    sourceTokens: ["Primary / 300"],
    usage: "Secondary separators and muted cards.",
    cssVariable: "--uc-neutral-200",
  },
  {
    id: "neutral-300",
    name: "Neutral 300",
    paletteId: "neutral",
    lightHex: "#D8D8D8",
    darkHex: "#555555",
    sourceTokens: ["Primary / 902"],
    usage: "Primary borders and divider lines.",
    cssVariable: "--uc-neutral-300",
  },
  {
    id: "neutral-400",
    name: "Neutral 400",
    paletteId: "neutral",
    lightHex: "#CCCCCC",
    darkHex: "#666666",
    sourceTokens: ["Primary / 600"],
    usage: "Disabled borders and low-emphasis controls.",
    cssVariable: "--uc-neutral-400",
  },
  {
    id: "neutral-500",
    name: "Neutral 500",
    paletteId: "neutral",
    lightHex: "#B9B9B9",
    darkHex: "#7A7A7A",
    sourceTokens: ["Primary / Main 22"],
    usage: "Secondary UI chrome and inactive indicators.",
    cssVariable: "--uc-neutral-500",
  },
  {
    id: "neutral-600",
    name: "Neutral 600",
    paletteId: "neutral",
    lightHex: "#999999",
    darkHex: "#909090",
    sourceTokens: ["Primary / 600 Copy"],
    usage: "Muted labels and secondary text.",
    cssVariable: "--uc-neutral-600",
  },
  {
    id: "neutral-650",
    name: "Neutral 650",
    paletteId: "neutral",
    lightHex: "#909090",
    darkHex: "#CCCCCC",
    sourceTokens: ["Primary / Main 26"],
    usage: "Status and chart helper labels.",
    cssVariable: "--uc-neutral-650",
  },
  {
    id: "neutral-700",
    name: "Neutral 700",
    paletteId: "neutral",
    lightHex: "#666666",
    darkHex: "#CCCCCC",
    sourceTokens: ["Primary / 901"],
    usage: "Secondary labels and inactive navigation text.",
    cssVariable: "--uc-neutral-700",
  },
  {
    id: "neutral-750",
    name: "Neutral 750",
    paletteId: "neutral",
    lightHex: "#535453",
    darkHex: "#D6D1D8",
    sourceTokens: ["Primary / Main Copy 3"],
    usage: "Deep muted product surfaces.",
    cssVariable: "--uc-neutral-750",
  },
  {
    id: "neutral-800",
    name: "Neutral 800",
    paletteId: "neutral",
    lightHex: "#454545",
    darkHex: "#D0D0D0",
    sourceTokens: ["Primary / Main 20"],
    usage: "Dense dark UI surfaces.",
    cssVariable: "--uc-neutral-800",
  },
  {
    id: "neutral-900",
    name: "Primary K1",
    paletteId: "neutral",
    lightHex: "#262626",
    darkHex: "#FFFFFF",
    sourceTokens: ["Primary / 900", "Primary / Main 21"],
    usage: "Primary text, icons, and strong dividers.",
    cssVariable: "--uc-primary-k1",
  },
  {
    id: "neutral-black",
    name: "Black",
    paletteId: "neutral",
    lightHex: "#262626",
    darkHex: "#FFFFFF",
    sourceTokens: ["Primary / Main"],
    usage: "Device chrome and strong dark surfaces, normalized away from pure black.",
    cssVariable: "--uc-primary-main",
  },
  {
    id: "teal-900",
    name: "Teal Deep",
    paletteId: "action-teal",
    lightHex: "#006375",
    darkHex: "#CCCCCC",
    sourceTokens: ["Primary / Main 2", "Primary / 900 Copy 3", "Primary / Main 18"],
    usage: "Pressed action, deep selected state, and offer backgrounds.",
    cssVariable: "--uc-teal-900",
  },
  {
    id: "teal-700",
    name: "Teal Main",
    paletteId: "action-teal",
    lightHex: "#007A91",
    darkHex: "#FFFFFF",
    sourceTokens: ["Primary / Main 3", "Primary / 900 2", "Primary / 900 16", "Primary / Main 27"],
    usage: "Primary action, active navigation, banners, and chart inflow.",
    cssVariable: "--uc-teal-main",
  },
  {
    id: "teal-650",
    name: "Teal Blue",
    paletteId: "action-teal",
    lightHex: "#05829A",
    darkHex: "#4FC6DD",
    sourceTokens: ["Primary / Main 19"],
    usage: "Alternate selected teal for charts and status surfaces.",
    cssVariable: "--uc-teal-blue",
  },
  {
    id: "teal-600",
    name: "Teal Bright",
    paletteId: "action-teal",
    lightHex: "#00A197",
    darkHex: "#3ED6C8",
    sourceTokens: ["Primary / Main 4"],
    usage: "Bright action accent and dark-mode active state.",
    cssVariable: "--uc-teal-bright",
  },
  {
    id: "teal-300",
    name: "Teal Soft",
    paletteId: "action-teal",
    lightHex: "#99D9D5",
    darkHex: "#2E7C88",
    sourceTokens: ["Primary / 900 3"],
    usage: "Soft active surface and light selected background.",
    cssVariable: "--uc-teal-soft",
  },
  {
    id: "teal-100",
    name: "Teal Pale",
    paletteId: "action-teal",
    lightHex: "#CCECEA",
    darkHex: "#315B66",
    sourceTokens: ["Primary / 800"],
    usage: "Low-emphasis success/info background.",
    cssVariable: "--uc-teal-pale",
  },
  {
    id: "red-main",
    name: "UniCredit Red",
    paletteId: "brand-red",
    lightHex: "#E2001A",
    darkHex: "#E2001A",
    sourceTokens: ["Primary / Main 5", "Primary / 900 14"],
    usage: "Brand mark and primary brand accent.",
    cssVariable: "--uc-red-main",
  },
  {
    id: "red-bright",
    name: "Red Bright",
    paletteId: "brand-red",
    lightHex: "#E01E25",
    darkHex: "#FF5A68",
    sourceTokens: ["Primary / 600 Copy 6"],
    usage: "Dark-mode brand accent and alert emphasis.",
    cssVariable: "--uc-red-bright",
  },
  {
    id: "red-card",
    name: "Red Card",
    paletteId: "brand-red",
    lightHex: "#B91823",
    darkHex: "#F04A58",
    sourceTokens: ["Primary / 600 Copy 2", "Primary / 900 13"],
    usage: "Card product tile and strong warning.",
    cssVariable: "--uc-red-card",
  },
  {
    id: "red-deep",
    name: "Red Deep",
    paletteId: "brand-red",
    lightHex: "#9A000B",
    darkHex: "#D94A5A",
    sourceTokens: ["Primary / 900 Copy", "Primary / Main 15"],
    usage: "Deep red surfaces and dark red accents.",
    cssVariable: "--uc-red-deep",
  },
  {
    id: "red-brown",
    name: "Red Brown",
    paletteId: "brand-red",
    lightHex: "#961414",
    darkHex: "#D65C68",
    sourceTokens: ["Primary / 900 4"],
    usage: "Legacy deep warning and decorative emphasis.",
    cssVariable: "--uc-red-brown",
  },
  {
    id: "product-blue-deep",
    name: "Product Blue Deep",
    paletteId: "product",
    lightHex: "#244858",
    darkHex: "#91D1DD",
    sourceTokens: ["Primary / Main 6"],
    usage: "Account product tile.",
    cssVariable: "--uc-product-blue-deep",
  },
  {
    id: "product-slate",
    name: "Product Slate",
    paletteId: "product",
    lightHex: "#5E6F73",
    darkHex: "#AAB8BC",
    sourceTokens: ["Primary / 900 5"],
    usage: "Investments and neutral product tile.",
    cssVariable: "--uc-product-slate",
  },
  {
    id: "product-blue",
    name: "Product Blue",
    paletteId: "product",
    lightHex: "#3F6A8B",
    darkHex: "#78B6E8",
    sourceTokens: ["Primary / Main 7"],
    usage: "Insurance product tile.",
    cssVariable: "--uc-product-blue",
  },
  {
    id: "product-mauve",
    name: "Product Mauve",
    paletteId: "product",
    lightHex: "#A26077",
    darkHex: "#D38AA3",
    sourceTokens: ["Primary / Main 8"],
    usage: "Mortgage and loans product tile.",
    cssVariable: "--uc-product-mauve",
  },
  {
    id: "product-pink",
    name: "Product Pink",
    paletteId: "product",
    lightHex: "#DD1860",
    darkHex: "#FF5F9A",
    sourceTokens: ["Primary / 900 6"],
    usage: "Pink accent in product/editorial visuals.",
    cssVariable: "--uc-product-pink",
  },
  {
    id: "product-brown",
    name: "Product Brown",
    paletteId: "product",
    lightHex: "#5E3D32",
    darkHex: "#9A6246",
    sourceTokens: ["Primary / Main 9"],
    usage: "Warm product surface and illustration accent.",
    cssVariable: "--uc-product-brown",
  },
  {
    id: "product-hedging",
    name: "Product Hedging",
    paletteId: "product",
    lightHex: "#717863",
    darkHex: "#717863",
    sourceTokens: ["Prestiti"],
    usage: "Market Hedging product menu tile.",
    cssVariable: "--uc-product-hedging",
  },
  {
    id: "green-deep",
    name: "Green Deep",
    paletteId: "semantic-green",
    lightHex: "#004C3D",
    darkHex: "#004C3D",
    sourceTokens: ["Primary / Main Copy 2", "Primary / Main 16"],
    usage: "Deep green editorial and success surface.",
    cssVariable: "--uc-green-deep",
  },
  {
    id: "green-main",
    name: "Green Main",
    paletteId: "semantic-green",
    lightHex: "#007A6B",
    darkHex: "#26C3A8",
    sourceTokens: ["Primary / 900 15"],
    usage: "Positive/action green accent.",
    cssVariable: "--uc-green-main",
  },
  {
    id: "green-bright",
    name: "Green Bright",
    paletteId: "semantic-green",
    lightHex: "#008574",
    darkHex: "#008574",
    sourceTokens: ["Primary / Main 17"],
    usage: "Bright green selected/semantic accent.",
    cssVariable: "--uc-green-bright",
  },
  {
    id: "green-success",
    name: "Green Success",
    paletteId: "semantic-green",
    lightHex: "#2FA358",
    darkHex: "#59D37F",
    sourceTokens: ["Primary / Main 10"],
    usage: "Success and positive status.",
    cssVariable: "--uc-green-success",
  },
  {
    id: "green-status",
    name: "Green Status",
    paletteId: "semantic-green",
    lightHex: "#359F42",
    darkHex: "#359F42",
    sourceTokens: ["Primary / Main Copy 4"],
    usage: "Status green in audit and message states.",
    cssVariable: "--uc-green-status",
  },
  {
    id: "green-olive",
    name: "Green Olive",
    paletteId: "semantic-green",
    lightHex: "#3D7D43",
    darkHex: "#26EDA9",
    sourceTokens: ["Primary / Main 23"],
    usage: "Olive product/status accent.",
    cssVariable: "--uc-green-olive",
  },
  {
    id: "orange-main",
    name: "Orange Main",
    paletteId: "warning-orange",
    lightHex: "#E67300",
    darkHex: "#FF9D3B",
    sourceTokens: ["Primary / Main Copy"],
    usage: "Warning and orange emphasis.",
    cssVariable: "--uc-orange-main",
  },
  {
    id: "orange-card",
    name: "Orange Card",
    paletteId: "warning-orange",
    lightHex: "#E67301",
    darkHex: "#FF9D3C",
    sourceTokens: ["Primary / Main 13"],
    usage: "Card/network adjacent orange.",
    cssVariable: "--uc-orange-card",
  },
  {
    id: "orange-bright",
    name: "Orange Bright",
    paletteId: "warning-orange",
    lightHex: "#F0871D",
    darkHex: "#FFB15C",
    sourceTokens: ["Primary / 900 10"],
    usage: "Bright warning highlight.",
    cssVariable: "--uc-orange-bright",
  },
  {
    id: "orange-status",
    name: "Orange Status",
    paletteId: "warning-orange",
    lightHex: "#F26B08",
    darkHex: "#FDA98B",
    sourceTokens: ["Primary / Main 24"],
    usage: "Status warning accent.",
    cssVariable: "--uc-orange-status",
  },
  {
    id: "yellow-gold",
    name: "Gold",
    paletteId: "warning-orange",
    lightHex: "#FBB800",
    darkHex: "#FFD24D",
    sourceTokens: ["Primary / 900 7"],
    usage: "Gold and attention highlights.",
    cssVariable: "--uc-yellow-gold",
  },
  {
    id: "yellow-muted",
    name: "Muted Gold",
    paletteId: "warning-orange",
    lightHex: "#DFA805",
    darkHex: "#F2C84B",
    sourceTokens: ["Primary / 900 8"],
    usage: "Muted gold highlight.",
    cssVariable: "--uc-yellow-muted",
  },
  {
    id: "yellow-brown",
    name: "Brown Gold",
    paletteId: "warning-orange",
    lightHex: "#D1960A",
    darkHex: "#E8BF52",
    sourceTokens: ["Primary / Main 11"],
    usage: "Deep gold/brown surface.",
    cssVariable: "--uc-yellow-brown",
  },
  {
    id: "yellow-main",
    name: "Yellow Main",
    paletteId: "warning-orange",
    lightHex: "#EDBA00",
    darkHex: "#FFD24D",
    sourceTokens: ["Primary / 900 9"],
    usage: "Yellow highlight.",
    cssVariable: "--uc-yellow-main",
  },
  {
    id: "orange-deep",
    name: "Orange Deep",
    paletteId: "warning-orange",
    lightHex: "#E3690E",
    darkHex: "#FF9A47",
    sourceTokens: ["Primary / Main 12"],
    usage: "Deep orange accent.",
    cssVariable: "--uc-orange-deep",
  },
  {
    id: "peach-100",
    name: "Peach 100",
    paletteId: "peach",
    lightHex: "#FFDAC0",
    darkHex: "#8F5E42",
    sourceTokens: ["Primary / 900 12"],
    usage: "Warm pale surface.",
    cssVariable: "--uc-peach-100",
  },
  {
    id: "peach-200",
    name: "Peach 200",
    paletteId: "peach",
    lightHex: "#FFCBB1",
    darkHex: "#9A6246",
    sourceTokens: ["Primary / 900 11"],
    usage: "Warm supporting surface.",
    cssVariable: "--uc-peach-200",
  },
  {
    id: "peach-300",
    name: "Peach 300",
    paletteId: "peach",
    lightHex: "#FFBDA5",
    darkHex: "#A86B4F",
    sourceTokens: ["Primary / Main 14"],
    usage: "Warm supporting accent.",
    cssVariable: "--uc-peach-300",
  },
  {
    id: "pfm-taxes-penalties",
    name: "PFM Taxes and Penalties",
    paletteId: "pfm",
    lightHex: "#7757A4",
    darkHex: "#9574BF",
    sourceTokens: ["PFM / Taxes and penalties"],
    usage: "Personal finance category color for taxes and penalties transactions.",
    cssVariable: "--uc-pfm-taxes-penalties",
  },
  {
    id: "pfm-groceries",
    name: "PFM Groceries",
    paletteId: "pfm",
    lightHex: "#A33694",
    darkHex: "#C355B1",
    sourceTokens: ["PFM / Groceries"],
    usage: "Personal finance category color for groceries.",
    cssVariable: "--uc-pfm-groceries",
  },
  {
    id: "pfm-lifestyle",
    name: "PFM Lifestyle",
    paletteId: "pfm",
    lightHex: "#388BCA",
    darkHex: "#55A2DC",
    sourceTokens: ["PFM / Lifestyle"],
    usage: "Personal finance category color for lifestyle and personal care.",
    cssVariable: "--uc-pfm-lifestyle",
  },
  {
    id: "pfm-investments",
    name: "PFM Investments",
    paletteId: "pfm",
    lightHex: "#363338",
    darkHex: "#88858A",
    sourceTokens: ["PFM / Investments"],
    usage: "Personal finance category color for investments.",
    cssVariable: "--uc-pfm-investments",
  },
  {
    id: "pfm-internal",
    name: "PFM Internal",
    paletteId: "pfm",
    lightHex: "#0D5870",
    darkHex: "#5190A6",
    sourceTokens: ["PFM / Internal"],
    usage: "Personal finance category color for internal own-account movements.",
    cssVariable: "--uc-pfm-internal",
  },
  {
    id: "pfm-income",
    name: "PFM Income",
    paletteId: "pfm",
    lightHex: "#05829A",
    darkHex: "#3499AD",
    sourceTokens: ["PFM / Income"],
    usage: "Personal finance category color for income; intentionally aligned with the shared teal-blue action family.",
    cssVariable: "--uc-pfm-income",
  },
  {
    id: "pfm-utilities",
    name: "PFM Utilities",
    paletteId: "pfm",
    lightHex: "#006375",
    darkHex: "#4693A2",
    sourceTokens: ["PFM / Utilities"],
    usage: "Personal finance category color for utilities; intentionally aligned with Teal Deep.",
    cssVariable: "--uc-pfm-utilities",
  },
  {
    id: "pfm-exclude-budget",
    name: "PFM Exclude from Budget",
    paletteId: "pfm",
    lightHex: "#B91823",
    darkHex: "#E04950",
    sourceTokens: ["PFM / Exclude from budget"],
    usage: "Personal finance category color for excluded spend.",
    cssVariable: "--uc-pfm-exclude-budget",
  },
  {
    id: "pfm-shopping",
    name: "PFM Shopping",
    paletteId: "pfm",
    lightHex: "#9A000B",
    darkHex: "#DA5251",
    sourceTokens: ["PFM / Shopping"],
    usage: "Personal finance category color for shopping.",
    cssVariable: "--uc-pfm-shopping",
  },
  {
    id: "pfm-insurance",
    name: "PFM Insurance",
    paletteId: "pfm",
    lightHex: "#004C3D",
    darkHex: "#569482",
    sourceTokens: ["PFM / Insurance"],
    usage: "Personal finance category color for insurance.",
    cssVariable: "--uc-pfm-insurance",
  },
  {
    id: "pfm-home",
    name: "PFM Home",
    paletteId: "pfm",
    lightHex: "#008574",
    darkHex: "#309B88",
    sourceTokens: ["PFM / Home"],
    usage: "Personal finance category color for home.",
    cssVariable: "--uc-pfm-home",
  },
  {
    id: "pfm-education",
    name: "PFM Education",
    paletteId: "pfm",
    lightHex: "#5E3D32",
    darkHex: "#A17C73",
    sourceTokens: ["PFM / Education"],
    usage: "Personal finance category color for education.",
    cssVariable: "--uc-pfm-education",
  },
  {
    id: "pfm-transportation",
    name: "PFM Transportation",
    paletteId: "pfm",
    lightHex: "#E67300",
    darkHex: "#FD8C46",
    sourceTokens: ["PFM / Transportation"],
    usage: "Personal finance category color for transportation.",
    cssVariable: "--uc-pfm-transportation",
  },
  {
    id: "pfm-leisure-time",
    name: "PFM Leisure Time",
    paletteId: "pfm",
    lightHex: "#E01E25",
    darkHex: "#F8434C",
    sourceTokens: ["PFM / Leisure time"],
    usage: "Personal finance category color for leisure time.",
    cssVariable: "--uc-pfm-leisure-time",
  },
  {
    id: "pfm-healthcare",
    name: "PFM Healthcare",
    paletteId: "pfm",
    lightHex: "#DD1860",
    darkHex: "#F63E7B",
    sourceTokens: ["PFM / Healthcare"],
    usage: "Personal finance category color for healthcare.",
    cssVariable: "--uc-pfm-healthcare",
  },
  {
    id: "pfm-children",
    name: "PFM Children",
    paletteId: "pfm",
    lightHex: "#006375",
    darkHex: "#4693A2",
    sourceTokens: ["PFM / Children"],
    usage: "Personal finance category color for children-related spend.",
    cssVariable: "--uc-pfm-children",
  },
  {
    id: "pfm-wallet",
    name: "PFM Wallet",
    paletteId: "pfm",
    lightHex: "#7E5B01",
    darkHex: "#A28040",
    sourceTokens: ["PFM / Wallet"],
    usage: "Personal finance category color for wallet and cash-like activity.",
    cssVariable: "--uc-pfm-wallet",
  },
  {
    id: "pfm-transfers",
    name: "PFM Transfers",
    paletteId: "pfm",
    lightHex: "#359F42",
    darkHex: "#4CB65D",
    sourceTokens: ["PFM / Transfers"],
    usage: "Personal finance category color for transfers.",
    cssVariable: "--uc-pfm-transfers",
  },
  {
    id: "pfm-finance",
    name: "PFM Finance",
    paletteId: "pfm",
    lightHex: "#535453",
    darkHex: "#858685",
    sourceTokens: ["PFM / Finance"],
    usage: "Personal finance category color for finance-related activity.",
    cssVariable: "--uc-pfm-finance",
  },
  {
    id: "pfm-uncategorized",
    name: "PFM Uncategorized",
    paletteId: "pfm",
    lightHex: "#007A6B",
    darkHex: "#389987",
    sourceTokens: ["PFM / Uncategorized"],
    usage: "Fallback personal finance category color for uncategorized items.",
    cssVariable: "--uc-pfm-uncategorized",
  },
  {
    id: "pfm-atm",
    name: "PFM ATM",
    paletteId: "pfm",
    lightHex: "#388BCA",
    darkHex: "#55A2DC",
    sourceTokens: ["PFM / ATM"],
    usage: "Personal finance category color for ATM activity.",
    cssVariable: "--uc-pfm-atm",
  },
  {
    id: "pfm-fx",
    name: "PFM FX",
    paletteId: "pfm",
    lightHex: "#244858",
    darkHex: "#688C9C",
    sourceTokens: ["PFM / FX"],
    usage: "Personal finance category color for foreign exchange activity.",
    cssVariable: "--uc-pfm-fx",
  },
  {
    id: "red-status",
    name: "Status Red",
    paletteId: "utility",
    lightHex: "#CF3524",
    darkHex: "#FF7A8E",
    sourceTokens: ["Primary / Main 25"],
    usage: "Status red in audit and warning surfaces.",
    cssVariable: "--uc-status-red",
  },
  {
    id: "gold-brown",
    name: "Gold Brown",
    paletteId: "utility",
    lightHex: "#7E5B01",
    darkHex: "#D4B04D",
    sourceTokens: ["Primary / Main Copy 4 2"],
    usage: "Utility brown/gold accent from source SVG.",
    cssVariable: "--uc-gold-brown",
  },
];

export const APP_COLOR_AUDIT: AppColorAuditItem[] = [
  {
    sourceColor: "#F5F5F5",
    targetToken: "--uc-app-bg",
    targetHex: "#F5F5F5",
    status: "mapped",
    usage: "Main app background.",
  },
  {
    sourceColor: "#FFFFFF",
    targetToken: "--uc-surface",
    targetHex: "#FFFFFF",
    status: "mapped",
    usage: "Cards, sheets, nav bars, and page surfaces.",
  },
  {
    sourceColor: "#262626",
    targetToken: "--uc-text",
    targetHex: "#262626",
    status: "mapped",
    usage: "Primary text and icons.",
  },
  {
    sourceColor: "#666666",
    targetToken: "--uc-text-muted",
    targetHex: "#666666",
    status: "mapped",
    usage: "Secondary labels and inactive navigation.",
  },
  {
    sourceColor: "#D8D8D8",
    targetToken: "--uc-border",
    targetHex: "#D8D8D8",
    status: "mapped",
    usage: "Dividers and borders.",
  },
  {
    sourceColor: "#007A91",
    targetToken: "--uc-action",
    targetHex: "#007A91",
    status: "mapped",
    usage: "Primary action, active navigation, teal banners.",
  },
  {
    sourceColor: "#E2001A",
    targetToken: "--uc-brand",
    targetHex: "#E2001A",
    status: "mapped",
    usage: "UniCredit brand and selected shell controls.",
  },
  {
    sourceColor: "#245466",
    targetToken: "--uc-product-blue-deep",
    targetHex: "#244858",
    status: "mapped",
    usage: "Legacy product-card blue mapped to DS Product Blue Deep.",
  },
  {
    sourceColor: "#A70F14",
    targetToken: "--uc-red-card",
    targetHex: "#B91823",
    status: "mapped",
    usage: "Legacy card tile red mapped to DS Red Card.",
  },
  {
    sourceColor: "#A86683",
    targetToken: "--uc-product-mauve",
    targetHex: "#A26077",
    status: "mapped",
    usage: "Legacy mortgages tile mauve mapped to DS Product Mauve.",
  },
  {
    sourceColor: "#467392",
    targetToken: "--uc-product-blue",
    targetHex: "#3F6A8B",
    status: "mapped",
    usage: "Legacy insurance tile blue mapped to DS Product Blue.",
  },
  {
    sourceColor: "#667A7B",
    targetToken: "--uc-product-slate",
    targetHex: "#5E6F73",
    status: "mapped",
    usage: "Legacy investments tile slate mapped to DS Product Slate.",
  },
  {
    sourceColor: "#77816A",
    targetToken: "--uc-neutral-750",
    targetHex: "#535453",
    status: "mapped",
    usage: "Legacy additional-services tile mapped to DS neutral utility.",
  },
  {
    sourceColor: "#7757A4 / #A33694 / #388BCA / #363338 / #0D5870",
    targetToken: "PFM category tokens",
    targetHex: "see registry",
    status: "mapped",
    usage: "PFM-only colors now cataloged explicitly in the DS registry instead of living only in theme.css.",
    note: "See the `pfm` palette entries for Taxes and Penalties, Groceries, Lifestyle, Investments, and Internal.",
  },
  {
    sourceColor: "#EB001B / #FF5F00 / #F79E1B",
    targetToken: "asset exception",
    targetHex: "#E2001A",
    status: "asset-exception",
    usage: "Card-network decorative mark colors inside mock card artwork.",
    note: "Kept only where the color is part of an embedded brand-like illustration.",
  },
];

export const COLOR_BY_HEX = DESIGN_SYSTEM_COLORS.reduce<Record<string, DesignSystemColor[]>>((acc, color) => {
  const key = color.lightHex.toUpperCase();
  acc[key] = [...(acc[key] ?? []), color];
  return acc;
}, {});

export function normalizeHexColor(value: string) {
  const trimmed = value.trim().toUpperCase();
  if (/^#[0-9A-F]{6}$/.test(trimmed)) return trimmed;
  if (/^#[0-9A-F]{3}$/.test(trimmed)) {
    return `#${trimmed[1]}${trimmed[1]}${trimmed[2]}${trimmed[2]}${trimmed[3]}${trimmed[3]}`;
  }
  return trimmed;
}

export function findDesignSystemColorsByHex(value: string) {
  return COLOR_BY_HEX[normalizeHexColor(value)] ?? [];
}
