/**
 * Component Registry
 * Machine-readable component catalog for AI reuse and coverage checks.
 */

import type {
  CapabilityStatus,
  ComponentId,
  DesignSystemId,
  ProductId,
  ScreenId,
} from "@/app/state/demoTypes";

export interface ComponentMeta {
  id: ComponentId;
  label: string;
  products: readonly ProductId[];
  designSystems: readonly DesignSystemId[];
  status: CapabilityStatus;
  componentPath: string;
  usedByScreens: readonly ScreenId[];
  notes?: string;
}

export const COMPONENT_REGISTRY: Record<ComponentId, ComponentMeta> = {
  "shell.mobile-frame": {
    id: "shell.mobile-frame",
    label: "Mobile frame",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/MobileFrame.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.home.overview",
      "pi.analytics.overview",
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payments.overview",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.products.overview",
      "pi.prime.overview",
      "pi.more.overview",
      "pi.contacts.overview",
      "kids.ro.prototype",
    ],
  },
  "shell.page-header": {
    id: "shell.page-header",
    label: "Page header",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/PageHeader.tsx",
    usedByScreens: [
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.documents.overview",
      "pi.settings.overview",
      "pi.contacts.overview",
    ],
    notes: "Shared top-page header family used by runtime detail/list screens and reconstructed templates.",
  },
  "shell.bottom-navigation": {
    id: "shell.bottom-navigation",
    label: "Bottom navigation",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/BottomNavigation.tsx",
    usedByScreens: ["pi.home.overview", "pi.analytics.overview", "pi.payments.overview", "pi.products.overview", "pi.more.overview"],
    notes: "Fixed 375x54 bottom bar contract with 24px side padding, 32px icon slots, 24x2 active bar touching the icon slot, and 14px labels with 15px line-height and no icon/label gap.",
  },
  "shell.bottom-sheet": {
    id: "shell.bottom-sheet",
    label: "Bottom sheet shell",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/BottomSheet.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable overlay and rounded bottom panel shell for modal quick menus, with 16px uniform sheet padding.",
  },
  "icons.app-icon": {
    id: "icons.app-icon",
    label: "App icon registry",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/icons/AppIcon.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.home.overview",
      "pi.analytics.overview",
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payments.overview",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.products.overview",
      "pi.prime.overview",
      "pi.more.overview",
      "pi.documents.overview",
      "pi.settings.overview",
      "pi.contacts.overview",
      "kids.ro.prototype",
      "platform.design-system",
    ],
    notes: "Central source for reusable UI icons; templates and runtime screens should reference icons through this registry rather than direct lucide or raw SVG usage.",
  },
  "brand.unicredit-logo": {
    id: "brand.unicredit-logo",
    label: "UniCredit logo",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/UniCreditLogo.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active", "platform.design-system"],
  },
  "ui.primary-button": {
    id: "ui.primary-button",
    label: "Primary button",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/PrimaryButton.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.prime.overview",
      "kids.ro.prototype",
      "platform.design-system",
    ],
  },
  "ui.text-field": {
    id: "ui.text-field",
    label: "Text field",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/TextField.tsx",
    usedByScreens: ["pi.co-apping.session", "pi.payment.domestic-create", "pi.payment.sign", "kids.ro.prototype", "platform.design-system"],
  },
  "ui.amount-field": {
    id: "ui.amount-field",
    label: "Amount field",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/AmountField.tsx",
    usedByScreens: ["pi.payment.domestic-create", "kids.ro.prototype", "platform.design-system"],
    notes: "Amount input variant with the same visual states as Text field plus a 24px-spaced currency selector column, 14px currency label, 18px currency value, and 32x32 trailing chevron with zero currency-to-chevron gap.",
  },
  "ui.radio-button": {
    id: "ui.radio-button",
    label: "Radio button",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/common/RadioButton.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active", "platform.design-system"],
  },
  "ui.section-heading-divider": {
    id: "ui.section-heading-divider",
    label: "Section heading divider",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/SectionHeadingDivider.tsx",
    usedByScreens: ["pi.analytics.overview", "pi.payment.domestic-create", "pi.settings.overview", "pi.contacts.overview", "platform.design-system"],
  },
  "prelogin.inactive": {
    id: "prelogin.inactive",
    label: "Pre-login inactive composition",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/components/PreLoginScreen.tsx",
    usedByScreens: ["pi.prelogin.inactive"],
  },
  "prelogin.active": {
    id: "prelogin.active",
    label: "Pre-login active composition",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/components/PreLoginActiveScreen.tsx",
    usedByScreens: ["pi.prelogin.active"],
  },
  "prelogin.language-selector": {
    id: "prelogin.language-selector",
    label: "Language selector",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/LanguageSelector.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active"],
    notes: "Country-aware local/English language selector used by pre-login templates.",
  },
  "prelogin.other-panel": {
    id: "prelogin.other-panel",
    label: "Other panel menu",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/PanelWithTranslations.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active"],
    notes: "Translated pre-login panel pattern for Smart Banking, exchange rates, ATM/branches, and Co-Apping entry rows.",
  },
  "co-apping.floating-button": {
    id: "co-apping.floating-button",
    label: "Co-Apping floating button",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/FloatingCoAppingButton.tsx",
    usedByScreens: ["pi.home.overview", "pi.more.overview", "pi.contacts.overview"],
  },
  "co-apping.session-entry": {
    id: "co-apping.session-entry",
    label: "Co-Apping session entry",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/components/CoAppingSessionScreen.tsx",
    usedByScreens: ["pi.co-apping.session"],
  },
  "home.amount-visibility-toggle": {
    id: "home.amount-visibility-toggle",
    label: "Amount visibility toggle",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/AmountVisibilityButton.tsx",
    usedByScreens: ["pi.home.overview"],
    notes: "Toggles account/card/product amount masking across navigation while leaving transaction amounts visible.",
  },
  "home.account-summary": {
    id: "home.account-summary",
    label: "Home account summary",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/home/AccountSummary.tsx",
    usedByScreens: ["pi.home.overview"],
  },
  "home.account-balance-card": {
    id: "home.account-balance-card",
    label: "Account balance card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountBalanceCard.tsx",
    usedByScreens: ["pi.account.detail"],
  },
  "home.unplanned-banner": {
    id: "home.unplanned-banner",
    label: "Unplanned banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/home/UnplannedBanner.tsx",
    usedByScreens: ["pi.home.overview"],
  },
  "analytics.spendings": {
    id: "analytics.spendings",
    label: "Analytics spendings overview",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/analytics/AnalyticsScreen.tsx",
    usedByScreens: ["pi.analytics.overview"],
    notes: "Screenshot-inspired My Spendings screen with transaction-derived inflow/outflow bars, cash transaction banner, and PFM-category Money Out / Money In summaries.",
  },
  "pfm.category-icon": {
    id: "pfm.category-icon",
    label: "PFM category icon",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/components/pfm/PfmCategoryIcon.tsx",
    usedByScreens: ["pi.account.detail", "pi.analytics.overview"],
    notes: "Token-driven PFM category icon mapped from screenshots/PFM-icons.svg; Taxes and Penalties, Income, Home, Utilities, Transportation, Children, Healthcare, Shopping, Lifestyle, Education, Leisure time, Investments, Uncategorized, Groceries, Exclude from budget, Insurance, Finance, Wallet, and Transfers render real 20x20 SVG glyphs inside a 32x32 container, while remaining categories still fall back to initials.",
  },
  "messages.mailbox-tabs": {
    id: "messages.mailbox-tabs",
    label: "Messages mailbox tabs",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/messages/MessagesMailboxTabs.tsx",
    usedByScreens: ["pi.messages.overview", "platform.design-system"],
    notes: "Reusable 2-tab mailbox switcher for Messages-family screens and templates, with 48px height, active leading 12px dot, optional numeric badge pill, muted inactive label, and 2px bottom active indicator.",
  },
  "messages.inbox-list": {
    id: "messages.inbox-list",
    label: "Messages inbox and outbox list",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/messages/MessagesScreen.tsx",
    usedByScreens: ["pi.messages.overview"],
    notes: "Runtime screen reconstructed from template 52, using the shared PageHeader, country-addressable extended mock Inbox/Outbox data, reusable MessagesMailboxTabs, AccountSearchBar, date rows, NEW badges, row action dots, and page-level scrolling.",
  },
  "accounts.action-bar": {
    id: "accounts.action-bar",
    label: "Account action bar",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountActionBar.tsx",
    usedByScreens: ["pi.account.detail", "pi.analytics.overview"],
    notes: "Reusable 1-4 item action bar with shared 32px icon slot, 14px/15px label contract, and page-level alignment options.",
  },
  "accounts.details-info": {
    id: "accounts.details-info",
    label: "Account details information screen",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/accounts/AccountDetailsInfoScreen.tsx",
    usedByScreens: ["pi.account.details-info"],
    notes: "Uses AccountDetailsInfoField rows for the account-number-with-icon variant and default title/subtitle fields.",
  },
  "accounts.details-info-field": {
    id: "accounts.details-info-field",
    label: "Account details info field",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountDetailsInfoField.tsx",
    usedByScreens: ["pi.account.details-info"],
    notes: "80px reusable Account Details title/subtitle row with 4px internal title-to-subtitle gap, 16px normal title, 16px bold subtitle, and optional trailing-icon variant.",
  },
  "accounts.transaction-search": {
    id: "accounts.transaction-search",
    label: "Account transaction search",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountSearchBar.tsx",
    usedByScreens: ["pi.account.detail"],
    notes: "Searches the current account transaction list, uses 32x32 search and filter/clear icon slots with icon-driven 32px height, swaps the filter icon for a clear-results action while a query is active, and keeps the search bar pinned at the top of the list.",
  },
  "accounts.transaction-row": {
    id: "accounts.transaction-row",
    label: "Account transaction row",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountTransactionRow.tsx",
    usedByScreens: ["pi.account.detail"],
    notes: "Renders account transactions with a PFM category badge sourced from the shared PFM category map, fixed date/icon spacing, 18px transaction label line-height, 22px amount line-height, and 16px list spacing around month dividers in Account Detail.",
  },
  "transactions.detail": {
    id: "transactions.detail",
    label: "Transaction detail screen",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    usedByScreens: ["pi.transaction.detail"],
    notes: "Shows transaction amount, a transaction-derived PFM category pill with the shared PFM icon glyph, category actions, spending insight, details, and a Redo payment entry into domestic payment.",
  },
  "payments.menu": {
    id: "payments.menu",
    label: "Payments menu",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/PaymentsScreen.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Country-scoped Payments hub. Default countries keep the original four primary cards and OTHER rail, while BA and BA_BL render five primary cards and five OTHER shortcuts with supplied market copy.",
  },
  "payments.hero-card": {
    id: "payments.hero-card",
    label: "Payments hero card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/PaymentHeroCard.tsx",
    usedByScreens: ["pi.payments.overview", "platform.design-system"],
    notes: "Reusable 327x120 Payments primary card. Title is 24px bold, starts 16px from the top, respects supplied line breaks without ellipsis, and the 14px description sits 16px below single-line titles or 8px below explicitly multiline titles. Supports 9 screenshot-backed image variants (`payments1.png` through `payments9.png`) plus an optional imageSrc override.",
  },
  "payments.other-shortcut": {
    id: "payments.other-shortcut",
    label: "Payments Other shortcut",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/PaymentOtherShortcut.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable single shortcut action used in Payments OTHER, with a 32x32 icon slot inside a 58px circular button, fixed 74px rail item width, and a 14px bold label clamped to 2 lines at 15px line-height for scrollable carousel use.",
  },
  "payments.new-payment-sheet": {
    id: "payments.new-payment-sheet",
    label: "New payment bottom sheet",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/PaymentsScreen.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Opens from the New payment card and renders country-scoped payment-type labels from paymentsMenuConfig.",
  },
  "payments.new-payment-action": {
    id: "payments.new-payment-action",
    label: "New payment action row",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/NewPaymentActionListItem.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable 80px New payment bottom-sheet row with supplied action icon, title, subtitle, and chevron.",
  },
  "payments.new-payment-discover-banner": {
    id: "payments.new-payment-discover-banner",
    label: "New payment discover banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/NewPaymentDiscoverBanner.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable teal help banner for New payment with supplied info and close icons, 16px padding, 4px title/subtitle gap, and normal text line-height.",
  },
  "payments.domestic-flow": {
    id: "payments.domestic-flow",
    label: "Domestic payment flow",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    usedByScreens: [
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
    ],
    notes: "Creates domestic payments either blank from Payments/New payment or prefilled from Transaction detail/Redo payment.",
  },
  "templates.reconstructed-code": {
    id: "templates.reconstructed-code",
    label: "Reconstructed code templates",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Renders 50 real JSX template previews: all 30 screenshot-backed templates plus 20 code-only templates derived from active pre-login, panel, Co-Apping, Home/account, Payments, Products, More, Contacts, Messages, Spending, Prime, and dialog patterns. Source PNG/JPG files remain comparison evidence where they exist.",
  },
  "products.menu": {
    id: "products.menu",
    label: "Products menu",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/products/ProductsScreen.tsx",
    usedByScreens: ["pi.products.overview"],
    notes: "Country-scoped configuration controls whether the Banking/ShopSmart tabs are visible, whether offer rails/headings render, and which product cards remain. BA and BA_BL are cards-only with Accounts, Cards, Loans, and Savings.",
  },
  "products.offer-card": {
    id: "products.offer-card",
    label: "Products offer card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/products/ProductOfferCard.tsx",
    usedByScreens: ["pi.products.overview"],
    notes: "Reusable 327x157 offer carousel card with centered vertical chevron background, a text area that fills to 16px before the fixed 100px right image column, 22px bold title clamped to 2 lines, 18px regular subtitle clamped to 3 lines, and selectable family/light-tone pairs covering green, yellow, orange, pink, red, blue, and grey banner variants.",
  },
  "products.product-card": {
    id: "products.product-card",
    label: "Products menu card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/products/ProductMenuCard.tsx",
    usedByScreens: ["pi.products.overview"],
    notes: "Reusable Products menu card with a 164x120 standard variant and a 164x72 compact variant. Product config controls title, background, fallback illustration, and optional imageSrc artwork; the component positions supplied artwork per card family for Account, Cards, Mortgages and Loans, Insurance, Investments and Savings, Market Hedging, Shopsmart, and Partner Offers without changing country runtime baselines unless config passes those cards.",
  },
  "more.card-grid": {
    id: "more.card-grid",
    label: "More service card grid",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/more/MoreScreen.tsx",
    usedByScreens: ["pi.more.overview"],
    notes: "Country-scoped More card matrix. BA and BA_BL include Tutorials plus My applications after Settings and use Contact phone + Messages header actions.",
  },
  "contacts.navigation-card": {
    id: "contacts.navigation-card",
    label: "Contacts navigation card",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/contacts/ContactsNavigationCard.tsx",
    usedByScreens: ["pi.contacts.overview"],
  },
  "prime.advisor-tab": {
    id: "prime.advisor-tab",
    label: "Prime advisor tab",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/prime/YourAdvisorTab.tsx",
    usedByScreens: ["pi.prime.overview"],
  },
  "prime.benefits-tab": {
    id: "prime.benefits-tab",
    label: "Prime benefits tab",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/prime/YourBenefitsTab.tsx",
    usedByScreens: ["pi.prime.overview"],
  },
  "dialogs.logout-confirmation": {
    id: "dialogs.logout-confirmation",
    label: "Logout confirmation dialog",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/LogoutConfirmDialog.tsx",
    usedByScreens: ["pi.more.overview"],
    notes: "Reusable confirmation overlay used by More and the code-only logout-confirmation template.",
  },
  "kids.ro-prototype": {
    id: "kids.ro-prototype",
    label: "RO Kids prototype module",
    products: ["KIDS_PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/kids/RoKidsApp.tsx",
    usedByScreens: ["kids.ro.prototype"],
    notes: "Contained Romania-only Kids PI module with local state for kid home, request money, parent approvals, send money approval, card customization, saving goals, allowance, chores, Learn, onboarding, parent visibility, activation, parent dashboard, safety limits, and chore management.",
  },
};

export function getComponentMeta(componentId: ComponentId): ComponentMeta {
  return COMPONENT_REGISTRY[componentId];
}

export function getComponentsForScreen(screenId: ScreenId): ComponentMeta[] {
  return Object.values(COMPONENT_REGISTRY).filter((component) =>
    component.usedByScreens.includes(screenId)
  );
}
