/**
 * Component Registry
 * Machine-readable component catalog for AI reuse and coverage checks.
 */

import type {
  CapabilityStatus,
  ComponentId,
  DesignSystemId,
  ProductId,
  ScreenId,
} from "@/app/state/demoTypes";

export interface ComponentMeta {
  id: ComponentId;
  label: string;
  products: readonly ProductId[];
  designSystems: readonly DesignSystemId[];
  status: CapabilityStatus;
  componentPath: string;
  usedByScreens: readonly ScreenId[];
  notes?: string;
}

export const COMPONENT_REGISTRY: Record<ComponentId, ComponentMeta> = {
  "shell.mobile-frame": {
    id: "shell.mobile-frame",
    label: "Mobile frame",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/MobileFrame.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.home.overview",
      "pi.analytics.overview",
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payments.overview",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.investments.portfolio",
      "pi.products.overview",
      "pi.products.detail",
      "pi.prime.overview",
      "pi.more.overview",
      "pi.contacts.overview",
      "kids.sk.home-concept",
      "kids.hu.home-concept",
    ],
  },
  "shell.phone-screenshot-control": {
    id: "shell.phone-screenshot-control",
    label: "Phone screenshot control",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/demo/PhoneScreenshotControl.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.home.overview",
      "pi.analytics.overview",
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payments.overview",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.investments.portfolio",
      "pi.products.overview",
      "pi.prime.overview",
      "pi.more.overview",
      "pi.documents.overview",
      "pi.settings.overview",
      "pi.contacts.overview",
    ],
    notes: "Desktop demo-shell header control rendered as an icon-only camera dropdown immediately after the Control Panel/Settings button. Dropdown exports visible/full-height PNG captures and Figma-ready `build-ui.screen.v1` JSON via `Generate visible JSON` and `Generate entire screen JSON`; JSON is generated from an unscaled app-content clone and includes app background, numeric bounds, Figma paints/effects/text specs, assets, text safety width, cleaner fallback layer names, and conservative Auto Layout intent. Design System Inventory keeps the control visible but disabled.",
  },
  "shell.page-header": {
    id: "shell.page-header",
    label: "Page header",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/PageHeader.tsx",
    usedByScreens: [
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.documents.overview",
      "pi.settings.overview",
      "pi.contacts.overview",
      "pi.investments.portfolio",
      "pi.products.detail",
    ],
    notes: "Shared top-page header family used by runtime detail/list screens and reconstructed templates.",
  },
  "shell.bottom-navigation": {
    id: "shell.bottom-navigation",
    label: "Bottom navigation",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/BottomNavigation.tsx",
    usedByScreens: ["pi.home.overview", "pi.analytics.overview", "pi.payments.overview", "pi.products.overview", "pi.more.overview"],
    notes: "Fixed 375x54 bottom bar contract with 24px side padding, 32px icon slots, 24x2 active bar touching the icon slot, and 14px labels with 15px line-height and no icon/label gap.",
  },
  "shell.bottom-sheet": {
    id: "shell.bottom-sheet",
    label: "Bottom sheet shell",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/BottomSheet.tsx",
    usedByScreens: ["pi.payments.overview", "pi.products.overview"],
    notes: "Reusable overlay and rounded bottom panel shell for modal quick menus, with 16px uniform sheet padding. Products uses it for the OUR PRODUCTS category option sheet before opening product detail pages.",
  },
  "icons.app-icon": {
    id: "icons.app-icon",
    label: "App icon registry",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/icons/AppIcon.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.home.overview",
      "pi.analytics.overview",
      "pi.messages.overview",
      "pi.account.detail",
      "pi.account.details-info",
      "pi.account.options",
      "pi.transaction.detail",
      "pi.payments.overview",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.investments.portfolio",
      "pi.products.overview",
      "pi.prime.overview",
      "pi.more.overview",
      "pi.documents.overview",
      "pi.settings.overview",
      "pi.contacts.overview",
      "platform.design-system",
    ],
    notes: "Central source for reusable UI icons; templates and runtime screens should reference icons through this registry rather than direct lucide or raw SVG usage.",
  },
  "brand.unicredit-logo": {
    id: "brand.unicredit-logo",
    label: "UniCredit logo",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/UniCreditLogo.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active", "platform.design-system"],
  },
  "ui.primary-button": {
    id: "ui.primary-button",
    label: "Primary button",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/PrimaryButton.tsx",
    usedByScreens: [
      "pi.prelogin.inactive",
      "pi.prelogin.active",
      "pi.co-apping.session",
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
      "pi.products.detail",
      "pi.prime.overview",
      "platform.design-system",
    ],
  },
  "ui.text-field": {
    id: "ui.text-field",
    label: "Text field",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/TextField.tsx",
    usedByScreens: ["pi.co-apping.session", "pi.payment.domestic-create", "pi.payment.sign", "platform.design-system"],
  },
  "ui.amount-field": {
    id: "ui.amount-field",
    label: "Amount field",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/AmountField.tsx",
    usedByScreens: ["pi.payment.domestic-create", "platform.design-system"],
    notes: "Amount input variant with the same visual states as Text field plus a 24px-spaced currency selector column, 14px currency label, 18px currency value, and 32x32 trailing chevron with zero currency-to-chevron gap.",
  },
  "ui.link-button": {
    id: "ui.link-button",
    label: "Link button",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/LinkButton.tsx",
    usedByScreens: ["kids.hu.home-concept", "platform.design-system"],
    notes: "Reusable text action with chevron-link accessory: centered flex w-fit button, zero text-to-chevron gap, 13px bold uppercase label with 16px line-height, 24px chevron icon, current action color, and focus-visible ring.",
  },
  "ui.pill": {
    id: "ui.pill",
    label: "Pill",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/Pill.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Meniga-normalized pill button from Figma node `1057:21187`: 120x36, 18px radius, 8px horizontal padding, N5 14px bold centered label, 0 2 2 shadow, primary teal surface, white secondary/counter/loading/activated surfaces, 16px loading/success icons, and 8px icon-label gap.",
  },
  "ui.wallet-button": {
    id: "ui.wallet-button",
    label: "Wallet buttons",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/WalletButton.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Meniga-normalized 48px wallet/payment button family from Figma nodes `7464:1768`, `7464:1858`, and `7464:1912`. Exposes Google Wallet, Apple Wallet, and Click to Pay states, condensed and 327px long sizes, plus Google EN/HU/SK/CZ copy variants. Uses local vector marks instead of expiring Figma MCP assets.",
  },
  "ui.bar": {
    id: "ui.bar",
    label: "Bar",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/Bar.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Meniga-normalized Bar primitive from Figma node `1058:22155`: 375x8 Empty, Full, Mid 1, Mid 2, and Small states with a 24px left inset and teal active fill, plus the 279x1 Thin status.",
  },
  "ui.date-filter": {
    id: "ui.date-filter",
    label: "Date filter",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/DateFilter.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Meniga-normalized Date filter from Figma node `290:14520`: 238x24 wrapper, 4-item and 5-item states, 15px gaps, 35x22 chips, 3.5px radius, 14px bold labels, and teal selected chip.",
  },
  "ui.pill-sorting": {
    id: "ui.pill-sorting",
    label: "Pill sorting",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/PillSorting.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Meniga-normalized Pill sorting rail from Figma node `290:14610`: 375x40 row, 8px gap, 24px chip height, 14.5px radius, 14px regular idle labels, and black selected chip with bold white label.",
  },
  "ui.code-field": {
    id: "ui.code-field",
    label: "Code field",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/CodeField.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-normalized one-time-code field: 327px wrapper, centered 224px slot row, four 44x64 slots with 16px gap, 8px radius, 1px neutral/error border, N1 30px bold digits, numeric paste distribution, disabled/error states, aria-invalid messaging, and focus-visible ring.",
  },
  "ui.toast-message": {
    id: "ui.toast-message",
    label: "Toast message",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ui/ToastMessage.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Meniga-normalized Toast message family from Figma node `178:15386`: Action required light, Aware dark, and Google Pay dark states. The message capsule uses 16px radius, 14px bold UniCredit text, 327x32 icon variants with a 32px icon slot and centered 8px status-red dot, plus a 174x35 hug Google Pay confirmation variant.",
  },
  "ui.profile-avatar": {
    id: "ui.profile-avatar",
    label: "Profile avatar",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ProfileAvatar.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-derived 40x40 avatar family with full-photo, inset-profile-photo plus optional 8px notification dot, dark K1 initials fallback, and AI gradient avatar variants. Supports real image sources and controlled sizing for nearby runtime uses.",
  },
  "ui.navigation-row": {
    id: "ui.navigation-row",
    label: "Navigation row",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/NavigationRow.tsx",
    usedByScreens: ["pi.settings.overview", "pi.contacts.overview", "platform.design-system"],
    notes: "Figma-derived Navigation row family now mapped to the Meniga additional-cases node `1515:1995`: 18 selector variants covering icon/no-icon/toggle/special rows, 64px and 80px heights, 32px leading visuals, 64x40 card art, centered text-message/CTA rows, 16px bold title, optional 16px description, 14px teal CTA link, chevron accessory, and shared 60x30 ToggleButton.",
  },
  "ui.toggle-button": {
    id: "ui.toggle-button",
    label: "Toggle button",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ToggleButton.tsx",
    usedByScreens: ["pi.payment.review", "platform.design-system"],
    notes: "Figma-derived 60x30 switch-like control with explicit checked/unchecked states, white surface, 2px border, 22x22 knob, right-aligned teal success state, left-aligned gray off state, and accessible `role=switch` runtime behavior.",
  },
  "ui.radio-button": {
    id: "ui.radio-button",
    label: "Radio button",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/common/RadioButton.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active", "platform.design-system"],
  },
  "ui.section-heading-divider": {
    id: "ui.section-heading-divider",
    label: "Divider",
    products: ["PI", "KIDS_PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/SectionHeadingDivider.tsx",
    usedByScreens: ["pi.analytics.overview", "pi.payment.domestic-create", "pi.investments.portfolio", "pi.settings.overview", "pi.contacts.overview", "kids.hu.home-concept", "platform.design-system"],
    notes: "Shared section/divider family now mapped to Meniga Divider node `1058:22303`: keeps the legacy runtime `section` API intact while exposing 13 explicit DS states for small/medium/large titles, title+data, counters, action/date, name/action, checkbox action/date, and Light Restyle title/date/small-data variants.",
  },
  "prelogin.inactive": {
    id: "prelogin.inactive",
    label: "Pre-login inactive composition",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/components/PreLoginScreen.tsx",
    usedByScreens: ["pi.prelogin.inactive"],
  },
  "prelogin.active": {
    id: "prelogin.active",
    label: "Pre-login active composition",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/components/PreLoginActiveScreen.tsx",
    usedByScreens: ["pi.prelogin.active"],
  },
  "prelogin.language-selector": {
    id: "prelogin.language-selector",
    label: "Language selector",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/LanguageSelector.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active"],
    notes: "Country-aware local/English language selector used by pre-login templates.",
  },
  "prelogin.other-panel": {
    id: "prelogin.other-panel",
    label: "Other panel menu",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/PanelWithTranslations.tsx",
    usedByScreens: ["pi.prelogin.inactive", "pi.prelogin.active"],
    notes: "Translated pre-login panel pattern for Smart Banking, exchange rates, ATM/branches, and Co-Apping entry rows.",
  },
  "co-apping.floating-button": {
    id: "co-apping.floating-button",
    label: "Co-Apping floating button",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/FloatingCoAppingButton.tsx",
    usedByScreens: ["pi.home.overview", "pi.more.overview", "pi.contacts.overview"],
  },
  "co-apping.session-entry": {
    id: "co-apping.session-entry",
    label: "Co-Apping session entry",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/components/CoAppingSessionScreen.tsx",
    usedByScreens: ["pi.co-apping.session"],
  },
  "home.amount-visibility-toggle": {
    id: "home.amount-visibility-toggle",
    label: "Amount visibility toggle",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/AmountVisibilityButton.tsx",
    usedByScreens: ["pi.home.overview"],
    notes: "Toggles account/card/product amount masking across navigation while leaving transaction amounts visible.",
  },
  "home.account-summary": {
    id: "home.account-summary",
    label: "Home account summary",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/home/AccountSummary.tsx",
    usedByScreens: ["pi.home.overview"],
  },
  "home.account-balance-card": {
    id: "home.account-balance-card",
    label: "Account balance card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountBalanceCard.tsx",
    usedByScreens: ["pi.account.detail"],
  },
  "home.unplanned-banner": {
    id: "home.unplanned-banner",
    label: "Unplanned banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/home/UnplannedBanner.tsx",
    usedByScreens: ["pi.home.overview"],
  },
  "analytics.spendings": {
    id: "analytics.spendings",
    label: "Analytics spendings overview",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/analytics/AnalyticsScreen.tsx",
    usedByScreens: ["pi.analytics.overview"],
    notes: "Screenshot-inspired My Spendings screen with transaction-derived inflow/outflow bars, cash transaction banner, interactive PFM-category Money Out / Money In summaries, and session recategorization reflected in its aggregates.",
  },
  "analytics.category-details": {
    id: "analytics.category-details",
    label: "PFM spending category details",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/analytics/PfmCategoryDetailScreen.tsx",
    usedByScreens: ["pi.analytics.overview", "pi.transaction.detail"],
    notes: "Production-reference-derived Money Out/Money In category drill-down with connected period totals, proportional subcategory bubbles, Add Transaction action, matching transaction rows, and the dismissible Uncategorized helper. Data is session-local and mock-driven.",
  },
  "pfm.category-icon": {
    id: "pfm.category-icon",
    label: "PFM category icon",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/components/pfm/PfmCategoryIcon.tsx",
    usedByScreens: ["pi.account.detail", "pi.analytics.overview"],
    notes: "Token-driven PFM category icon mapped from screenshots/PFM-icons.svg; Taxes and Penalties, Income, Home, Utilities, Transportation, Children, Healthcare, Shopping, Lifestyle, Education, Leisure time, Investments, Uncategorized, Groceries, Exclude from budget, Insurance, Finance, Wallet, and Transfers render real 20x20 SVG glyphs inside a 32x32 container, while remaining categories still fall back to initials.",
  },
  "pfm.category-change-sheet": {
    id: "pfm.category-change-sheet",
    label: "PFM category change sheet",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/components/pfm/PfmCategoryChangeSheet.tsx",
    usedByScreens: ["pi.account.detail", "pi.transaction.detail"],
    notes: "Production-screenshot-derived recategorization sheet with 18 initially collapsed expense groups, 103 mapped subcategories, search, single radio selection, and a guarded confirmation action. It updates deterministic demo-session transaction presentation only; no backend persistence is implied.",
  },
  "messages.mailbox-tabs": {
    id: "messages.mailbox-tabs",
    label: "Messages mailbox tabs",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/messages/MessagesMailboxTabs.tsx",
    usedByScreens: ["pi.messages.overview", "pi.investments.portfolio", "platform.design-system"],
    notes: "Reusable Design System tab switcher for Messages-family screens, templates, and Investments portfolio tabs, with 48px height, active leading 12px dot when configured, muted inactive label, 2px bottom active indicator, and equal-width or horizontally scrollable layouts.",
  },
  "messages.inbox-list": {
    id: "messages.inbox-list",
    label: "Messages inbox and outbox list",
    products: ["PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/messages/MessagesScreen.tsx",
    usedByScreens: ["pi.messages.overview"],
    notes: "Runtime screen reconstructed from template 52, using the shared PageHeader, country-addressable extended mock Inbox/Outbox data, reusable MessagesMailboxTabs, AccountSearchBar, date rows, NEW badges, row action dots, and page-level scrolling.",
  },
  "accounts.action-bar": {
    id: "accounts.action-bar",
    label: "Account action bar",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountActionBar.tsx",
    usedByScreens: ["pi.account.detail", "pi.analytics.overview"],
    notes: "Reusable 1-4 item action bar with shared 32px icon slot, 14px/15px label contract, and page-level alignment options.",
  },
  "accounts.details-info": {
    id: "accounts.details-info",
    label: "Account details information screen",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/accounts/AccountDetailsInfoScreen.tsx",
    usedByScreens: ["pi.account.details-info"],
    notes: "Uses AccountDetailsInfoField rows for the account-number-with-icon variant and default title/subtitle fields.",
  },
  "accounts.details-info-field": {
    id: "accounts.details-info-field",
    label: "Account details info field",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountDetailsInfoField.tsx",
    usedByScreens: ["pi.account.details-info"],
    notes: "80px reusable Account Details title/subtitle row with 4px internal title-to-subtitle gap, 16px normal title, 16px bold subtitle, and optional trailing-icon variant.",
  },
  "accounts.transaction-search": {
    id: "accounts.transaction-search",
    label: "Account transaction search",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountSearchBar.tsx",
    usedByScreens: ["pi.account.detail"],
    notes: "Searches the current account transaction list, uses 32x32 search and filter/clear icon slots with icon-driven 32px height, swaps the filter icon for a clear-results action while a query is active, and supports the Meniga `Type=Active remove filters` state from node `1517:12655` with teal filter icon plus 14px bold `REMOVE FILTERS` action. Keeps the search bar pinned at the top of the list.",
  },
  "accounts.transaction-row": {
    id: "accounts.transaction-row",
    label: "Account transaction row",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/accounts/AccountTransactionRow.tsx",
    usedByScreens: ["pi.account.detail"],
    notes: "Renders account transactions with a PFM category badge sourced from the shared PFM category map, fixed date/icon spacing, 18px transaction label line-height, 22px amount line-height, and 16px list spacing around month dividers in Account Detail. Its optional split-interaction mode opens PFM recategorization from the icon while the detail column preserves Transaction Details navigation.",
  },
  "transactions.detail": {
    id: "transactions.detail",
    label: "Transaction detail screen",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    usedByScreens: ["pi.transaction.detail"],
    notes: "Shows transaction amount, a transaction-derived PFM category pill with the shared PFM icon glyph, category actions, spending insight, details, a connected Change category sheet, and a Redo payment entry into domestic payment.",
  },
  "payments.menu": {
    id: "payments.menu",
    label: "Payments menu",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/PaymentsScreen.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Country-scoped Payments hub. Default countries keep the original four primary cards and OTHER rail, while BA and BA_BL render five primary cards and five OTHER shortcuts with supplied market copy.",
  },
  "payments.templates-screen": {
    id: "payments.templates-screen",
    label: "Payments templates screen",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/PaymentTemplatesScreen.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Searchable local Payments child view for fictional saved templates and beneficiaries. Selecting an item enters the existing Domestic Payment flow with a typed prefilled draft.",
  },
  "payments.template-list-item": {
    id: "payments.template-list-item",
    label: "Payment template list item",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/PaymentTemplateListItem.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Semantic saved-template or beneficiary row with the canonical Payments template icon and screenshot-aligned account/amount hierarchy.",
  },
  "payments.exchange-rates-screen": {
    id: "payments.exchange-rates-screen",
    label: "Payments exchange rates screen",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/ExchangeRatesScreen.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Connected deterministic FX calculator with country-currency default, editable amount, currency-selection BottomSheet, and recalculated target rows.",
  },
  "payments.exchange-rate-list-item": {
    id: "payments.exchange-rate-list-item",
    label: "Payments exchange rate list item",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/ExchangeRateListItem.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Currency row showing the target flag/code, unit relationship to the selected source currency, and connected converted amount; tapping promotes the row currency to source.",
  },
  "payments.currency-flag": {
    id: "payments.currency-flag",
    label: "Currency flag",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/CurrencyFlag.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Platform-independent 36x24 SVG artwork for all supported demo currencies, avoiding Windows regional-letter glyph fallback.",
  },
  "payments.hero-card": {
    id: "payments.hero-card",
    label: "Payments hero card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/PaymentHeroCard.tsx",
    usedByScreens: ["pi.payments.overview", "platform.design-system"],
    notes: "Reusable 327x120 Payments primary card. Title is 24px bold, starts 16px from the top, respects supplied line breaks without ellipsis, and the 14px description sits 16px below single-line titles or 8px below explicitly multiline titles. Supports 9 screenshot-backed image variants (`payments1.png` through `payments9.png`) plus an optional imageSrc override.",
  },
  "payments.other-shortcut": {
    id: "payments.other-shortcut",
    label: "Payments Other shortcut",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/PaymentOtherShortcut.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable single shortcut action used in Payments OTHER, with the PaymentOtherShortcutIconBubble atom above a 14px UniCredit bold centered label using normal line-height and no letter spacing.",
  },
  "payments.other-shortcut-icon-bubble": {
    id: "payments.other-shortcut-icon-bubble",
    label: "Payments Other shortcut icon bubble",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/PaymentOtherShortcut.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable Payments OTHER bubble atom: flex hug container with 8px padding, centered 32x32 icon slot, 10px internal gap token, circular action background, and no oversized 58px wrapper.",
  },
  "payments.new-payment-sheet": {
    id: "payments.new-payment-sheet",
    label: "New payment bottom sheet",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/PaymentsScreen.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Opens from the New payment card and renders country-scoped payment-type labels from paymentsMenuConfig.",
  },
  "payments.new-payment-action": {
    id: "payments.new-payment-action",
    label: "New payment action row",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/NewPaymentActionListItem.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable 80px New payment bottom-sheet row with supplied action icon, title, subtitle, and chevron.",
  },
  "payments.new-payment-discover-banner": {
    id: "payments.new-payment-discover-banner",
    label: "New payment discover banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/payments/NewPaymentDiscoverBanner.tsx",
    usedByScreens: ["pi.payments.overview"],
    notes: "Reusable teal help banner for New payment with supplied info and close icons, 16px padding, 4px title/subtitle gap, and normal text line-height.",
  },
  "payments.domestic-flow": {
    id: "payments.domestic-flow",
    label: "Domestic payment flow",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    usedByScreens: [
      "pi.payment.domestic-create",
      "pi.payment.review",
      "pi.payment.sign",
      "pi.payment.success",
    ],
    notes: "Creates domestic payments either blank from Payments/New payment or prefilled from Transaction detail/Redo payment.",
  },
  "investments.portfolio-tabs": {
    id: "investments.portfolio-tabs",
    label: "Investments portfolio tabs",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentPortfolioTabs.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Controlled Investments wrapper around the shared MessagesMailboxTabs Design System component, using its horizontally scrollable layout for Performance, Product type, Currency, Asset class, and Account list.",
  },
  "investments.portfolio-chart": {
    id: "investments.portfolio-chart",
    label: "Investments portfolio chart",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentPortfolioChart.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Reusable Recharts line/area chart driven by portfolio value and selected period points rather than a static screenshot or hand-drawn chart.",
  },
  "investments.distribution-chart": {
    id: "investments.distribution-chart",
    label: "Investments distribution chart",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentDistributionChart.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Reusable donut/list distribution view for Product type, Currency, Asset class, and Account list tabs. Distribution values are grouped from the same portfolio securities and sum back to the owned investment total in local currency.",
  },
  "investments.period-chips": {
    id: "investments.period-chips",
    label: "Investments period chips",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentPeriodChips.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Controlled period selector for 1M, 3M, 6M, 1Y, 3Y, and ALL chart views.",
  },
  "investments.action-bar": {
    id: "investments.action-bar",
    label: "Investments action bar",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentActionBar.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Investments-specific 3-small-actions plus compact Invest CTA variation of the max-four action-button pattern. The Invest CTA is a 56x56 teal circle with a 32x32 growth/investment glyph and lowercase 11px `invest` label, matching the supplied Figma JSON.",
  },
  "investments.filter-chips": {
    id: "investments.filter-chips",
    label: "Investments filter chips",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentFilterChips.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Controlled sorting chips for Max value, Min value, Max %, and Min %, wired to sort displayed investment instruments.",
  },
  "investments.products-accordion": {
    id: "investments.products-accordion",
    label: "Investments products accordion",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentProductsAccordion.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Collapsible Active securities and Inactive securities list sections with inline item counts.",
  },
  "investments.product-card": {
    id: "investments.product-card",
    label: "Investment product card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentProductCard.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Reusable investment instrument row/card with source product, value, performance amount, contribution type, and percentage movement.",
  },
  "investments.fund-banner": {
    id: "investments.fund-banner",
    label: "Investments fund suggestion banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/investments/InvestmentsFundBanner.tsx",
    usedByScreens: ["pi.investments.portfolio"],
    notes: "Reusable CTA banner for fund discovery with title, description, tertiary action, and decorative finance illustration.",
  },
  "templates.reconstructed-code": {
    id: "templates.reconstructed-code",
    label: "Reconstructed code templates",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Renders 50 real JSX template previews: all 30 screenshot-backed templates plus 20 code-only templates derived from active pre-login, panel, Co-Apping, Home/account, Payments, Products, More, Contacts, Messages, Spending, Prime, and dialog patterns. Source PNG/JPG files remain comparison evidence where they exist.",
  },
  "products.menu": {
    id: "products.menu",
    label: "Products menu",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/products/ProductsScreen.tsx",
    usedByScreens: ["pi.products.overview"],
    notes: "Country-scoped configuration controls whether the Banking/ShopSmart tabs are visible, whether offer rails/headings render, and which product cards remain. BA and BA_BL are cards-only with Accounts, Cards, Loans, and Savings. Product sheet rows now open the shared product-detail page with the selected row title.",
  },
  "products.offer-card": {
    id: "products.offer-card",
    label: "Products offer card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/products/ProductOfferCard.tsx",
    usedByScreens: ["pi.products.overview"],
    notes: "Reusable 327x157 offer carousel card with centered vertical chevron background, a text area that fills to 16px before the fixed 100px right image column, and selectable family/light-tone pairs covering green, yellow, orange, pink, red, blue, and grey banner variants. Two size variants: \"standard\" (22px bold title / 2 lines, 18px regular subtitle / 3 lines) and \"compact\" (20px bold title / 2 lines, 16px regular subtitle / 3 lines, plus an optional 14px one-line caption below the subtitle).",
  },
  "products.shopsmart-offer-card": {
    id: "products.shopsmart-offer-card",
    label: "Shopsmart offer card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/shopsmart/ShopsmartOfferCard.tsx",
    usedByScreens: ["pi.products.overview", "platform.design-system"],
    notes: "Figma-mapped Shopsmart card component from Meniga DS nodes 9185:16470 and 9185:16260 plus RO Enablers ShopSmart runtime state 2843:35520. Supports the activate/active pill variant, orange free-shipping tag variant, local Figma image assets, 327px width, 8px radius, #666 border, 130/143px image heights, merchant/title/status typography, optional distance, and website/partner trailing icon.",
  },
  "products.product-card": {
    id: "products.product-card",
    label: "Products menu card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/products/ProductMenuCard.tsx",
    usedByScreens: ["pi.products.overview"],
    notes: "Reusable Products menu card with a 164x120 standard variant and a 164x72 compact variant. Product config controls title, background, fallback illustration, and optional imageSrc artwork; the component positions supplied artwork per card family for Account, Cards, Mortgages and Loans, Insurance, Investments and Savings, Market Hedging, Shopsmart, and Partner Offers without changing country runtime baselines unless config passes those cards.",
  },
  "products.product-card-list-total": {
    id: "products.product-card-list-total",
    label: "Product card / list / total row - evolution",
    products: ["PI", "SME"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/ProductCard.tsx + src/app/components/ProductsList.tsx + src/app/components/TotalRow.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-mapped Products specimen from `Product card - evolution` component set node `8724:1885` (requested share node `9201:7443` resolved through the file). Covers PI app and SME app Default, Accordion, and Open variants with 327px cards, 16px padding, 4px radius, 32px icon slot, 24px card amount integer, 14px decimals/currency, and 20px total-row integer. Runtime callers keep legacy behavior unless they opt into `variant=\"evolution\"`.",
  },
  "cards.card": {
    id: "cards.card",
    label: "Card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/Card.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-mapped 64x40 Mastercard card artwork family sourced from Meniga Harmonization Icons nodes `3039:30713`, `3039:7485`, `3039:8064`, `4161:9198`, `3039:12315`, and `3039:12380`. The React component exposes a variant registry for MC Debit Gold, MC Credit Premium Gold, MC Credit Partner Standard, MC Debit Standard, MC Virtual Standard Electric Violet, and MC Virtual Standard Vibrant Orange, preserving the shared card structure while applying the Figma-sampled color palettes and debit/credit labels. Supports controlled figma, medium, and large sizing without changing runtime screen behavior.",
  },
  "cards.ghost-banner": {
    id: "cards.ghost-banner",
    label: "Ghost Banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/GhostBanner.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-extracted 327x92 dashed-border CTA banner generated from `codex-figma-component-spec/v1` node `9103:14301`. Leading 32x32 system add icon (`add-circle`, teal `--uc-action`) beside an 18px bold title and a 16px regular multiline description, both `--uc-text`. 16px padding, 8px radius, dashed `--uc-text` border, 10px vertical gap, 8px icon-to-text gap, 4px title-to-description gap. Renders as a button when `onClick` is supplied.",
  },
  "cards.info-banner": {
    id: "cards.info-banner",
    label: "Info Banner",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/InfoBanner.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-extracted 327x153 solid-border informational banner generated from `codex-figma-component-spec/v1` node `9104:14329`. Leading 32x32 `info-circle` icon (`--uc-text`) beside an 18px bold title and a 16px regular multiline description, both `--uc-text`, plus an optional 14px bold teal text action (`--uc-action`, e.g. EDIT). 16px padding, 8px radius, solid `--uc-text` border, 8px icon-to-text gap, 8px text-block-to-action gap, 4px title-to-description gap. Static region; the inline action is the only interactive element.",
  },
  "cards.user-event-card": {
    id: "cards.user-event-card",
    label: "User Event Card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/UserEventCard.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-extracted 343-wide white shadowed card generated from `codex-figma-component-spec/v1` `User events` (full node `9104:14482`, compact node `9104:14438`). Leading 48x48 teal (`--uc-action`) avatar circle with a white 24x24 glyph, a 14px bold title and a 14px regular multiline description (both `--uc-text`). One component covers both Figma variants via props: `actionLabel` renders a 14px bold teal text link and `showOptions` renders the trailing 32x32 `more-horizontal` overflow control. 16px padding, 8px radius, `0 4px 16px rgba(0,0,0,0.08)` shadow, 8px gaps; aligns items center without an action and start with one.",
  },
  "cards.helper-card": {
    id: "cards.helper-card",
    label: "Helper Card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/HelperCard.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-extracted 343-wide solid teal helper generated from `codex-figma-component-spec/v1` `Helpers` (plain node `9104:14526`, with-link node `9104:14570`). Leading 32x32 white `info-circle`, an 18px bold white title and an 18px regular white multiline body. One component covers both variants via props: `actionLabel` renders a 14px bold white text link and `dismissible` renders a white `close-x` control top-right. Teal `--uc-action` background, 4px radius, 16px padding, white text via `--uc-static-white`.",
  },
  "cards.pending-action-card": {
    id: "cards.pending-action-card",
    label: "Pending Action Card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/PendingActionCard.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-extracted 327x157 teal-gradient promo card generated from `codex-figma-component-spec/v1` node `9104:14611`. Left-to-right `linear-gradient(90deg, #007A91, #44909E)` background, 8px radius, 24px padding. 24px bold white title, 18px regular white body, and an optional white pill (`--uc-static-white`) with a teal `warning-small` glyph and a 12px bold uppercase teal label (e.g. EXPIRING ON 12.04.25). Renders as a button when `onClick` is supplied.",
  },
  "cards.card-component": {
    id: "cards.card-component",
    label: "Card Component",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/cards/CardComponent.tsx",
    usedByScreens: ["platform.design-system"],
    notes: "Figma-extracted 375-wide card management section generated from `codex-figma-component-spec/v1` node `9133:3831` (Card component). Primary/K7 (#F5F5F5) background, vertical layout with 12px gap, clips content. Frame 46 has 24px left padding, 8px gap: a 169-wide text column with 14px bold N5 card-holder name and 18px bold L2 masked card number (both K1, UniCredit Bold). Cards carousel is 351x140 horizontal with 24px gap and 1px left padding; each 219x138 card slot renders the shared `cards.card` component variant with 5.67px corner radius and a 0 11.265px 11.265px rgba(0,0,0,0.2) drop-shadow. No card artwork image asset or outside border is used.",
  },
  "more.card-grid": {
    id: "more.card-grid",
    label: "More service card grid",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/more/MoreScreen.tsx",
    usedByScreens: ["pi.more.overview"],
    notes: "Country-scoped More card matrix. BA and BA_BL include Tutorials plus My applications after Settings and use Contact phone + Messages header actions.",
  },
  "contacts.navigation-card": {
    id: "contacts.navigation-card",
    label: "Contacts navigation card",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/screens/contacts/ContactsNavigationCard.tsx",
    usedByScreens: ["pi.contacts.overview"],
    notes: "Country contact rows now delegate to the shared NavigationRow component while keeping the contact-specific icon registry and chevron/value variants.",
  },
  "prime.advisor-tab": {
    id: "prime.advisor-tab",
    label: "Prime advisor tab",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/prime/YourAdvisorTab.tsx",
    usedByScreens: ["pi.prime.overview"],
  },
  "prime.benefits-tab": {
    id: "prime.benefits-tab",
    label: "Prime benefits tab",
    products: ["PI"],
    designSystems: ["current"],
    status: "partial",
    componentPath: "src/app/screens/prime/YourBenefitsTab.tsx",
    usedByScreens: ["pi.prime.overview"],
  },
  "dialogs.logout-confirmation": {
    id: "dialogs.logout-confirmation",
    label: "Logout confirmation dialog",
    products: ["PI"],
    designSystems: ["current"],
    status: "implemented",
    componentPath: "src/app/components/LogoutConfirmDialog.tsx",
    usedByScreens: ["pi.more.overview"],
    notes: "Reusable confirmation overlay used by More and the code-only logout-confirmation template.",
  },
  "kids.market-home-concepts": {
    id: "kids.market-home-concepts",
    label: "Kids market homepage concepts",
    products: ["KIDS_PI"],
    designSystems: ["current"],
    status: "mock-driven",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    usedByScreens: [
      "kids.sk.home-concept",
      "kids.hu.home-concept",
    ],
    notes: "Country-contained Kids homepage and bottom-navigation concepts for Slovakia and Hungary. The same module uses market-specific mock data and intentionally different UI directions: SK Bulbank document-inspired Products/Education/Tasks/More and HU CEE Light Restyle/theme personalization.",
  },
};

export function getComponentMeta(componentId: ComponentId): ComponentMeta {
  return COMPONENT_REGISTRY[componentId];
}

export function getComponentsForScreen(screenId: ScreenId): ComponentMeta[] {
  return Object.values(COMPONENT_REGISTRY).filter((component) =>
    component.usedByScreens.includes(screenId)
  );
}
