/**
 * Screen Registry
 * Machine-readable screen catalog for demo navigation, AI flow composition, and coverage checks.
 */

import type { Screen } from "@/app/contexts/NavigationContext";
import type {
  CapabilityStatus,
  CountryId,
  DesignSystemId,
  FeatureId,
  ProductId,
  ScreenId,
} from "@/app/state/demoTypes";

export type LayoutFamily =
  | "prelogin"
  | "co-apping"
  | "dashboard"
  | "analytics"
  | "messages"
  | "account-detail"
  | "account-options"
  | "payments"
  | "payment-flow"
  | "investments"
  | "products"
  | "prime"
  | "service-menu"
  | "contacts"
  | "kids"
  | "design-system";

export interface ScreenMeta {
  id: ScreenId;
  label: string;
  runtimeScreen: Screen;
  products: readonly ProductId[];
  countries: readonly CountryId[];
  designSystems: readonly DesignSystemId[];
  status: CapabilityStatus;
  layoutFamily: LayoutFamily;
  componentPath: string;
  features: readonly FeatureId[];
  screenshots: readonly string[];
  similarTo: readonly ScreenId[];
}

const ALL_COUNTRIES: readonly CountryId[] = ["RO", "CZ", "SK", "HU", "RS", "BA", "BA_BL", "SI"] as const;

export const SCREEN_REGISTRY: Record<ScreenId, ScreenMeta> = {
  "pi.prelogin.inactive": {
    id: "pi.prelogin.inactive",
    label: "PI Pre-login inactive",
    runtimeScreen: "prelogin-inactive",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "prelogin",
    componentPath: "src/app/components/PreLoginScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.prelogin.active"],
  },
  "pi.prelogin.active": {
    id: "pi.prelogin.active",
    label: "PI Pre-login active",
    runtimeScreen: "prelogin-active",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "prelogin",
    componentPath: "src/app/components/PreLoginActiveScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.prelogin.inactive"],
  },
  "pi.co-apping.session": {
    id: "pi.co-apping.session",
    label: "PI Co-Apping session",
    runtimeScreen: "co-apping-session",
    products: ["PI"],
    countries: ["CZ", "SK"],
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "co-apping",
    componentPath: "src/app/components/CoAppingSessionScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: [],
  },
  "pi.home.overview": {
    id: "pi.home.overview",
    label: "PI Home overview",
    runtimeScreen: "homepage",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "dashboard",
    componentPath: "src/app/screens/home/HomeScreen.tsx",
    features: [
      "fx_cardsRedesign",
      "fx_unplannedBanner",
      "fx_newPaymentsHub",
      "fx_quickActionsRedesign",
      "fx_transactionsFilters",
      "fx_enhancedAnalytics",
    ],
    screenshots: ["screenshots/homepage.png"],
    similarTo: [],
  },
  "pi.analytics.overview": {
    id: "pi.analytics.overview",
    label: "PI Analytics spendings",
    runtimeScreen: "analytics",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "analytics",
    componentPath: "src/app/screens/analytics/AnalyticsScreen.tsx",
    features: ["fx_enhancedAnalytics"],
    screenshots: ["screenshots/Analytics.jpg"],
    similarTo: ["pi.home.overview"],
  },
  "pi.messages.overview": {
    id: "pi.messages.overview",
    label: "PI Messages inbox",
    runtimeScreen: "messages",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "messages",
    componentPath: "src/app/screens/messages/MessagesScreen.tsx",
    features: [],
    screenshots: ["screenshots/52.png"],
    similarTo: ["pi.more.overview", "pi.analytics.overview"],
  },
  "pi.account.detail": {
    id: "pi.account.detail",
    label: "PI Account detail",
    runtimeScreen: "account-detail",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "account-detail",
    componentPath: "src/app/screens/accounts/AccountDetailScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.account.details-info", "pi.account.options"],
  },
  "pi.account.details-info": {
    id: "pi.account.details-info",
    label: "PI Account details info",
    runtimeScreen: "account-details-info",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "account-detail",
    componentPath: "src/app/screens/accounts/AccountDetailsInfoScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.account.detail", "pi.account.options"],
  },
  "pi.account.options": {
    id: "pi.account.options",
    label: "PI Account options",
    runtimeScreen: "account-options",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "account-options",
    componentPath: "src/app/screens/accounts/AccountOptionsScreen.tsx",
    features: [],
    screenshots: ["screenshots/account-options.png"],
    similarTo: ["pi.account.detail", "pi.account.details-info"],
  },
  "pi.transaction.detail": {
    id: "pi.transaction.detail",
    label: "PI Transaction detail",
    runtimeScreen: "transaction-detail",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "account-detail",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    features: ["fx_newPaymentsHub"],
    screenshots: ["screenshots/Transaction detail.png"],
    similarTo: ["pi.account.detail", "pi.payment.domestic-create"],
  },
  "pi.payments.overview": {
    id: "pi.payments.overview",
    label: "PI Payments overview",
    runtimeScreen: "payments",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "payments",
    componentPath: "src/app/screens/payments/PaymentsScreen.tsx",
    features: ["fx_newPaymentsHub"],
    screenshots: [],
    similarTo: ["pi.more.overview"],
  },
  "pi.payment.domestic-create": {
    id: "pi.payment.domestic-create",
    label: "PI Domestic payment create",
    runtimeScreen: "domestic-payment",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "payment-flow",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    features: ["fx_newPaymentsHub"],
    screenshots: ["screenshots/Payment.png"],
    similarTo: ["pi.payment.review"],
  },
  "pi.payment.review": {
    id: "pi.payment.review",
    label: "PI Payment review data",
    runtimeScreen: "payment-review",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "payment-flow",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    features: ["fx_newPaymentsHub"],
    screenshots: ["screenshots/Review.png"],
    similarTo: ["pi.payment.domestic-create", "pi.payment.sign"],
  },
  "pi.payment.sign": {
    id: "pi.payment.sign",
    label: "PI Payment sign",
    runtimeScreen: "payment-sign",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "payment-flow",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    features: ["fx_newPaymentsHub"],
    screenshots: ["screenshots/Language Selection.png"],
    similarTo: ["pi.payment.review", "pi.payment.success"],
  },
  "pi.payment.success": {
    id: "pi.payment.success",
    label: "PI Payment success",
    runtimeScreen: "payment-success",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "payment-flow",
    componentPath: "src/app/screens/payments/DomesticPaymentFlowScreens.tsx",
    features: ["fx_newPaymentsHub"],
    screenshots: ["screenshots/Transfer to new phone.png"],
    similarTo: ["pi.payment.sign"],
  },
  "pi.products.overview": {
    id: "pi.products.overview",
    label: "PI Products overview",
    runtimeScreen: "products",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "implemented",
    layoutFamily: "products",
    componentPath: "src/app/screens/products/ProductsScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.payments.overview", "pi.more.overview"],
  },
  "pi.investments.portfolio": {
    id: "pi.investments.portfolio",
    label: "PI Investments portfolio",
    runtimeScreen: "investments",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "investments",
    componentPath: "src/app/screens/investments/InvestmentsPortfolioScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.account.detail", "pi.products.overview"],
  },
  "pi.prime.overview": {
    id: "pi.prime.overview",
    label: "PI Prime overview",
    runtimeScreen: "prime",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "prime",
    componentPath: "src/app/screens/prime/PrimeScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: [],
  },
  "pi.more.overview": {
    id: "pi.more.overview",
    label: "PI More overview",
    runtimeScreen: "more",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "service-menu",
    componentPath: "src/app/screens/more/MoreScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.documents.overview", "pi.settings.overview", "pi.contacts.overview"],
  },
  "pi.documents.overview": {
    id: "pi.documents.overview",
    label: "PI Documents overview",
    runtimeScreen: "documents",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "messages",
    componentPath: "src/app/screens/documents/DocumentsScreen.tsx",
    features: [],
    screenshots: ["screenshots/Documents.png"],
    similarTo: ["pi.messages.overview", "pi.more.overview"],
  },
  "pi.settings.overview": {
    id: "pi.settings.overview",
    label: "PI Settings overview",
    runtimeScreen: "settings",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "service-menu",
    componentPath: "src/app/screens/settings/SettingsScreen.tsx",
    features: [],
    screenshots: ["screenshots/Settings.png"],
    similarTo: ["pi.more.overview", "pi.contacts.overview"],
  },
  "pi.contacts.overview": {
    id: "pi.contacts.overview",
    label: "PI Contacts overview",
    runtimeScreen: "contacts",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "contacts",
    componentPath: "src/app/screens/contacts/ContactsScreen.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.more.overview"],
  },
  "kids.ro.prototype": {
    id: "kids.ro.prototype",
    label: "RO Kids banking prototype",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["RO"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/RoKidsApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["pi.home.overview", "pi.payments.overview", "pi.more.overview"],
  },
  "kids.cz.home-concept": {
    id: "kids.cz.home-concept",
    label: "CZ Kids homepage concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["CZ"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.ro.prototype", "pi.home.overview"],
  },
  "kids.sk.home-concept": {
    id: "kids.sk.home-concept",
    label: "SK Kids Bulbank document-inspired concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["SK"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.cz.home-concept", "kids.ro.prototype", "pi.products.overview"],
  },
  "kids.hu.home-concept": {
    id: "kids.hu.home-concept",
    label: "HU Kids smart homepage concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["HU"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.sk.home-concept", "kids.cz.home-concept", "kids.ro.prototype"],
  },
  "kids.rs.home-concept": {
    id: "kids.rs.home-concept",
    label: "RS Kids safe-spend coach concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["RS"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.hu.home-concept", "kids.ro.prototype", "pi.analytics.overview"],
  },
  "kids.ba.home-concept": {
    id: "kids.ba.home-concept",
    label: "BA Kids family homepage concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["BA"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.ro.prototype", "kids.cz.home-concept"],
  },
  "kids.ba-bl.home-concept": {
    id: "kids.ba-bl.home-concept",
    label: "BA BL Kids card-first homepage concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["BA_BL"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.ba.home-concept", "kids.hu.home-concept", "kids.ro.prototype"],
  },
  "kids.si.home-concept": {
    id: "kids.si.home-concept",
    label: "SI Kids goal-coach homepage concept",
    runtimeScreen: "homepage",
    products: ["KIDS_PI"],
    countries: ["SI"],
    designSystems: ["current"],
    status: "mock-driven",
    layoutFamily: "kids",
    componentPath: "src/app/screens/kids/KidsMarketHomeApp.tsx",
    features: [],
    screenshots: [],
    similarTo: ["kids.sk.home-concept", "kids.hu.home-concept", "kids.ro.prototype"],
  },
  "platform.design-system": {
    id: "platform.design-system",
    label: "Design system inventory",
    runtimeScreen: "design-system",
    products: ["PI"],
    countries: ALL_COUNTRIES,
    designSystems: ["current"],
    status: "partial",
    layoutFamily: "design-system",
    componentPath: "src/app/screens/design-system/DesignSystemPage.tsx",
    features: [],
    screenshots: [],
    similarTo: [],
  },
};

export function getScreenMeta(screenId: ScreenId): ScreenMeta {
  return SCREEN_REGISTRY[screenId];
}

export function getScreensForRuntimeScreen(runtimeScreen: Screen): ScreenMeta[] {
  return Object.values(SCREEN_REGISTRY).filter((screen) => screen.runtimeScreen === runtimeScreen);
}
