export type TemplateRegistryItem = {
  id: string;
  name: string;
  sourcePath: string;
  imageSrc: string;
  width: number;
  height: number;
  format: "png" | "jpg";
  relatedComponents: string[];
};

const screenshotUrl = (fileName: string) => new URL(`../../../screenshots/${fileName}`, import.meta.url).href;

export const TEMPLATE_REGISTRY: TemplateRegistryItem[] = [
  {
    id: "template-52",
    name: "52",
    sourcePath: "screenshots/52.png",
    imageSrc: screenshotUrl("52.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["MobileFrame", "StatusBar", "DynamicIsland"],
  },
  {
    id: "template-67",
    name: "67",
    sourcePath: "screenshots/67.png",
    imageSrc: screenshotUrl("67.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["MobileFrame", "StatusBar", "DynamicIsland"],
  },
  {
    id: "template-account-options",
    name: "Account options",
    sourcePath: "screenshots/account-options.png",
    imageSrc: screenshotUrl("account-options.png"),
    width: 375,
    height: 1038,
    format: "png",
    relatedComponents: ["AccountOptionsScreen", "PageHeader"],
  },
  {
    id: "template-activate-mtoken",
    name: "Activate mToken",
    sourcePath: "screenshots/Activate mToken.jpg",
    imageSrc: screenshotUrl("Activate mToken.jpg"),
    width: 754,
    height: 1628,
    format: "jpg",
    relatedComponents: ["PreLoginActiveScreen", "PrimaryButton"],
  },
  {
    id: "template-analytics",
    name: "Analytics",
    sourcePath: "screenshots/Analytics.jpg",
    imageSrc: screenshotUrl("Analytics.jpg"),
    width: 754,
    height: 1628,
    format: "jpg",
    relatedComponents: ["BottomNavigation", "PageHeader"],
  },
  {
    id: "template-apple-pay",
    name: "Apple pay",
    sourcePath: "screenshots/Apple pay.png",
    imageSrc: screenshotUrl("Apple pay.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-cards",
    name: "Cards",
    sourcePath: "screenshots/Cards.jpg",
    imageSrc: screenshotUrl("Cards.jpg"),
    width: 754,
    height: 1996,
    format: "jpg",
    relatedComponents: ["ProductCard", "ProductsList", "BottomNavigation"],
  },
  {
    id: "template-contact",
    name: "Contact",
    sourcePath: "screenshots/Contact.png",
    imageSrc: screenshotUrl("Contact.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["ContactsDivider", "ContactsNavigationCard", "PageHeader"],
  },
  {
    id: "template-documents",
    name: "Documents",
    sourcePath: "screenshots/Documents.png",
    imageSrc: screenshotUrl("Documents.png"),
    width: 377,
    height: 863,
    format: "png",
    relatedComponents: ["DocumentsCard", "PageHeader"],
  },
  {
    id: "template-error-to-be",
    name: "Error to be",
    sourcePath: "screenshots/Error to be.png",
    imageSrc: screenshotUrl("Error to be.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-generate-token",
    name: "Generate Token",
    sourcePath: "screenshots/Generate Token.png",
    imageSrc: screenshotUrl("Generate Token.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "TextField"],
  },
  {
    id: "template-homepage",
    name: "Homepage",
    sourcePath: "screenshots/homepage.png",
    imageSrc: screenshotUrl("homepage.png"),
    width: 750,
    height: 1624,
    format: "png",
    relatedComponents: ["HomeHeader", "AccountSummary", "BottomNavigation"],
  },
  {
    id: "template-informative",
    name: "Informative",
    sourcePath: "screenshots/Informative.png",
    imageSrc: screenshotUrl("Informative.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-language-selection",
    name: "Language Selection",
    sourcePath: "screenshots/Language Selection.png",
    imageSrc: screenshotUrl("Language Selection.png"),
    width: 375,
    height: 812,
    format: "png",
    relatedComponents: ["LanguageSelectorButton", "RadioButton", "PageHeader"],
  },
  {
    id: "template-message",
    name: "Message",
    sourcePath: "screenshots/Message.png",
    imageSrc: screenshotUrl("Message.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PageHeader"],
  },
  {
    id: "template-new-request-with-push",
    name: "New request with push",
    sourcePath: "screenshots/New request with push.png",
    imageSrc: screenshotUrl("New request with push.png"),
    width: 377,
    height: 871,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-panel",
    name: "Panel",
    sourcePath: "screenshots/Panel.png",
    imageSrc: screenshotUrl("Panel.png"),
    width: 375,
    height: 809,
    format: "png",
    relatedComponents: ["PanelWithTranslations", "PanelWithoutCoAppingTranslations"],
  },
  {
    id: "template-payment",
    name: "Payment",
    sourcePath: "screenshots/Payment.png",
    imageSrc: screenshotUrl("Payment.png"),
    width: 375,
    height: 1378,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "TextField", "PrimaryButton"],
  },
  {
    id: "template-pending",
    name: "Pending",
    sourcePath: "screenshots/Pending.png",
    imageSrc: screenshotUrl("Pending.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-product-selection",
    name: "Product selection",
    sourcePath: "screenshots/Product selection.jpg",
    imageSrc: screenshotUrl("Product selection.jpg"),
    width: 377,
    height: 814,
    format: "jpg",
    relatedComponents: ["ProductAccordion", "ProductAccordionAnimated"],
  },
  {
    id: "template-product",
    name: "Product",
    sourcePath: "screenshots/Product.png",
    imageSrc: screenshotUrl("Product.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["ProductsScreen", "ProductMenuCard", "BottomNavigation"],
  },
  {
    id: "template-review-request",
    name: "Review request",
    sourcePath: "screenshots/Review request.png",
    imageSrc: screenshotUrl("Review request.png"),
    width: 377,
    height: 1281,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-review",
    name: "Review",
    sourcePath: "screenshots/Review.png",
    imageSrc: screenshotUrl("Review.png"),
    width: 375,
    height: 1077,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "PrimaryButton"],
  },
  {
    id: "template-rs-travel-insurance",
    name: "RS - Travel Insurance",
    sourcePath: "screenshots/RS - Travel Insurance.png",
    imageSrc: screenshotUrl("RS - Travel Insurance.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["ProductMenuCard", "PrimaryButton"],
  },
  {
    id: "template-settings",
    name: "Settings",
    sourcePath: "screenshots/Settings.png",
    imageSrc: screenshotUrl("Settings.png"),
    width: 754,
    height: 1628,
    format: "png",
    relatedComponents: ["SettingsCard", "PageHeader"],
  },
  {
    id: "template-success-to-be",
    name: "Success to be",
    sourcePath: "screenshots/Success to be.png",
    imageSrc: screenshotUrl("Success to be.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
  {
    id: "template-transaction-detail",
    name: "Transaction detail",
    sourcePath: "screenshots/Transaction detail.png",
    imageSrc: screenshotUrl("Transaction detail.png"),
    width: 375,
    height: 1855,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "AccountTransactionRow", "PageHeader"],
  },
  {
    id: "template-transfer-to-new-phone",
    name: "Transfer to new phone",
    sourcePath: "screenshots/Transfer to new phone.png",
    imageSrc: screenshotUrl("Transfer to new phone.png"),
    width: 375,
    height: 812,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "PrimaryButton"],
  },
  {
    id: "template-tutorial-1",
    name: "Tutorial 1",
    sourcePath: "screenshots/Tutorial 1.png",
    imageSrc: screenshotUrl("Tutorial 1.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TutorialCard", "PrimaryButton"],
  },
  {
    id: "template-warning-to-be",
    name: "Warning to be",
    sourcePath: "screenshots/Warning to be.png",
    imageSrc: screenshotUrl("Warning to be.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader"],
  },
];
