import type { TemplateCodePreviewId } from "@/app/components/templates/TemplateCodePreviews";

export type TemplateRegistryItem = {
  id: string;
  name: string;
  sourcePath: string;
  imageSrc?: string;
  width: number;
  height: number;
  format: "png" | "jpg" | "code";
  sourceKind?: "screenshot" | "code-only";
  relatedComponents: string[];
  codePreviewId?: TemplateCodePreviewId;
  implementationPath?: string;
  implementationStatus?: "source-only" | "reconstructed-code";
  reuseNotes?: string[];
};

const screenshotUrl = (fileName: string) => new URL(`../../../screenshots/${fileName}`, import.meta.url).href;

export const TEMPLATE_REGISTRY: TemplateRegistryItem[] = [
  {
    id: "template-52",
    name: "52",
    sourcePath: "screenshots/52.png",
    imageSrc: screenshotUrl("52.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["MessagesScreen", "TemplateCodePreview", "AccountSearchBar", "AppIcon"],
    codePreviewId: "messages-inbox",
    implementationPath: "src/app/screens/messages/MessagesScreen.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "The runtime Messages screen is reconstructed from this template and uses the same country-addressable message config as the Design System preview.",
      "Reuses the account search bar, AppIcon header actions, two-tab bar, date/message row, new badge, and dot-menu patterns.",
      "The screenshot remains source evidence; the Design System preview renders reconstructed JSX while the header Messages icon opens the runtime screen.",
    ],
  },
  {
    id: "template-67",
    name: "67",
    sourcePath: "screenshots/67.png",
    imageSrc: screenshotUrl("67.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "AccountSearchBar", "AppIcon"],
    codePreviewId: "recurrent-payment",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Shares the same phone surface, header, tab bar, search strip, section title, and dot-menu primitives with template 52.",
      "The standing-order row is data-driven, so further payment-list templates can reuse the same shape.",
    ],
  },
  {
    id: "template-account-options",
    name: "Account options",
    sourcePath: "screenshots/account-options.png",
    imageSrc: screenshotUrl("account-options.png"),
    width: 375,
    height: 1038,
    format: "png",
    relatedComponents: ["AccountOptionsScreen", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "account-options",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the account options list and product recommendation cards as JSX using the same account-details data already used by the runtime AccountOptionsScreen.",
      "Introduces reusable account-option icon mapping and product promo card composition for follow-up account option flows.",
    ],
  },
  {
    id: "template-activate-mtoken",
    name: "Activate mToken",
    sourcePath: "screenshots/Activate mToken.jpg",
    imageSrc: screenshotUrl("Activate mToken.jpg"),
    width: 754,
    height: 1628,
    format: "jpg",
    relatedComponents: ["PreLoginActiveScreen", "TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "activate-mtoken",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Activate Mobile Token choice screen with shared top chrome, radio option rows, CSS hero art, and fixed Start CTA.",
      "Shares the same radio-row primitive with Generate Token, Product selection, and account-selection panel templates.",
    ],
  },
  {
    id: "template-analytics",
    name: "Analytics",
    sourcePath: "screenshots/Analytics.jpg",
    imageSrc: screenshotUrl("Analytics.jpg"),
    width: 754,
    height: 1628,
    format: "jpg",
    relatedComponents: ["BottomNavigation", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "analytics-overview",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the My Spendings analytics overview with code-native chart bars, add-cash banner, money-out summary, and five-item bottom navigation.",
      "Creates reusable chart and five-tab navigation primitives for future analytics templates.",
    ],
  },
  {
    id: "template-apple-pay",
    name: "Apple pay",
    sourcePath: "screenshots/Apple pay.png",
    imageSrc: screenshotUrl("Apple pay.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "apple-pay-activation",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Apple Pay activation screen as JSX with close action, card/device hero, explanatory copy, fixed bottom CTA, and home indicator.",
      "The hero is code-native CSS composition so this template can be reused without embedding the PNG as the implementation surface.",
    ],
  },
  {
    id: "template-cards",
    name: "Cards",
    sourcePath: "screenshots/Cards.jpg",
    imageSrc: screenshotUrl("Cards.jpg"),
    width: 754,
    height: 1996,
    format: "jpg",
    relatedComponents: ["ProductCard", "ProductsList", "BottomNavigation", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "cards-overview",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Cards overview as JSX with a generated debit-card surface, free-to-spend balance, wallet actions, shortcuts, search, transaction rows, and bottom navigation.",
      "Shares shortcut and transaction-row primitives with account detail and transaction detail templates.",
    ],
  },
  {
    id: "template-contact",
    name: "Contact",
    sourcePath: "screenshots/Contact.png",
    imageSrc: screenshotUrl("Contact.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["ContactsDivider", "ContactsNavigationCard", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "contact-info-sheet",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the contact information bottom sheet with a dark backdrop, close action, and reusable contact action cards.",
      "Uses existing contact iconography so support/contact sheet flows can be composed without screenshot assets.",
    ],
  },
  {
    id: "template-documents",
    name: "Documents",
    sourcePath: "screenshots/Documents.png",
    imageSrc: screenshotUrl("Documents.png"),
    width: 377,
    height: 863,
    format: "png",
    relatedComponents: ["DocumentsScreen", "PageHeader", "AccountSearchBar"],
    codePreviewId: "documents",
    implementationPath: "src/app/screens/documents/DocumentsScreen.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Documents list as the same family as Messages, reusing the shared header and search treatment but removing the mailbox tabs and per-row dot menu.",
      "The More > Documents runtime screen and the Design System Template preview both read the same `documentsConfig.ts` grouped-list data.",
    ],
  },
  {
    id: "template-error-to-be",
    name: "Error to be",
    sourcePath: "screenshots/Error to be.png",
    imageSrc: screenshotUrl("Error to be.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "error-status",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Shares the feedback status screen primitive with Informative, Pending, Success, and Warning templates.",
      "Reconstructs the title, help action, red status icon, lorem copy block, and fixed bottom CTA as JSX.",
    ],
  },
  {
    id: "template-generate-token",
    name: "Generate Token",
    sourcePath: "screenshots/Generate Token.png",
    imageSrc: screenshotUrl("Generate Token.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "generate-token",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the token-generation screen with logout/help chrome, token panel, reusable radio option rows, and bottom Generate CTA.",
      "Shares radio-row and CTA primitives with Product selection and account-selection panel templates.",
    ],
  },
  {
    id: "template-homepage",
    name: "Homepage",
    sourcePath: "screenshots/homepage.png",
    imageSrc: screenshotUrl("homepage.png"),
    width: 750,
    height: 1624,
    format: "png",
    relatedComponents: ["HomeHeader", "AccountSummary", "BottomNavigation", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "account-detail-homepage",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "The source filename is `homepage`, but the screenshot content is an account-detail home screen; the registry maps it to the reconstructed account-detail homepage preview.",
      "Reuses account balance card, shortcut, search, transaction-list, and five-item bottom navigation patterns for future account flows.",
    ],
  },
  {
    id: "template-informative",
    name: "Informative",
    sourcePath: "screenshots/Informative.png",
    imageSrc: screenshotUrl("Informative.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "informative-status",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Introduces a reusable feedback status screen primitive with help-only top chrome, centered status icon, body copy, and fixed bottom CTA.",
      "This variant renders the neutral informational icon and title while sharing layout with Pending, Success, Error, and Warning.",
    ],
  },
  {
    id: "template-language-selection",
    name: "Language Selection",
    sourcePath: "screenshots/Language Selection.png",
    imageSrc: screenshotUrl("Language Selection.png"),
    width: 375,
    height: 812,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "sign-pin",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "The source filename is `Language Selection`, but the screenshot content is a Sign/PIN screen; the registry maps it to the reconstructed sign-pin code preview.",
      "Reuses the shared phone surface, back chrome, PIN input line treatment, fixed bottom CTA, and home indicator.",
    ],
  },
  {
    id: "template-message",
    name: "Message",
    sourcePath: "screenshots/Message.png",
    imageSrc: screenshotUrl("Message.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "message-detail",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the message detail layout with back chrome, title/date, media placeholder, body copy, primary CTA, and link action.",
      "Complements template 52 by covering the detail-side message pattern without introducing a runtime detail screen yet.",
    ],
  },
  {
    id: "template-new-request-with-push",
    name: "New request with push",
    sourcePath: "screenshots/New request with push.png",
    imageSrc: screenshotUrl("New request with push.png"),
    width: 377,
    height: 871,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "push-request-form",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the request-with-push form as sectioned JSX fields with payer, account, and payment-information blocks.",
      "Adds a shared field-line primitive that can be reused by future review/payment form templates.",
    ],
  },
  {
    id: "template-panel",
    name: "Panel",
    sourcePath: "screenshots/Panel.png",
    imageSrc: screenshotUrl("Panel.png"),
    width: 375,
    height: 809,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "account-selection-panel",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the account-selection bottom sheet with dark backdrop, sheet header/close action, radio account rows, and Select CTA.",
      "Shares the same radio option row primitive with Generate Token and Product selection.",
    ],
  },
  {
    id: "template-payment",
    name: "Payment",
    sourcePath: "screenshots/Payment.png",
    imageSrc: screenshotUrl("Payment.png"),
    width: 375,
    height: 1378,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "TextField", "PrimaryButton", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "domestic-payment-form",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Domestic payment entry form with section headers, flow fields, camera/dropdown affordances, instant-payment toggle, and fixed Next CTA.",
      "The shared flow-field primitive is reused by payment review templates and can seed future payment form variants.",
    ],
  },
  {
    id: "template-pending",
    name: "Pending",
    sourcePath: "screenshots/Pending.png",
    imageSrc: screenshotUrl("Pending.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "pending-status",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Shares the feedback status screen primitive with Informative, Success, Error, and Warning templates.",
      "Reconstructs the neutral pending/hourglass status treatment, lorem copy block, and fixed bottom CTA as JSX.",
    ],
  },
  {
    id: "template-product-selection",
    name: "Product selection",
    sourcePath: "screenshots/Product selection.jpg",
    imageSrc: screenshotUrl("Product selection.jpg"),
    width: 377,
    height: 814,
    format: "jpg",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "product-selection",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the product-selection screen with radio rows, default-product toggle, Access CTA, and bottom navigation.",
      "Uses shared radio and mini bottom-navigation primitives so future product picker flows can reuse the layout.",
    ],
  },
  {
    id: "template-product",
    name: "Product",
    sourcePath: "screenshots/Product.png",
    imageSrc: screenshotUrl("Product.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "product-bottom-sheet",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the product bottom-sheet as JSX with real typography, overlay, close action, media placeholder, body copy, and reusable PrimaryButton.",
      "Useful as a reusable product-detail sheet foundation instead of a static screenshot card.",
    ],
  },
  {
    id: "template-review-request",
    name: "Review request",
    sourcePath: "screenshots/Review request.png",
    imageSrc: screenshotUrl("Review request.png"),
    width: 377,
    height: 1281,
    format: "png",
    relatedComponents: ["PrimaryButton", "PageHeader", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "review-request",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Review request confirmation screen with payer, account, and payment-information sections rendered as read-only rows.",
      "Shares the read-only row and section-title primitives with Review data and Transaction detail templates.",
    ],
  },
  {
    id: "template-review",
    name: "Review",
    sourcePath: "screenshots/Review.png",
    imageSrc: screenshotUrl("Review.png"),
    width: 375,
    height: 1077,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "PrimaryButton", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "review-data",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Review data payment-order screen with a read-only payment summary, Save as template toggle, and fixed Sign CTA.",
      "Extends the payment-flow template family without embedding the source PNG as the implementation.",
    ],
  },
  {
    id: "template-rs-travel-insurance",
    name: "RS - Travel Insurance",
    sourcePath: "screenshots/RS - Travel Insurance.png",
    imageSrc: screenshotUrl("RS - Travel Insurance.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "travel-insurance-detail",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the travel-insurance detail screen with back/help chrome, code-native travel hero scene, body copy, and fixed Proceed CTA.",
      "Keeps the screenshot as source evidence while avoiding a screenshot-as-implementation PNG dependency.",
    ],
  },
  {
    id: "template-settings",
    name: "Settings",
    sourcePath: "screenshots/Settings.png",
    imageSrc: screenshotUrl("Settings.png"),
    width: 754,
    height: 1628,
    format: "png",
    relatedComponents: ["SettingsScreen", "PageHeader", "SectionHeadingDivider", "AppIcon"],
    codePreviewId: "settings",
    implementationPath: "src/app/screens/settings/SettingsScreen.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the Settings screen as a shared PageHeader plus section-heading/divider and chevron-list rows driven by a common settings config.",
      "The More > Settings runtime screen and the Design System Template preview both read the same `settingsConfig.ts` section data so copy and structure stay aligned.",
    ],
  },
  {
    id: "template-success-to-be",
    name: "Success to be",
    sourcePath: "screenshots/Success to be.png",
    imageSrc: screenshotUrl("Success to be.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "success-status",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Shares the feedback status screen primitive with Informative, Pending, Error, and Warning templates.",
      "Reconstructs the green success icon, `Successfully requested` title, lorem copy block, and fixed bottom CTA as JSX.",
    ],
  },
  {
    id: "template-transaction-detail",
    name: "Transaction detail",
    sourcePath: "screenshots/Transaction detail.png",
    imageSrc: screenshotUrl("Transaction detail.png"),
    width: 375,
    height: 1855,
    format: "png",
    relatedComponents: ["DomesticPaymentFlowScreens", "AccountTransactionRow", "PageHeader", "TemplateCodePreview", "AppIcon"],
    codePreviewId: "transaction-detail",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the transaction detail screen with merchant summary, action shortcuts, spending insight chart, copyable details, and Show less action.",
      "Reuses read-only detail rows and shortcut primitives already introduced for payment/account templates.",
    ],
  },
  {
    id: "template-transfer-to-new-phone",
    name: "Transfer to new phone",
    sourcePath: "screenshots/Transfer to new phone.png",
    imageSrc: screenshotUrl("Transfer to new phone.png"),
    width: 375,
    height: 812,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "DomesticPaymentFlowScreens", "PrimaryButton", "AppIcon"],
    codePreviewId: "successful-payment",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "The source filename is `Transfer to new phone`, but the screenshot content is a Successful payment screen; the registry maps it to a success-payment code preview.",
      "Reuses the same success icon and bottom CTA pattern as the Domestic payment success runtime screen.",
    ],
  },
  {
    id: "template-tutorial-1",
    name: "Tutorial 1",
    sourcePath: "screenshots/Tutorial 1.png",
    imageSrc: screenshotUrl("Tutorial 1.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "TutorialCard", "AppIcon"],
    codePreviewId: "tutorial-intro",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Reconstructs the tutorial/webview intro with loading chrome, progress bar, device media area, playback controls, carousel dots, and skip/back/next actions.",
      "Adds a reusable webview/tutorial composition pattern for future onboarding templates.",
    ],
  },
  {
    id: "template-warning-to-be",
    name: "Warning to be",
    sourcePath: "screenshots/Warning to be.png",
    imageSrc: screenshotUrl("Warning to be.png"),
    width: 377,
    height: 814,
    format: "png",
    relatedComponents: ["TemplateCodePreview", "PrimaryButton", "AppIcon"],
    codePreviewId: "warning-status",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Shares the feedback status screen primitive with Informative, Pending, Success, and Error templates.",
      "Reconstructs the orange warning/bell status icon, lorem copy block, and fixed bottom CTA as JSX.",
    ],
  },
  {
    id: "template-home-dashboard-code",
    name: "Home dashboard",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::home-dashboard",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["HomeHeader", "AccountSummary", "AccountSearchBar", "BottomNavigation", "AppIcon"],
    codePreviewId: "home-dashboard",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template derived from the active Home/account summary family, so it can seed future dashboard flows without a PNG source.",
      "Reuses the top header action rail, account balance card, shortcut pattern, transaction rows, product cards, and bottom navigation primitives.",
    ],
  },
  {
    id: "template-payments-menu-code",
    name: "Payments menu",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::payments-menu",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["PaymentsScreen", "PaymentOtherShortcut", "BottomNavigation", "AppIcon"],
    codePreviewId: "payments-menu",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template based on the runtime Payments menu and country-scoped payments config.",
      "Reuses the Payments hero card family, OTHER shortcut carousel items, header actions, and five-tab bottom navigation.",
    ],
  },
  {
    id: "template-new-payment-sheet-code",
    name: "New payment sheet",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::new-payment-sheet",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["BottomSheet", "NewPaymentActionListItem", "NewPaymentDiscoverBanner", "AppIcon"],
    codePreviewId: "new-payment-sheet",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the Payments New payment bottom sheet using the same action rows and discover banner as the runtime sheet.",
      "Keeps the corrected 16px sheet padding and 4px discover-banner title/subtitle spacing visible in the reusable template grid.",
    ],
  },
  {
    id: "template-products-menu-code",
    name: "Products menu",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::products-menu",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["ProductsScreen", "ProductOfferCard", "ProductMenuCard", "BottomNavigation"],
    codePreviewId: "products-menu",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template derived from the Products runtime menu and products config.",
      "Reuses the segmented Banking/ShopSmart treatment, Products offer card, product card grid, and bottom navigation.",
    ],
  },
  {
    id: "template-more-menu-code",
    name: "More menu",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::more-menu",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["MoreScreen", "BottomNavigation", "AppIcon"],
    codePreviewId: "more-menu",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template derived from the country-aware More card matrix.",
      "Reuses the top-level header, More card row composition, icon registry, and five-tab bottom navigation.",
    ],
  },
  {
    id: "template-contacts-directory-code",
    name: "Contacts directory",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::contacts-directory",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["ContactsScreen", "ContactsNavigationCard", "AccountSearchBar", "AppIcon"],
    codePreviewId: "contacts-directory",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for a full Contacts directory surface, complementing the existing contact bottom-sheet screenshot template.",
      "Reuses the search strip, section divider, contact action cards, and centralized contact icons.",
    ],
  },
  {
    id: "template-account-details-info-code",
    name: "Account details info",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::account-details-info",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["AccountDetailsInfoScreen", "AccountDetailsInfoField", "AppIcon"],
    codePreviewId: "account-details-info",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the account-details information family, using the same account card, read-only rows, copy affordance, and share action.",
      "Complements the existing account options and account-detail homepage templates for account flow assembly.",
    ],
  },
  {
    id: "template-messages-outbox-code",
    name: "Messages outbox",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::messages-outbox",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["MessagesScreen", "AccountSearchBar", "AppIcon"],
    codePreviewId: "messages-outbox",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only mailbox variant that reuses the template 52 Messages family but selects Outbox data from messagesConfig.",
      "Gives future prompt-driven flows both inbox and sent-message list patterns without needing an extra PNG.",
    ],
  },
  {
    id: "template-prime-advisor-code",
    name: "Prime advisor",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::prime-advisor",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["PrimeScreen", "YourAdvisorTab", "PrimaryButton", "AppIcon"],
    codePreviewId: "prime-advisor",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the Prime advisor contact pattern.",
      "Reuses top chrome, advisor summary card, read-only contact rows, copy affordances, and a fixed bottom CTA.",
    ],
  },
  {
    id: "template-prime-benefits-code",
    name: "Prime benefits",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::prime-benefits",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["PrimeScreen", "YourBenefitsTab", "PrimaryButton", "AppIcon"],
    codePreviewId: "prime-benefits",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for Prime benefits and premium-service storytelling.",
      "Reuses the status/card + checklist composition so Prime prompts can be built from known screen parts instead of invented cards.",
    ],
  },
  {
    id: "template-prelogin-inactive-code",
    name: "Prelogin inactive",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::prelogin-inactive",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["PreLoginScreen", "UniCreditLogo", "PrimaryButton", "AppIcon"],
    codePreviewId: "prelogin-inactive",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the inactive pre-login activation surface, including logo/language header, product teaser rows, CTA, and bottom utility links.",
      "Uses code-native background/card art rather than a PNG so pre-login prompt flows can reuse the layout vocabulary.",
    ],
  },
  {
    id: "template-prelogin-active-code",
    name: "Prelogin active",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::prelogin-active",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["PreLoginActiveScreen", "UniCreditLogo", "PrimaryButton", "AppIcon"],
    codePreviewId: "prelogin-active",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the active app login posture with title/subtitle, login CTA, language selector, and utility-link row.",
      "Complements the Home dashboard templates with the actual entry-state pattern used before authenticated navigation.",
    ],
  },
  {
    id: "template-language-selector-sheet-code",
    name: "Language selector sheet",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::language-selector-sheet",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["LanguageSelector", "RadioButton", "PrimaryButton", "AppIcon"],
    codePreviewId: "language-selector-sheet",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the pre-login language selection modal pattern over the inactive background.",
      "Reuses the same radio-row primitive family used by token, product-selection, and account-selection templates.",
    ],
  },
  {
    id: "template-more-panel-menu-code",
    name: "Other panel menu",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::more-panel-menu",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["PanelWithTranslations", "PanelOverlay", "AppIcon"],
    codePreviewId: "more-panel-menu",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the dark pre-login Other panel using the actual translated panel component.",
      "Keeps smart banking, exchange rates, ATM/branches, and Co-Apping entry as reusable row patterns.",
    ],
  },
  {
    id: "template-co-apping-session-code",
    name: "Co-Apping session",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::co-apping-session",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["CoAppingSessionScreen", "TextField", "PrimaryButton", "AppIcon"],
    codePreviewId: "co-apping-session",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the Co-Apping code-entry screen with hero art, explanatory copy, reusable TextField, privacy helper, and fixed Continue CTA.",
      "Supports future assistant-built support/session flows without inventing a new form pattern.",
    ],
  },
  {
    id: "template-account-transactions-list-code",
    name: "Account transactions list",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::account-transactions-list",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["AccountDetailScreen", "AccountSearchBar", "AccountTransactionRow", "AppIcon"],
    codePreviewId: "account-transactions-list",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only account transaction list template with account card, search strip, month divider, and transaction rows.",
      "Complements the account-detail homepage screenshot template with a denser list-first state for prompt-built account flows.",
    ],
  },
  {
    id: "template-account-search-results-code",
    name: "Account search results",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::account-search-results",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["AccountSearchBar", "AccountTransactionRow", "AppIcon"],
    codePreviewId: "account-search-results",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the transaction-search results state, including active query, clear affordance, result count, filtered rows, and clear-results action.",
      "Makes the search-result state available as a reusable prompt target instead of only an interaction inside the runtime screen.",
    ],
  },
  {
    id: "template-spending-money-out-code",
    name: "Spending money out",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::spending-money-out",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["AnalyticsScreen", "SectionHeadingDivider", "BottomNavigation", "AppIcon"],
    codePreviewId: "spending-money-out",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only Spending category breakdown template with total card, bar chart, category rows, and proportional row bars.",
      "Extends the Analytics screenshot template with a reusable money-out category state for future PFM prompts.",
    ],
  },
  {
    id: "template-products-shopsmart-code",
    name: "Products ShopSmart",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::products-shopsmart",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["ProductsScreen", "ProductOfferCard", "ProductMenuCard", "BottomNavigation"],
    codePreviewId: "products-shopsmart",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the ShopSmart tab state using the products menu config, ProductOfferCard, and ProductMenuCard grid.",
      "Complements the Banking products template so the tabbed Products family has both reusable states.",
    ],
  },
  {
    id: "template-logout-confirmation-code",
    name: "Logout confirmation",
    sourcePath: "src/app/components/templates/TemplateCodePreviews.tsx::logout-confirmation",
    width: 377,
    height: 814,
    format: "code",
    sourceKind: "code-only",
    relatedComponents: ["LogoutConfirmDialog", "MoreScreen", "AppIcon"],
    codePreviewId: "logout-confirmation",
    implementationPath: "src/app/components/templates/TemplateCodePreviews.tsx",
    implementationStatus: "reconstructed-code",
    reuseNotes: [
      "Code-only template for the iOS-style logout confirmation overlay over the More surface.",
      "Reuses the actual LogoutConfirmDialog component so destructive/confirmation prompts stay visually consistent.",
    ],
  },
];
