import type { ComponentId } from '@/app/state/demoTypes'
import type { ComponentMeta } from '../contracts'

export const FOUNDATION_COMPONENTS = {
  'shell.mobile-frame': {
    id: 'shell.mobile-frame',
    label: 'Mobile frame',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/MobileFrame.tsx',
    usedByScreens: [
      'pi.prelogin.inactive',
      'pi.prelogin.active',
      'pi.co-apping.session',
      'pi.home.overview',
      'pi.analytics.overview',
      'pi.messages.overview',
      'pi.account.detail',
      'pi.account.details-info',
      'pi.account.options',
      'pi.transaction.detail',
      'pi.payments.overview',
      'pi.payment.domestic-create',
      'pi.payment.review',
      'pi.payment.sign',
      'pi.payment.success',
      'pi.investments.portfolio',
      'pi.products.overview',
      'pi.products.detail',
      'pi.prime.overview',
      'pi.more.overview',
      'pi.contacts.overview',
      'kids.sk.home-concept',
      'kids.hu.home-concept',
    ],
  },
  'shell.phone-screenshot-control': {
    id: 'shell.phone-screenshot-control',
    label: 'Phone screenshot control',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/demo/PhoneScreenshotControl.tsx',
    usedByScreens: [
      'pi.prelogin.inactive',
      'pi.prelogin.active',
      'pi.co-apping.session',
      'pi.home.overview',
      'pi.analytics.overview',
      'pi.messages.overview',
      'pi.account.detail',
      'pi.account.details-info',
      'pi.account.options',
      'pi.transaction.detail',
      'pi.payments.overview',
      'pi.payment.domestic-create',
      'pi.payment.review',
      'pi.payment.sign',
      'pi.payment.success',
      'pi.investments.portfolio',
      'pi.products.overview',
      'pi.prime.overview',
      'pi.more.overview',
      'pi.documents.overview',
      'pi.settings.overview',
      'pi.contacts.overview',
    ],
    notes:
      'Desktop demo-shell header control rendered as an icon-only camera dropdown immediately after the Control Panel/Settings button. Dropdown exports visible/full-height PNG captures and Figma-ready `build-ui.screen.v1` JSON via `Generate visible JSON` and `Generate entire screen JSON`; JSON is generated from an unscaled app-content clone and includes app background, numeric bounds, Figma paints/effects/text specs, assets, text safety width, cleaner fallback layer names, and conservative Auto Layout intent. Design System Inventory keeps the control visible but disabled.',
  },
  'shell.page-header': {
    id: 'shell.page-header',
    label: 'Page header',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/PageHeader.tsx',
    usedByScreens: [
      'pi.messages.overview',
      'pi.account.detail',
      'pi.account.details-info',
      'pi.account.options',
      'pi.transaction.detail',
      'pi.payment.domestic-create',
      'pi.payment.review',
      'pi.payment.sign',
      'pi.payment.success',
      'pi.documents.overview',
      'pi.settings.overview',
      'pi.contacts.overview',
      'pi.investments.portfolio',
      'pi.products.detail',
    ],
    notes: 'Shared top-page header family used by runtime detail/list screens and reconstructed templates.',
  },
  'shell.bottom-navigation': {
    id: 'shell.bottom-navigation',
    label: 'Bottom navigation',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/BottomNavigation.tsx',
    usedByScreens: [
      'pi.home.overview',
      'pi.analytics.overview',
      'pi.payments.overview',
      'pi.products.overview',
      'pi.more.overview',
    ],
    notes:
      'Fixed 375x54 bottom bar contract with 24px side padding, 32px icon slots, 24x2 active bar touching the icon slot, and 14px labels with 15px line-height and no icon/label gap.',
  },
  'shell.bottom-sheet': {
    id: 'shell.bottom-sheet',
    label: 'Bottom sheet shell',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/BottomSheet.tsx',
    usedByScreens: ['pi.payments.overview', 'pi.products.overview'],
    notes:
      'Reusable overlay and rounded bottom panel shell for modal quick menus, with 16px uniform sheet padding. Products uses it for the OUR PRODUCTS category option sheet before opening product detail pages.',
  },
  'shell.status-bar': {
    id: 'shell.status-bar',
    label: 'Status bar',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/StatusBar.tsx',
    usedByScreens: [
      'pi.prelogin.inactive',
      'pi.prelogin.active',
      'pi.co-apping.session',
      'pi.home.overview',
      'pi.analytics.overview',
      'pi.messages.overview',
      'pi.account.detail',
      'pi.account.details-info',
      'pi.account.options',
      'pi.transaction.detail',
      'pi.payments.overview',
      'pi.payment.domestic-create',
      'pi.payment.review',
      'pi.payment.sign',
      'pi.payment.success',
      'pi.investments.portfolio',
      'pi.products.overview',
      'pi.prime.overview',
      'pi.more.overview',
      'pi.contacts.overview',
      'kids.sk.home-concept',
      'kids.hu.home-concept',
    ],
    notes:
      'Absolute, pointer-events-none overlay rendering the simulated iOS clock plus cellular/wifi/battery glyphs at the top of the phone frame. Foreground color follows the light/dark/theme variant and Co-Apping active tone.',
  },
  'shell.home-header': {
    id: 'shell.home-header',
    label: 'Home header',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/screens/home/HomeHeader.tsx',
    usedByScreens: ['pi.home.overview'],
    notes: 'Home screen top bar with the UniCredit mark, Prime entry, and Messages icon with unread badge.',
  },
  'shell.more-header': {
    id: 'shell.more-header',
    label: 'More header',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/screens/more/MoreHeader.tsx',
    usedByScreens: ['pi.more.overview'],
    notes: 'More screen top bar with profile initials avatar, Messages icon with unread count, and Logout action.',
  },
  'icons.app-icon': {
    id: 'icons.app-icon',
    label: 'App icon registry',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/icons/AppIcon.tsx',
    usedByScreens: [
      'pi.prelogin.inactive',
      'pi.prelogin.active',
      'pi.co-apping.session',
      'pi.home.overview',
      'pi.analytics.overview',
      'pi.messages.overview',
      'pi.account.detail',
      'pi.account.details-info',
      'pi.account.options',
      'pi.transaction.detail',
      'pi.payments.overview',
      'pi.payment.domestic-create',
      'pi.payment.review',
      'pi.payment.sign',
      'pi.payment.success',
      'pi.investments.portfolio',
      'pi.products.overview',
      'pi.prime.overview',
      'pi.more.overview',
      'pi.documents.overview',
      'pi.settings.overview',
      'pi.contacts.overview',
      'platform.design-system',
    ],
    notes:
      'Central source for reusable UI icons; templates and runtime screens should reference icons through this registry rather than direct lucide or raw SVG usage.',
  },
  'brand.unicredit-logo': {
    id: 'brand.unicredit-logo',
    label: 'UniCredit logo',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/UniCreditLogo.tsx',
    usedByScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
  },
  'ui.primary-button': {
    id: 'ui.primary-button',
    label: 'Primary button',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/PrimaryButton.tsx',
    usedByScreens: [
      'pi.prelogin.inactive',
      'pi.prelogin.active',
      'pi.co-apping.session',
      'pi.payment.domestic-create',
      'pi.payment.review',
      'pi.payment.sign',
      'pi.payment.success',
      'pi.products.detail',
      'pi.prime.overview',
      'platform.design-system',
    ],
  },
  'ui.text-field': {
    id: 'ui.text-field',
    label: 'Text field',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/TextField.tsx',
    usedByScreens: ['pi.co-apping.session', 'pi.payment.domestic-create', 'pi.payment.sign', 'platform.design-system'],
  },
  'ui.amount-field': {
    id: 'ui.amount-field',
    label: 'Amount field',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/AmountField.tsx',
    usedByScreens: ['pi.payment.domestic-create', 'platform.design-system'],
    notes:
      'Amount input variant with the same visual states as Text field plus a 24px-spaced currency selector column, 14px currency label, 18px currency value, and 32x32 trailing chevron with zero currency-to-chevron gap.',
  },
  'ui.link-button': {
    id: 'ui.link-button',
    label: 'Link button',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/LinkButton.tsx',
    usedByScreens: ['kids.hu.home-concept', 'platform.design-system'],
    notes:
      'Reusable text action with chevron-link accessory: centered flex w-fit button, zero text-to-chevron gap, 13px bold uppercase label with 16px line-height, 24px chevron icon, current action color, and focus-visible ring.',
  },
  'ui.pill': {
    id: 'ui.pill',
    label: 'Pill',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/Pill.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Meniga-normalized pill button from Figma node `1057:21187`: 120x36, 18px radius, 8px horizontal padding, N5 14px bold centered label, 0 2 2 shadow, primary teal surface, white secondary/counter/loading/activated surfaces, 16px loading/success icons, and 8px icon-label gap.',
  },
  'ui.wallet-button': {
    id: 'ui.wallet-button',
    label: 'Wallet buttons',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/WalletButton.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Meniga-normalized 48px wallet/payment button family from Figma nodes `7464:1768`, `7464:1858`, and `7464:1912`. Exposes Google Wallet, Apple Wallet, and Click to Pay states, condensed and 327px long sizes, plus Google EN/HU/SK/CZ copy variants. Uses local vector marks instead of expiring Figma MCP assets.',
  },
  'ui.bar': {
    id: 'ui.bar',
    label: 'Bar',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/Bar.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Meniga-normalized Bar primitive from Figma node `1058:22155`: 375x8 Empty, Full, Mid 1, Mid 2, and Small states with a 24px left inset and teal active fill, plus the 279x1 Thin status.',
  },
  'ui.date-filter': {
    id: 'ui.date-filter',
    label: 'Date filter',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/DateFilter.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Meniga-normalized Date filter from Figma node `290:14520`: 238x24 wrapper, 4-item and 5-item states, 15px gaps, 35x22 chips, 3.5px radius, 14px bold labels, and teal selected chip.',
  },
  'ui.pill-sorting': {
    id: 'ui.pill-sorting',
    label: 'Pill sorting',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/PillSorting.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Meniga-normalized Pill sorting rail from Figma node `290:14610`: 375x40 row, 8px gap, 24px chip height, 14.5px radius, 14px regular idle labels, and black selected chip with bold white label.',
  },
  'ui.code-field': {
    id: 'ui.code-field',
    label: 'Code field',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/CodeField.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Figma-normalized one-time-code field: 327px wrapper, centered 224px slot row, four 44x64 slots with 16px gap, 8px radius, 1px neutral/error border, N1 30px bold digits, numeric paste distribution, disabled/error states, aria-invalid messaging, and focus-visible ring.',
  },
  'ui.toast-message': {
    id: 'ui.toast-message',
    label: 'Toast message',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/ToastMessage.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Meniga-normalized Toast message family from Figma node `178:15386`: Action required light, Aware dark, and Google Pay dark states. The message capsule uses 16px radius, 14px bold UniCredit text, 327x32 icon variants with a 32px icon slot and centered 8px status-red dot, plus a 174x35 hug Google Pay confirmation variant.',
  },
  'ui.profile-avatar': {
    id: 'ui.profile-avatar',
    label: 'Profile avatar',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ProfileAvatar.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Figma-derived 40x40 avatar family with full-photo, inset-profile-photo plus optional 8px notification dot, dark K1 initials fallback, and AI gradient avatar variants. Supports real image sources and controlled sizing for nearby runtime uses.',
  },
  'ui.navigation-row': {
    id: 'ui.navigation-row',
    label: 'Navigation row',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/NavigationRow.tsx',
    usedByScreens: ['pi.settings.overview', 'pi.contacts.overview', 'platform.design-system'],
    notes:
      'Figma-derived Navigation row family now mapped to the Meniga additional-cases node `1515:1995`: 18 selector variants covering icon/no-icon/toggle/special rows, 64px and 80px heights, 32px leading visuals, 64x40 card art, centered text-message/CTA rows, 16px bold title, optional 16px description, 14px teal CTA link, chevron accessory, and shared 60x30 ToggleButton.',
  },
  'ui.toggle-button': {
    id: 'ui.toggle-button',
    label: 'Toggle button',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ToggleButton.tsx',
    usedByScreens: ['pi.payment.review', 'platform.design-system'],
    notes:
      'Figma-derived 60x30 switch-like control with explicit checked/unchecked states, white surface, 2px border, 22x22 knob, right-aligned teal success state, left-aligned gray off state, and accessible `role=switch` runtime behavior.',
  },
  'ui.radio-button': {
    id: 'ui.radio-button',
    label: 'Radio button',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/common/RadioButton.tsx',
    usedByScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
  },
  'ui.section-heading-divider': {
    id: 'ui.section-heading-divider',
    label: 'Divider',
    products: ['PI', 'KIDS_PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/SectionHeadingDivider.tsx',
    usedByScreens: [
      'pi.analytics.overview',
      'pi.payment.domestic-create',
      'pi.investments.portfolio',
      'pi.settings.overview',
      'pi.contacts.overview',
      'kids.hu.home-concept',
      'platform.design-system',
    ],
    notes:
      'Shared section/divider family now mapped to Meniga Divider node `1058:22303`: keeps the legacy runtime `section` API intact while exposing 13 explicit DS states for small/medium/large titles, title+data, counters, action/date, name/action, checkbox action/date, and Light Restyle title/date/small-data variants.',
  },
  'ui.language-selector-button': {
    id: 'ui.language-selector-button',
    label: 'Language selector button',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/LanguageSelectorButton.tsx',
    usedByScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
    notes:
      'Compact top-bar language toggle: right-aligned uppercase language code over a 1px underline, used on pre-login surfaces.',
  },
  'ui.navigation-link': {
    id: 'ui.navigation-link',
    label: 'Navigation link',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/NavigationLink.tsx',
    usedByScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
    notes: 'Dark-surface text link with a trailing chevron icon, used for pre-login find-out-more actions.',
  },
  'ui.prelogin-heading': {
    id: 'ui.prelogin-heading',
    label: 'Prelogin heading',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/PreLoginHeading.tsx',
    usedByScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
    notes:
      'Three-line white pre-login hero heading (38px bold H1, 24px bold H2, 18px regular H3) stacked with a 16px group gap and a 32px gap between H1 and H2.',
  },
  'ui.button-registry': {
    id: 'ui.button-registry',
    label: 'Button registry variants',
    products: ['PI', 'SME'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/ui/button.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Vendored shadcn/Radix Button primitive exposing default, secondary, outline, ghost, and destructive variants for generic (non-branded) call-to-action use, separate from the bespoke PrimaryButton.',
  },
  'ui.generic-controls': {
    id: 'ui.generic-controls',
    label: 'Generic UI controls',
    products: ['PI', 'SME'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath:
      'src/app/components/ui/button.tsx + badge.tsx + input.tsx + checkbox.tsx + toggle.tsx + toggle-group.tsx + slider.tsx + progress.tsx + separator.tsx + skeleton.tsx + alert.tsx + tabs.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Vendored shadcn/Radix primitive family (Button, Badge, Input, Checkbox, Toggle, Toggle group, Slider, Progress, Separator, Skeleton, Alert, Tabs) kept generic and separate from bespoke UniCredit components.',
  },
  'templates.reconstructed-code': {
    id: 'templates.reconstructed-code',
    label: 'Reconstructed code templates',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    usedByScreens: ['platform.design-system'],
    notes:
      'Renders 50 real JSX template previews: all 30 screenshot-backed templates plus 20 code-only templates derived from active pre-login, panel, Co-Apping, Home/account, Payments, Products, More, Contacts, Messages, Spending, Prime, and dialog patterns. Source PNG/JPG files remain comparison evidence where they exist.',
  },
  'dialogs.logout-confirmation': {
    id: 'dialogs.logout-confirmation',
    label: 'Logout confirmation dialog',
    products: ['PI'],
    designSystems: ['current'],
    status: 'implemented',
    componentPath: 'src/app/components/LogoutConfirmDialog.tsx',
    usedByScreens: ['pi.more.overview'],
    notes: 'Reusable confirmation overlay used by More and the code-only logout-confirmation template.',
  },
} satisfies Partial<Record<ComponentId, ComponentMeta>>
