/**
 * HU Kids seed data: quick actions, tasks, goals, learn topics, pending
 * actions, and the mock transaction ledger.
 *
 * Extracted verbatim from KidsMarketHomeApp.tsx (kids-split Phase 3).
 */
import type { IconName } from "@/app/components/icons";
import {
  HU_KIDS_GOALS,
  HU_KIDS_LEARN_MODULES,
  type LearnModule,
  type SavingGoal,
} from "@/data/huKidsBanking";
import type {
  HuKidsMenuShapeCountry,
  HuKidsRuntimeCountry,
  HuKidsTask,
  HuKidsTransaction,
  HuMoneyReason,
  HuPendingAction,
  HuSendContact,
} from "./types";

export const HU_KIDS_SIMPLIFIED_MENU_SHAPE_COUNTRY: HuKidsMenuShapeCountry = "BA";

export const HU_KIDS_RUNTIME_COUNTRY: HuKidsRuntimeCountry = "HU";

export const HU_KIDS_HIDDEN_PAYMENT_PRIMARY_IDS = new Set(["recurrent-payments"]);

export const HU_KIDS_HIDDEN_PAYMENT_OTHER_IDS = new Set(["card-repayment", "exchange-rates"]);

export const HU_LIGHT_ACTIONS: Array<{ id: "request" | "send" | "card" | "more"; label: string; icon: IconName }> = [
  { id: "request", label: "Request money", icon: "hu-kids-request-money" },
  { id: "send", label: "Send money", icon: "nav-payments" },
  { id: "card", label: "Account details", icon: "hu-kids-account-details" },
  { id: "more", label: "More Options", icon: "hu-kids-more-options" },
];

export const HU_SAVING_ACTIONS: Array<{ id: "save" | "request" | "card" | "more"; label: string; icon: IconName }> = [
  { id: "save", label: "Save money", icon: "hu-kids-saving" },
  { id: "request", label: "Request money", icon: "hu-kids-request-money" },
  { id: "card", label: "Account details", icon: "hu-kids-account-details" },
  { id: "more", label: "More Options", icon: "hu-kids-more-options" },
];

export const HU_MONEY_REASONS: HuMoneyReason[] = ["Food", "School", "Transport", "Fun", "Other"];

export const HU_SEND_CONTACTS: HuSendContact[] = ["Anna", "David", "More contacts"];

export const HU_SEND_APPROVAL_THRESHOLD = 5000;

export const HU_KIDS_WEEKLY_ALLOWANCE = 5000;

export const HU_KIDS_INITIAL_TASKS: HuKidsTask[] = [
  { id: "load-dishwasher", title: "Load dishwasher", recurrence: "Weekly", reward: 800, status: "waiting-parent", parentNote: "Waiting for parent confirmation" },
  { id: "brush-teeth", title: "Brush your teeth", recurrence: "Daily", reward: 200, status: "todo" },
  { id: "finish-homework", title: "Finish your homework", recurrence: "Weekly", reward: 1500, status: "todo" },
  { id: "walk-the-dog", title: "Walk the dog", recurrence: "Daily", reward: 300, status: "todo" },
  { id: "tidy-room", title: "Tidy your room", recurrence: "Weekly", reward: 600, status: "approved", parentNote: "Great job!" },
  { id: "read-book", title: "Read a book", recurrence: "Weekly", reward: 1000, status: "todo" },
  { id: "water-plants", title: "Water the plants", recurrence: "Daily", reward: 150, status: "approved", parentNote: "Well done!" },
  { id: "set-the-table", title: "Set the table", recurrence: "Daily", reward: 250, status: "todo" },
];

export const HU_KIDS_INITIAL_GOALS: SavingGoal[] = HU_KIDS_GOALS.map((goal) => ({ ...goal }));

export const HU_KIDS_INITIAL_LEARN_MODULES: LearnModule[] = HU_KIDS_LEARN_MODULES.map((module) => ({ ...module }));

export const HU_PENDING_ACTIONS: HuPendingAction[] = [
  {
    id: "grandpa-food",
    title: "Request Money",
    person: "Grandpa Andrei",
    description: "30 Ron for Food",
    amountLabel: "30 RON",
    status: "pending",
    tone: "green",
    icon: "hu-kids-request-money",
    flow: "request-money",
    createdAt: "Today 14:31",
  },
  {
    id: "mom-trip",
    title: "School trip",
    person: "Mom",
    description: "4.000 HUF waiting for approval",
    amountLabel: "4.000 HUF",
    status: "pending",
    tone: "blue",
    icon: "book-open",
    flow: "request-money",
    createdAt: "Today 12:10",
  },
  {
    id: "dad-reward",
    title: "Task reward",
    person: "Dad",
    description: "Clean room reward approved",
    amountLabel: "2.500 HUF",
    status: "approved",
    tone: "pink",
    icon: "clipboard-check",
    flow: "request-money",
    createdAt: "Yesterday",
  },
];

export const HU_KIDS_TOTAL_MONEY = 35628;

export const HU_KIDS_WEEKLY_LIMIT = 75000;

export const HU_KIDS_WEEKLY_SPENT = 25000;

export const HU_KIDS_DAYS_LEFT = 2;

export const HU_KIDS_TRANSACTIONS: HuKidsTransaction[] = [
  {
    id: "hu-kids-from-dad",
    day: "12",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Today",
    label: "From Dad",
    details: "Salary November",
    subtitle: "Salary November",
    amount: 11824.33,
    type: "credit",
    category: "Income",
    pfmCategory: "Income",
    pfmSubcategory: "Allowance",
    status: "Booked",
    time: "09:14",
  },
  {
    id: "hu-kids-mcdonalds",
    day: "12",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Today",
    label: "McDonalds",
    details: "Lunch with card",
    amount: -940.21,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Fast food",
    status: "Booked",
    merchantLogo: "mcdonalds",
    time: "12:31",
  },
  {
    id: "hu-kids-spotify",
    day: "12",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Today",
    label: "Spotify",
    details: "Music subscription",
    subtitle: "Monthly plan",
    amount: -499,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Streaming",
    status: "Pending",
    merchantLogo: "spotify",
    time: "18:07",
  },
  {
    id: "hu-kids-tesco",
    day: "12",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Today",
    label: "Tesco",
    details: "Snacks and drinks",
    amount: -1280.5,
    type: "debit",
    category: "Shopping",
    pfmCategory: "Shopping",
    pfmSubcategory: "Groceries",
    status: "Booked",
    merchantLogo: "tesco",
    time: "20:45",
  },
  {
    id: "hu-kids-youtube",
    day: "11",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Yesterday",
    label: "YouTube",
    details: "Monthly subscription",
    subtitle: "Monthly, due tomorrow",
    amount: -550,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Streaming",
    status: "Pending",
    merchantLogo: "youtube",
    time: "08:22",
  },
  {
    id: "hu-kids-apple-refund",
    day: "11",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Yesterday",
    label: "Refund from Apple",
    details: "Expected by 15 June",
    subtitle: "Expected by 15 June",
    amount: 612.8,
    type: "credit",
    category: "Shopping",
    pfmCategory: "Shopping",
    pfmSubcategory: "Refund",
    status: "Pending",
    merchantLogo: "apple",
    time: "14:53",
  },
  {
    id: "hu-kids-roblox",
    day: "11",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "Yesterday",
    label: "Roblox",
    details: "800 Robux pack",
    amount: -1190,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Games",
    status: "Booked",
    merchantLogo: "roblox",
    time: "21:38",
  },
  {
    id: "hu-kids-netflix",
    day: "10",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "10 JUN",
    label: "Netflix",
    details: "Family plan share",
    subtitle: "Monthly subscription",
    amount: -799,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Streaming",
    status: "Booked",
    merchantLogo: "netflix",
    time: "07:05",
  },
  {
    id: "hu-kids-from-mom",
    day: "10",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "10 JUN",
    label: "From Mom",
    details: "Birthday gift",
    subtitle: "Pocket money",
    amount: 3000,
    type: "credit",
    category: "Income",
    pfmCategory: "Income",
    pfmSubcategory: "Gift",
    status: "Booked",
    time: "16:40",
  },
  {
    id: "hu-kids-ikea",
    day: "9",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "9 JUN",
    label: "IKEA",
    details: "Desk lamp",
    amount: -3450,
    type: "debit",
    category: "Shopping",
    pfmCategory: "Shopping",
    pfmSubcategory: "Home",
    status: "Booked",
    merchantLogo: "ikea",
    time: "11:27",
  },
  {
    id: "hu-kids-steam",
    day: "8",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "8 JUN",
    label: "Steam",
    details: "Game purchase",
    amount: -2499,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Games",
    status: "Booked",
    merchantLogo: "steam",
    time: "19:12",
  },
  {
    id: "hu-kids-amazon",
    day: "8",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "8 JUN",
    label: "Amazon",
    details: "Books and stationery",
    amount: -1850.75,
    type: "debit",
    category: "Shopping",
    pfmCategory: "Shopping",
    pfmSubcategory: "Online",
    status: "Booked",
    merchantLogo: "amazon",
    time: "13:55",
  },
  {
    id: "hu-kids-mcdonalds-2",
    day: "8",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "8 JUN",
    label: "McDonalds",
    details: "Ice cream",
    amount: -420,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Fast food",
    status: "Booked",
    merchantLogo: "mcdonalds",
    time: "17:08",
  },
  {
    id: "hu-kids-nintendo",
    day: "7",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "7 JUN",
    label: "Nintendo",
    details: "eShop credit",
    amount: -1500,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Games",
    status: "Pending",
    merchantLogo: "nintendo",
    time: "22:41",
  },
  {
    id: "hu-kids-playstation",
    day: "6",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "6 JUN",
    label: "PlayStation",
    details: "PS Plus monthly",
    amount: -990,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Games",
    status: "Booked",
    merchantLogo: "playstation",
    time: "15:33",
  },
  {
    id: "hu-kids-youtube-2",
    day: "6",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "6 JUN",
    label: "YouTube",
    details: "Premium family",
    amount: -550,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Streaming",
    status: "Booked",
    merchantLogo: "youtube",
    time: "02:19",
  },
  {
    id: "hu-kids-allowance",
    day: "5",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "5 JUN",
    label: "Weekly allowance",
    details: "From parents",
    subtitle: "Weekly pocket money",
    amount: 2500,
    type: "credit",
    category: "Income",
    pfmCategory: "Income",
    pfmSubcategory: "Allowance",
    status: "Booked",
    time: "10:00",
  },
  {
    id: "hu-kids-spotify-2",
    day: "3",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "3 JUN",
    label: "Spotify",
    details: "Student plan",
    amount: -299,
    type: "debit",
    category: "Leisure time",
    pfmCategory: "Leisure time",
    pfmSubcategory: "Streaming",
    status: "Booked",
    merchantLogo: "spotify",
    time: "06:48",
  },
  {
    id: "hu-kids-amazon-2",
    day: "1",
    month: "JUN",
    monthKey: "2026-06",
    monthTitle: "1 JUN",
    label: "Amazon",
    details: "Headphones",
    amount: -4200,
    type: "debit",
    category: "Shopping",
    pfmCategory: "Shopping",
    pfmSubcategory: "Electronics",
    status: "Booked",
    merchantLogo: "amazon",
    time: "23:51",
  },
  {
    id: "hu-kids-cashback",
    day: "28",
    month: "MAY",
    monthKey: "2026-05",
    monthTitle: "28 MAY",
    label: "Cashback reward",
    details: "Card spending bonus",
    subtitle: "Monthly cashback",
    amount: 184.6,
    type: "credit",
    category: "Income",
    pfmCategory: "Income",
    pfmSubcategory: "Cashback",
    status: "Booked",
    time: "04:27",
  },
];
