import { defineTemplate, screenshotUrl } from '../templateDefaults'
import type { TemplateRegistryItem } from '../contracts'
export const ANALYTICS_TEMPLATES: readonly TemplateRegistryItem[] = [
  defineTemplate({
    id: 'template-analytics',
    name: 'Analytics',
    sourcePath: 'screenshots/Analytics.jpg',
    imageSrc: screenshotUrl('Analytics.jpg'),
    width: 754,
    height: 1628,
    format: 'jpg',
    screenFamily: 'analytics',
    runtimeScreenId: 'pi.analytics.overview',
    relatedScreens: ['pi.analytics.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-analytics'],
    relatedComponents: [
      'analytics.spendings',
      'pfm.category-icon',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'analytics-overview',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the My Spendings analytics overview with code-native chart bars, add-cash banner, money-out summary, and five-item bottom navigation.',
      'Creates reusable chart and five-tab navigation primitives for future analytics templates.',
    ],
  }),
  defineTemplate({
    id: 'template-spending-money-out-code',
    name: 'Spending money out',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::spending-money-out',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'analytics',
    runtimeScreenId: 'pi.analytics.overview',
    relatedScreens: ['pi.analytics.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-analytics'],
    relatedComponents: [
      'analytics.spendings',
      'pfm.category-icon',
      'ui.section-heading-divider',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'spending-money-out',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only Spending category breakdown template with total card, bar chart, category rows, and proportional row bars.',
      'Extends the Analytics screenshot template with a reusable money-out category state for future PFM prompts.',
    ],
  }),
]
