import type { RoboExistingGoal } from './types'
import type { InvestmentHistoryOrder, InvestmentHistoryTransaction } from '@/app/config/investmentsPortfolioConfig'
export const INITIAL_CZ_ROBO_GOALS: readonly RoboExistingGoal[] = [
  {
    id: 'goal-4-strategic',
    name: 'Build long-term wealth',
    purpose: 'General build-up wealth',
    currentInteger: '100 000',
    currentDecimals: ',00 CZK',
    returnLabel: '+1 100,00 CZK (+1,36%)',
    returnTone: 'positive',
    targetInteger: '100 000',
    targetDecimals: ',00 CZK',
    horizonYears: 3,
    startDate: '15 Feb 2025',
    endDate: '15 Feb 2028',
    portfolioId: 'basket-sustainable-balanced-jp-morgan-global-growth',
    basketId: '3333343141',
    basketKey: 'jp-morgan-global-growth',
    basketIsin: 'RS34343143143',
    transactions: [
      {
        id: 'goal-4-strategic-sell-nano-transaction',
        securityId: 'robo-nano-chip-equity',
        date: '2026-06-18T12:00:00.000Z',
        title: 'Nano-Chip Equity Fund',
        amount: 303.15,
        quantity: 1.5,
        currency: 'CZK',
        type: 'SELL',
        tone: 'negative',
      } satisfies InvestmentHistoryTransaction,
      {
        id: 'goal-4-strategic-sell-quantum-transaction',
        securityId: 'robo-quantum-computing-alpha',
        date: '2026-08-20T12:00:00.000Z',
        title: 'Quantum Computing Alpha',
        amount: 455.82,
        quantity: 2,
        currency: 'CZK',
        type: 'SELL',
        tone: 'negative',
      } satisfies InvestmentHistoryTransaction,
    ],
    orders: [
      {
        id: 'goal-4-strategic-sell-nano-order',
        securityId: 'robo-nano-chip-equity',
        date: '2026-06-18T12:00:00.000Z',
        title: 'Nano-Chip Equity Fund',
        amount: 303.15,
        quantity: 1.5,
        currency: 'CZK',
        orderType: 'SELL',
        status: 'EXECUTED',
        tone: 'negative',
      } satisfies InvestmentHistoryOrder,
      {
        id: 'goal-4-strategic-sell-quantum-order',
        securityId: 'robo-quantum-computing-alpha',
        date: '2026-08-20T12:00:00.000Z',
        title: 'Quantum Computing Alpha',
        amount: 455.82,
        quantity: 2,
        currency: 'CZK',
        orderType: 'SELL',
        status: 'EXECUTED',
        tone: 'negative',
      } satisfies InvestmentHistoryOrder,
    ],
  },
  {
    id: 'goal-2-purchase',
    name: 'My future home',
    purpose: 'Saving for a major purchase',
    currentInteger: '51 241',
    currentDecimals: ',33 CZK',
    returnLabel: '+241,33 CZK (+0,47%)',
    returnTone: 'positive',
    targetInteger: '250 000',
    targetDecimals: ',00 CZK',
    horizonYears: 10,
    startDate: '15 Feb 2025',
    endDate: '15 Feb 2035',
    portfolioId: 'basket-balanced-core-blackrock-credit-opportunities',
    basketId: 'blackrock-credit-opportunities',
    basketKey: 'blackrock-credit-opportunities',
    basketIsin: 'CZROBO000002',
  },
  {
    id: 'goal-3-strategic',
    name: 'Financial freedom',
    purpose: 'Retirement',
    currentInteger: '5 000',
    currentDecimals: ',00 CZK',
    returnLabel: '0 total return',
    returnTone: 'neutral',
    targetInteger: '100 000',
    targetDecimals: ',00 CZK',
    horizonYears: 3,
    startDate: '15 Feb 2025',
    endDate: '15 Feb 2028',
    portfolioId: 'basket-steady-income-chase-regular-eur',
    basketId: 'chase-regular-eur',
    basketKey: 'chase-regular-eur',
    basketIsin: 'CZROBO000007',
  },
  {
    id: 'goal-4-inflation',
    name: 'Protect my savings',
    purpose: 'Saving for unforeseen circumstances',
    currentInteger: '100 000',
    currentDecimals: ',00 CZK',
    returnLabel: '-1 100,00 CZK (-1,36%)',
    returnTone: 'negative',
    targetInteger: '100 000',
    targetDecimals: ',00 CZK',
    horizonYears: 3,
    startDate: '15 Feb 2025',
    endDate: '15 Feb 2028',
    portfolioId: 'basket-balanced-core-onemarkets-eur-collection',
    basketId: 'onemarkets-eur-collection',
    basketKey: 'onemarkets-eur-collection',
    basketIsin: 'CZROBO000003',
  },
] as const
