import type { ScreenId } from '@/app/state/demoTypes'
import type { ScreenMeta } from '../contracts'
import { ALL_COUNTRIES } from '../countries'

export const PAYMENTS_SCREENS = {
  'pi.payments.overview': {
    id: 'pi.payments.overview',
    label: 'PI Payments overview',
    runtimeScreen: 'payments',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'implemented',
    layoutFamily: 'payments',
    componentPath: 'src/app/screens/payments/PaymentsScreen.tsx',
    features: ['fx_newPaymentsHub'],
    screenshots: [],
    similarTo: ['pi.more.overview'],
  },
  'pi.payment.domestic-create': {
    id: 'pi.payment.domestic-create',
    label: 'PI Domestic payment create',
    runtimeScreen: 'domestic-payment',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'implemented',
    layoutFamily: 'payment-flow',
    componentPath: 'src/app/screens/payments/DomesticPaymentFlowScreens.tsx',
    features: ['fx_newPaymentsHub'],
    screenshots: ['screenshots/Payment.png'],
    similarTo: ['pi.payment.review'],
  },
  'pi.payment.review': {
    id: 'pi.payment.review',
    label: 'PI Payment review data',
    runtimeScreen: 'payment-review',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'implemented',
    layoutFamily: 'payment-flow',
    componentPath: 'src/app/screens/payments/DomesticPaymentFlowScreens.tsx',
    features: ['fx_newPaymentsHub'],
    screenshots: ['screenshots/Review.png'],
    similarTo: ['pi.payment.domestic-create', 'pi.payment.sign'],
  },
  'pi.payment.sign': {
    id: 'pi.payment.sign',
    label: 'PI Payment sign',
    runtimeScreen: 'payment-sign',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'implemented',
    layoutFamily: 'payment-flow',
    componentPath: 'src/app/screens/payments/DomesticPaymentFlowScreens.tsx',
    features: ['fx_newPaymentsHub'],
    screenshots: ['screenshots/Language Selection.png'],
    similarTo: ['pi.payment.review', 'pi.payment.success'],
  },
  'pi.payment.success': {
    id: 'pi.payment.success',
    label: 'PI Payment success',
    runtimeScreen: 'payment-success',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'implemented',
    layoutFamily: 'payment-flow',
    componentPath: 'src/app/screens/payments/DomesticPaymentFlowScreens.tsx',
    features: ['fx_newPaymentsHub'],
    screenshots: ['screenshots/Transfer to new phone.png'],
    similarTo: ['pi.payment.sign'],
  },
} satisfies Partial<Record<ScreenId, ScreenMeta>>
