import { defineTemplate, screenshotUrl } from '../templateDefaults'
import type { TemplateRegistryItem } from '../contracts'
export const PAYMENTS_TEMPLATES: readonly TemplateRegistryItem[] = [
  defineTemplate({
    id: 'template-67',
    name: '67',
    sourcePath: 'screenshots/67.png',
    imageSrc: screenshotUrl('67.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'payments',
    relatedScreens: ['pi.payments.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-payments-menu'],
    relatedComponents: [
      'payments.menu',
      'accounts.transaction-search',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'recurrent-payment',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Shares the same phone surface, header, tab bar, search strip, section title, and dot-menu primitives with template 52.',
      'The standing-order row is data-driven, so further payment-list templates can reuse the same shape.',
    ],
  }),
  defineTemplate({
    id: 'template-error-to-be',
    name: 'Error to be',
    sourcePath: 'screenshots/Error to be.png',
    imageSrc: screenshotUrl('Error to be.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.success', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: ['ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'error-status',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Shares the feedback status screen primitive with Informative, Pending, Success, and Warning templates.',
      'Reconstructs the title, help action, red status icon, lorem copy block, and fixed bottom CTA as JSX.',
    ],
  }),
  defineTemplate({
    id: 'template-informative',
    name: 'Informative',
    sourcePath: 'screenshots/Informative.png',
    imageSrc: screenshotUrl('Informative.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.success', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: ['ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'informative-status',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Introduces a reusable feedback status screen primitive with help-only top chrome, centered status icon, body copy, and fixed bottom CTA.',
      'This variant renders the neutral informational icon and title while sharing layout with Pending, Success, Error, and Warning.',
    ],
  }),
  defineTemplate({
    id: 'template-language-selection',
    name: 'Language Selection',
    sourcePath: 'screenshots/Language Selection.png',
    imageSrc: screenshotUrl('Language Selection.png'),
    width: 375,
    height: 812,
    format: 'png',
    screenFamily: 'payment-flow',
    runtimeScreenId: 'pi.payment.sign',
    relatedScreens: ['pi.payment.sign', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment', 'pi.transaction-redo-payment'],
    relatedComponents: [
      'payments.domestic-flow',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'sign-pin',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'The source filename is `Language Selection`, but the screenshot content is a Sign/PIN screen; the registry maps it to the reconstructed sign-pin code preview.',
      'Reuses the shared phone surface, back chrome, PIN input line treatment, fixed bottom CTA, and home indicator.',
    ],
  }),
  defineTemplate({
    id: 'template-new-request-with-push',
    name: 'New request with push',
    sourcePath: 'screenshots/New request with push.png',
    imageSrc: screenshotUrl('New request with push.png'),
    width: 377,
    height: 871,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.domestic-create', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: [
      'shell.page-header',
      'ui.text-field',
      'ui.amount-field',
      'ui.section-heading-divider',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'push-request-form',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the request-with-push form with shared TextField, AmountField, SectionHeadingDivider, and primary CTA primitives.',
      'Dropdown affordances and amount/currency rows now come from the same form components used by runtime payment flows.',
    ],
  }),
  defineTemplate({
    id: 'template-payment',
    name: 'Payment',
    sourcePath: 'screenshots/Payment.png',
    imageSrc: screenshotUrl('Payment.png'),
    width: 375,
    height: 1378,
    format: 'png',
    screenFamily: 'payment-flow',
    runtimeScreenId: 'pi.payment.domestic-create',
    relatedScreens: ['pi.payment.domestic-create', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment', 'pi.transaction-redo-payment'],
    relatedComponents: [
      'payments.domestic-flow',
      'shell.page-header',
      'ui.text-field',
      'ui.amount-field',
      'ui.section-heading-divider',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'domestic-payment-form',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Domestic payment entry form with shared PageHeader, SectionHeadingDivider, TextField, AmountField, camera/dropdown affordances, instant-payment toggle, and fixed Next CTA.',
      'The runtime Domestic payment screen and the template preview now use the same field component family for dropdowns, text inputs, and amount/currency input.',
    ],
  }),
  defineTemplate({
    id: 'template-pending',
    name: 'Pending',
    sourcePath: 'screenshots/Pending.png',
    imageSrc: screenshotUrl('Pending.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.success', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: ['ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'pending-status',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Shares the feedback status screen primitive with Informative, Success, Error, and Warning templates.',
      'Reconstructs the neutral pending/hourglass status treatment, lorem copy block, and fixed bottom CTA as JSX.',
    ],
  }),
  defineTemplate({
    id: 'template-review-request',
    name: 'Review request',
    sourcePath: 'screenshots/Review request.png',
    imageSrc: screenshotUrl('Review request.png'),
    width: 377,
    height: 1281,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.review', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: ['shell.page-header', 'ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'review-request',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Review request confirmation screen with payer, account, and payment-information sections rendered as read-only rows.',
      'Shares the read-only row and section-title primitives with Review data and Transaction detail templates.',
    ],
  }),
  defineTemplate({
    id: 'template-review',
    name: 'Review',
    sourcePath: 'screenshots/Review.png',
    imageSrc: screenshotUrl('Review.png'),
    width: 375,
    height: 1077,
    format: 'png',
    screenFamily: 'payment-flow',
    runtimeScreenId: 'pi.payment.review',
    relatedScreens: ['pi.payment.review', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment', 'pi.transaction-redo-payment'],
    relatedComponents: [
      'payments.domestic-flow',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'review-data',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Review data payment-order screen with a read-only payment summary, Save as template toggle, and fixed Sign CTA.',
      'Extends the payment-flow template family without embedding the source PNG as the implementation.',
    ],
  }),
  defineTemplate({
    id: 'template-success-to-be',
    name: 'Success to be',
    sourcePath: 'screenshots/Success to be.png',
    imageSrc: screenshotUrl('Success to be.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.success', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: ['ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'success-status',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Shares the feedback status screen primitive with Informative, Pending, Error, and Warning templates.',
      'Reconstructs the green success icon, `Successfully requested` title, lorem copy block, and fixed bottom CTA as JSX.',
    ],
  }),
  defineTemplate({
    id: 'template-transfer-to-new-phone',
    name: 'Transfer to new phone',
    sourcePath: 'screenshots/Transfer to new phone.png',
    imageSrc: screenshotUrl('Transfer to new phone.png'),
    width: 375,
    height: 812,
    format: 'png',
    screenFamily: 'payment-flow',
    runtimeScreenId: 'pi.payment.success',
    relatedScreens: ['pi.payment.success', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment', 'pi.transaction-redo-payment'],
    relatedComponents: [
      'payments.domestic-flow',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'successful-payment',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'The source filename is `Transfer to new phone`, but the screenshot content is a Successful payment screen; the registry maps it to a success-payment code preview.',
      'Reuses the same success icon and bottom CTA pattern as the Domestic payment success runtime screen.',
    ],
  }),
  defineTemplate({
    id: 'template-warning-to-be',
    name: 'Warning to be',
    sourcePath: 'screenshots/Warning to be.png',
    imageSrc: screenshotUrl('Warning to be.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'payment-flow',
    relatedScreens: ['pi.payment.success', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: ['ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'warning-status',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Shares the feedback status screen primitive with Informative, Pending, Success, and Error templates.',
      'Reconstructs the orange warning/bell status icon, lorem copy block, and fixed bottom CTA as JSX.',
    ],
  }),
  defineTemplate({
    id: 'template-payments-menu-code',
    name: 'Payments menu',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::payments-menu',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'payments',
    runtimeScreenId: 'pi.payments.overview',
    relatedScreens: ['pi.payments.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-payments-menu'],
    relatedComponents: [
      'payments.menu',
      'payments.other-shortcut',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'payments-menu',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template based on the runtime Payments menu and country-scoped payments config.',
      'Reuses the Payments hero card family, OTHER shortcut carousel items, header actions, and five-tab bottom navigation.',
    ],
  }),
  defineTemplate({
    id: 'template-new-payment-sheet-code',
    name: 'New payment sheet',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::new-payment-sheet',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'payments',
    relatedScreens: ['pi.payments.overview', 'platform.design-system'],
    flowIds: ['pi.new-domestic-payment'],
    relatedComponents: [
      'shell.bottom-sheet',
      'payments.new-payment-sheet',
      'payments.new-payment-action',
      'payments.new-payment-discover-banner',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'new-payment-sheet',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the Payments New payment bottom sheet using the same action rows and discover banner as the runtime sheet.',
      'Keeps the corrected 16px sheet padding and 4px discover-banner title/subtitle spacing visible in the reusable template grid.',
    ],
  }),
]
