import { defineTemplate, screenshotUrl } from '../templateDefaults'
import type { TemplateRegistryItem } from '../contracts'
export const PRODUCTS_TEMPLATES: readonly TemplateRegistryItem[] = [
  defineTemplate({
    id: 'template-apple-pay',
    name: 'Apple pay',
    sourcePath: 'screenshots/Apple pay.png',
    imageSrc: screenshotUrl('Apple pay.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'products',
    relatedScreens: ['pi.products.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu'],
    relatedComponents: ['products.menu', 'ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'apple-pay-activation',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Apple Pay activation screen as JSX with close action, card/device hero, explanatory copy, fixed bottom CTA, and home indicator.',
      'The hero is code-native CSS composition so this template can be reused without embedding the PNG as the implementation surface.',
    ],
  }),
  defineTemplate({
    id: 'template-cards',
    name: 'Cards',
    sourcePath: 'screenshots/Cards.jpg',
    imageSrc: screenshotUrl('Cards.jpg'),
    width: 754,
    height: 1996,
    format: 'jpg',
    screenFamily: 'products',
    relatedScreens: ['pi.products.overview', 'pi.account.detail', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu', 'pi.home-to-account-detail'],
    relatedComponents: [
      'products.product-card',
      'accounts.transaction-search',
      'accounts.transaction-row',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'cards-overview',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Cards overview as JSX with a generated debit-card surface, free-to-spend balance, wallet actions, shortcuts, search, transaction rows, and bottom navigation.',
      'Shares shortcut and transaction-row primitives with account detail and transaction detail templates.',
    ],
  }),
  defineTemplate({
    id: 'template-product-selection',
    name: 'Product selection',
    sourcePath: 'screenshots/Product selection.jpg',
    imageSrc: screenshotUrl('Product selection.jpg'),
    width: 377,
    height: 814,
    format: 'jpg',
    screenFamily: 'products',
    relatedScreens: ['pi.products.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu'],
    relatedComponents: [
      'products.menu',
      'ui.radio-button',
      'ui.primary-button',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'product-selection',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the product-selection screen with radio rows, default-product toggle, Access CTA, and bottom navigation.',
      'Uses shared radio and mini bottom-navigation primitives so future product picker flows can reuse the layout.',
    ],
  }),
  defineTemplate({
    id: 'template-product',
    name: 'Product',
    sourcePath: 'screenshots/Product.png',
    imageSrc: screenshotUrl('Product.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'products',
    runtimeScreenId: 'pi.products.detail',
    relatedScreens: ['pi.products.detail', 'pi.products.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu'],
    relatedComponents: [
      'shell.page-header',
      'products.menu',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'product-detail',
    implementationPath: 'src/app/screens/products/ProductDetailScreen.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Product template as a Level 1 page using the shared PageHeader, Figma-sourced 327x160 product illustration, body copy, and reusable PrimaryButton.',
      'Products bottom-sheet rows open this runtime detail page and pass the selected row title, while images are mapped from the Meniga Harmonization Icons Pictures section.',
    ],
  }),
  defineTemplate({
    id: 'template-rs-travel-insurance',
    name: 'RS - Travel Insurance',
    sourcePath: 'screenshots/RS - Travel Insurance.png',
    imageSrc: screenshotUrl('RS - Travel Insurance.png'),
    width: 377,
    height: 814,
    format: 'png',
    countries: ['RS'],
    screenFamily: 'products',
    relatedScreens: ['pi.products.overview', 'pi.more.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu'],
    relatedComponents: ['products.menu', 'ui.primary-button', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'travel-insurance-detail',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the travel-insurance detail screen with back/help chrome, code-native travel hero scene, body copy, and fixed Proceed CTA.',
      'Keeps the screenshot as source evidence while avoiding a screenshot-as-implementation PNG dependency.',
    ],
  }),
  defineTemplate({
    id: 'template-products-menu-code',
    name: 'Products menu',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::products-menu',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'products',
    runtimeScreenId: 'pi.products.overview',
    relatedScreens: ['pi.products.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu'],
    relatedComponents: [
      'products.menu',
      'products.shopsmart-offer-card',
      'accounts.transaction-search',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'products-menu',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template derived from the Products runtime menu and products config.',
      'Reuses the segmented Banking/ShopSmart treatment, Products offer card, product card grid, and bottom navigation.',
    ],
  }),
  defineTemplate({
    id: 'template-products-shopsmart-code',
    name: 'Products ShopSmart',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::products-shopsmart',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'products',
    runtimeScreenId: 'pi.products.overview',
    relatedScreens: ['pi.products.overview', 'platform.design-system'],
    flowIds: ['pi.home-to-products-menu'],
    relatedComponents: [
      'products.menu',
      'products.offer-card',
      'products.product-card',
      'shell.bottom-navigation',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'products-shopsmart',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the ShopSmart tab state using the products menu config, ShopsmartOfferCard list, summary row, ALL OFFERS divider, and search/filter strip.',
      'Complements the Banking products template so the tabbed Products family has both reusable states.',
    ],
  }),
]
