import type { ScreenId } from '@/app/state/demoTypes'
import type { ScreenMeta } from '../contracts'
import { ALL_COUNTRIES } from '../countries'

export const IDENTITY_SCREENS = {
  'pi.prelogin.inactive': {
    id: 'pi.prelogin.inactive',
    label: 'PI Pre-login inactive',
    runtimeScreen: 'prelogin-inactive',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'prelogin',
    componentPath: 'src/app/components/PreLoginScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.prelogin.active'],
  },
  'pi.prelogin.active': {
    id: 'pi.prelogin.active',
    label: 'PI Pre-login active',
    runtimeScreen: 'prelogin-active',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'prelogin',
    componentPath: 'src/app/components/PreLoginActiveScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.prelogin.inactive'],
  },
  'pi.co-apping.session': {
    id: 'pi.co-apping.session',
    label: 'PI Co-Apping session',
    runtimeScreen: 'co-apping-session',
    products: ['PI'],
    countries: ['CZ', 'SK'],
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'co-apping',
    componentPath: 'src/app/components/CoAppingSessionScreen.tsx',
    features: [],
    screenshots: [],
    similarTo: [],
  },
  'pi.language.selector': {
    id: 'pi.language.selector',
    label: 'PI language selector',
    runtimeScreen: 'language-selector',
    products: ['PI'],
    countries: ALL_COUNTRIES,
    designSystems: ['current'],
    status: 'partial',
    layoutFamily: 'prelogin',
    componentPath: 'src/app/components/LanguageSelector.tsx',
    features: [],
    screenshots: [],
    similarTo: ['pi.prelogin.active'],
  },
} satisfies Partial<Record<ScreenId, ScreenMeta>>
