import { defineTemplate, screenshotUrl } from '../templateDefaults'
import type { TemplateRegistryItem } from '../contracts'
export const IDENTITY_TEMPLATES: readonly TemplateRegistryItem[] = [
  defineTemplate({
    id: 'template-activate-mtoken',
    name: 'Activate mToken',
    sourcePath: 'screenshots/Activate mToken.jpg',
    imageSrc: screenshotUrl('Activate mToken.jpg'),
    width: 754,
    height: 1628,
    format: 'jpg',
    screenFamily: 'prelogin',
    relatedScreens: ['pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.prelogin-to-home.active'],
    relatedComponents: [
      'prelogin.active',
      'ui.radio-button',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'activate-mtoken',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the Activate Mobile Token choice screen with shared top chrome, radio option rows, CSS hero art, and fixed Start CTA.',
      'Shares the same radio-row primitive with Generate Token, Product selection, and account-selection panel templates.',
    ],
  }),
  defineTemplate({
    id: 'template-generate-token',
    name: 'Generate Token',
    sourcePath: 'screenshots/Generate Token.png',
    imageSrc: screenshotUrl('Generate Token.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'prelogin',
    relatedScreens: ['pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.prelogin-to-home.active'],
    relatedComponents: [
      'prelogin.active',
      'ui.radio-button',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'generate-token',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the token-generation screen with logout/help chrome, token panel, reusable radio option rows, and bottom Generate CTA.',
      'Shares radio-row and CTA primitives with Product selection and account-selection panel templates.',
    ],
  }),
  defineTemplate({
    id: 'template-tutorial-1',
    name: 'Tutorial 1',
    sourcePath: 'screenshots/Tutorial 1.png',
    imageSrc: screenshotUrl('Tutorial 1.png'),
    width: 377,
    height: 814,
    format: 'png',
    screenFamily: 'prelogin',
    relatedScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.prelogin-to-home.active'],
    relatedComponents: [
      'prelogin.inactive',
      'prelogin.active',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'tutorial-intro',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Reconstructs the tutorial/webview intro with loading chrome, progress bar, device media area, playback controls, carousel dots, and skip/back/next actions.',
      'Adds a reusable webview/tutorial composition pattern for future onboarding templates.',
    ],
  }),
  defineTemplate({
    id: 'template-prelogin-inactive-code',
    name: 'Prelogin inactive',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::prelogin-inactive',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'prelogin',
    runtimeScreenId: 'pi.prelogin.inactive',
    relatedScreens: ['pi.prelogin.inactive', 'platform.design-system'],
    flowIds: ['pi.prelogin-to-home.active'],
    relatedComponents: [
      'prelogin.inactive',
      'prelogin.language-selector',
      'brand.unicredit-logo',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'prelogin-inactive',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the inactive pre-login activation surface, including logo/language header, product teaser rows, CTA, and bottom utility links.',
      'Uses code-native background/card art rather than a PNG so pre-login prompt flows can reuse the layout vocabulary.',
    ],
  }),
  defineTemplate({
    id: 'template-prelogin-active-code',
    name: 'Prelogin active',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::prelogin-active',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'prelogin',
    runtimeScreenId: 'pi.prelogin.active',
    relatedScreens: ['pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.prelogin-to-home.active'],
    relatedComponents: [
      'prelogin.active',
      'prelogin.language-selector',
      'brand.unicredit-logo',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'prelogin-active',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the active app login posture with title/subtitle, login CTA, language selector, and utility-link row.',
      'Complements the Home dashboard templates with the actual entry-state pattern used before authenticated navigation.',
    ],
  }),
  defineTemplate({
    id: 'template-language-selector-sheet-code',
    name: 'Language selector sheet',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::language-selector-sheet',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'prelogin',
    relatedScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.prelogin-to-home.active'],
    relatedComponents: [
      'prelogin.language-selector',
      'ui.radio-button',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'language-selector-sheet',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the pre-login language selection modal pattern over the inactive background.',
      'Reuses the same radio-row primitive family used by token, product-selection, and account-selection templates.',
    ],
  }),
  defineTemplate({
    id: 'template-more-panel-menu-code',
    name: 'Other panel menu',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::more-panel-menu',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'prelogin',
    relatedScreens: ['pi.prelogin.inactive', 'pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.co-apping.activation'],
    relatedComponents: ['prelogin.other-panel', 'icons.app-icon', 'templates.reconstructed-code'],
    codePreviewId: 'more-panel-menu',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the dark pre-login Other panel using the actual translated panel component.',
      'Keeps smart banking, exchange rates, ATM/branches, and Co-Apping entry as reusable row patterns.',
    ],
  }),
  defineTemplate({
    id: 'template-co-apping-session-code',
    name: 'Co-Apping session',
    sourcePath: 'src/app/components/templates/TemplateCodePreviews.tsx::co-apping-session',
    width: 377,
    height: 814,
    format: 'code',
    sourceKind: 'code-only',
    screenFamily: 'co-apping',
    runtimeScreenId: 'pi.co-apping.session',
    relatedScreens: ['pi.co-apping.session', 'pi.prelogin.active', 'platform.design-system'],
    flowIds: ['pi.co-apping.activation'],
    relatedComponents: [
      'co-apping.session-entry',
      'ui.text-field',
      'ui.primary-button',
      'icons.app-icon',
      'templates.reconstructed-code',
    ],
    codePreviewId: 'co-apping-session',
    implementationPath: 'src/app/components/templates/TemplateCodePreviews.tsx',
    implementationStatus: 'reconstructed-code',
    reuseNotes: [
      'Code-only template for the Co-Apping code-entry screen with hero art, explanatory copy, reusable TextField, privacy helper, and fixed Continue CTA.',
      'Supports future assistant-built support/session flows without inventing a new form pattern.',
    ],
  }),
]
